<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmPrMsPeriodGroups
Inherits System.Windows.Forms.Form
<System.Diagnostics.DebuggerNonUserCode()> _
Protected Overrides Sub Dispose(ByVal disposing As Boolean)
If Disposing AndAlso components IsNot Nothing Then
components.Dispose()
End If
MyBase.Dispose(Disposing)
End Sub
Private components As System.ComponentModel.IContainer
' AutoGenerated Form by Nodalsoft
<System.Diagnostics.DebuggerStepThrough()> _
Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmPrMsPeriodGroups))
        Me.sspStatus = New System.Windows.Forms.StatusStrip
        Me.lblSSStatus = New System.Windows.Forms.ToolStripStatusLabel
        Me.DG1 = New System.Windows.Forms.DataGridView
        Me.dgcPrdGrp_Code = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcPrdGrp_Status = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcPrdGpr_Year = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcTemGrp_Code = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcPrdGrp_DescriptionL = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.TSC1 = New System.Windows.Forms.ToolStripContainer
        Me.TS1 = New System.Windows.Forms.ToolStrip
        Me.TSBNew = New System.Windows.Forms.ToolStripButton
        Me.TSBSave = New System.Windows.Forms.ToolStripButton
        Me.TSBDelete = New System.Windows.Forms.ToolStripButton
        Me.TSBExcel = New System.Windows.Forms.ToolStripButton
        Me.lblCode = New System.Windows.Forms.Label
        Me.txtCode = New System.Windows.Forms.TextBox
        Me.ErrCode = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblStatus = New System.Windows.Forms.Label
        Me.txtStatus = New System.Windows.Forms.TextBox
        Me.ErrStatus = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblYear = New System.Windows.Forms.Label
        Me.txtYear = New System.Windows.Forms.TextBox
        Me.ErrYear = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblTemGrpCode = New System.Windows.Forms.Label
        Me.cmbTemGrpCode = New System.Windows.Forms.ComboBox
        Me.ErrTemGrpCode = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDescriptionL = New System.Windows.Forms.Label
        Me.txtDescriptionL = New System.Windows.Forms.TextBox
        Me.ErrDescriptionL = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.sspStatus.SuspendLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.TSC1.TopToolStripPanel.SuspendLayout()
        Me.TSC1.SuspendLayout()
        Me.TS1.SuspendLayout()
        CType(Me.ErrCode, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrStatus, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrYear, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrTemGrpCode, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDescriptionL, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'sspStatus
        '
        Me.sspStatus.BackColor = System.Drawing.SystemColors.Control
        Me.sspStatus.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.lblSSStatus})
        Me.sspStatus.Location = New System.Drawing.Point(0, 529)
        Me.sspStatus.Name = "sspStatus"
        Me.sspStatus.Size = New System.Drawing.Size(987, 22)
        Me.sspStatus.TabIndex = 3
        Me.sspStatus.Text = "StatusStrip"
        '
        'lblSSStatus
        '
        Me.lblSSStatus.Name = "lblSSStatus"
        Me.lblSSStatus.Size = New System.Drawing.Size(0, 17)
        '
        'DG1
        '
        Me.DG1.AllowUserToAddRows = False
        Me.DG1.AllowUserToDeleteRows = False
        Me.DG1.BackgroundColor = System.Drawing.SystemColors.Window
        Me.DG1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DG1.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.dgcPrdGrp_Code, Me.dgcPrdGrp_Status, Me.dgcPrdGpr_Year, Me.dgcTemGrp_Code, Me.dgcPrdGrp_DescriptionL})
        Me.DG1.Location = New System.Drawing.Point(12, 157)
        Me.DG1.Name = "DG1"
        Me.DG1.ReadOnly = True
        Me.DG1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
        Me.DG1.Size = New System.Drawing.Size(963, 355)
        Me.DG1.TabIndex = 10
        '
        'dgcPrdGrp_Code
        '
        Me.dgcPrdGrp_Code.DataPropertyName = "PrdGrp_Code"
        Me.dgcPrdGrp_Code.FillWeight = 150.0!
        Me.dgcPrdGrp_Code.HeaderText = "Code"
        Me.dgcPrdGrp_Code.Name = "dgcPrdGrp_Code"
        Me.dgcPrdGrp_Code.ReadOnly = True
        Me.dgcPrdGrp_Code.Width = 60
        '
        'dgcPrdGrp_Status
        '
        Me.dgcPrdGrp_Status.DataPropertyName = "PrdGrp_Status"
        Me.dgcPrdGrp_Status.FillWeight = 150.0!
        Me.dgcPrdGrp_Status.HeaderText = "Status"
        Me.dgcPrdGrp_Status.Name = "dgcPrdGrp_Status"
        Me.dgcPrdGrp_Status.ReadOnly = True
        Me.dgcPrdGrp_Status.Width = 60
        '
        'dgcPrdGpr_Year
        '
        Me.dgcPrdGpr_Year.DataPropertyName = "PrdGpr_Year"
        Me.dgcPrdGpr_Year.FillWeight = 150.0!
        Me.dgcPrdGpr_Year.HeaderText = "Year"
        Me.dgcPrdGpr_Year.Name = "dgcPrdGpr_Year"
        Me.dgcPrdGpr_Year.ReadOnly = True
        Me.dgcPrdGpr_Year.Width = 60
        '
        'dgcTemGrp_Code
        '
        Me.dgcTemGrp_Code.DataPropertyName = "TemGrp_Code"
        Me.dgcTemGrp_Code.FillWeight = 150.0!
        Me.dgcTemGrp_Code.HeaderText = "Template Code"
        Me.dgcTemGrp_Code.Name = "dgcTemGrp_Code"
        Me.dgcTemGrp_Code.ReadOnly = True
        '
        'dgcPrdGrp_DescriptionL
        '
        Me.dgcPrdGrp_DescriptionL.DataPropertyName = "PrdGrp_DescriptionL"
        Me.dgcPrdGrp_DescriptionL.FillWeight = 150.0!
        Me.dgcPrdGrp_DescriptionL.HeaderText = "Long Description"
        Me.dgcPrdGrp_DescriptionL.Name = "dgcPrdGrp_DescriptionL"
        Me.dgcPrdGrp_DescriptionL.ReadOnly = True
        Me.dgcPrdGrp_DescriptionL.Width = 250
        '
        'TSC1
        '
        Me.TSC1.BottomToolStripPanelVisible = False
        '
        'TSC1.ContentPanel
        '
        Me.TSC1.ContentPanel.Size = New System.Drawing.Size(987, 1)
        Me.TSC1.Dock = System.Windows.Forms.DockStyle.Top
        Me.TSC1.LeftToolStripPanelVisible = False
        Me.TSC1.Location = New System.Drawing.Point(0, 0)
        Me.TSC1.Name = "TSC1"
        Me.TSC1.RightToolStripPanelVisible = False
        Me.TSC1.Size = New System.Drawing.Size(987, 26)
        Me.TSC1.TabIndex = 12
        Me.TSC1.Text = "TSC1"
        '
        'TSC1.TopToolStripPanel
        '
        Me.TSC1.TopToolStripPanel.Controls.Add(Me.TS1)
        '
        'TS1
        '
        Me.TS1.Dock = System.Windows.Forms.DockStyle.None
        Me.TS1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.TSBNew, Me.TSBSave, Me.TSBDelete, Me.TSBExcel})
        Me.TS1.Location = New System.Drawing.Point(3, 0)
        Me.TS1.Name = "TS1"
        Me.TS1.Size = New System.Drawing.Size(252, 25)
        Me.TS1.TabIndex = 0
        '
        'TSBNew
        '
        Me.TSBNew.AutoSize = False
        Me.TSBNew.Image = CType(resources.GetObject("TSBNew.Image"), System.Drawing.Image)
        Me.TSBNew.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBNew.Name = "TSBNew"
        Me.TSBNew.Size = New System.Drawing.Size(60, 22)
        Me.TSBNew.Text = "New"
        Me.TSBNew.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBSave
        '
        Me.TSBSave.AutoSize = False
        Me.TSBSave.Image = CType(resources.GetObject("TSBSave.Image"), System.Drawing.Image)
        Me.TSBSave.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBSave.Name = "TSBSave"
        Me.TSBSave.Size = New System.Drawing.Size(60, 22)
        Me.TSBSave.Text = "Save"
        Me.TSBSave.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBDelete
        '
        Me.TSBDelete.AutoSize = False
        Me.TSBDelete.Image = CType(resources.GetObject("TSBDelete.Image"), System.Drawing.Image)
        Me.TSBDelete.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBDelete.Name = "TSBDelete"
        Me.TSBDelete.Size = New System.Drawing.Size(60, 22)
        Me.TSBDelete.Text = "Delete"
        Me.TSBDelete.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBExcel
        '
        Me.TSBExcel.AutoSize = False
        Me.TSBExcel.Image = Global.NodalPay.My.Resources.Resources.excel
        Me.TSBExcel.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBExcel.Name = "TSBExcel"
        Me.TSBExcel.Size = New System.Drawing.Size(60, 22)
        Me.TSBExcel.Text = "Excel"
        Me.TSBExcel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'lblCode
        '
        Me.lblCode.AutoSize = True
        Me.lblCode.Location = New System.Drawing.Point(37, 40)
        Me.lblCode.Name = "lblCode"
        Me.lblCode.Size = New System.Drawing.Size(32, 13)
        Me.lblCode.TabIndex = 0
        Me.lblCode.Text = "Code"
        '
        'txtCode
        '
        Me.txtCode.Location = New System.Drawing.Point(157, 40)
        Me.txtCode.MaxLength = 6
        Me.txtCode.Name = "txtCode"
        Me.txtCode.Size = New System.Drawing.Size(46, 20)
        Me.txtCode.TabIndex = 1
        '
        'ErrCode
        '
        Me.ErrCode.ContainerControl = Me
        '
        'lblStatus
        '
        Me.lblStatus.AutoSize = True
        Me.lblStatus.Location = New System.Drawing.Point(37, 60)
        Me.lblStatus.Name = "lblStatus"
        Me.lblStatus.Size = New System.Drawing.Size(37, 13)
        Me.lblStatus.TabIndex = 2
        Me.lblStatus.Text = "Status"
        '
        'txtStatus
        '
        Me.txtStatus.Location = New System.Drawing.Point(157, 60)
        Me.txtStatus.MaxLength = 1
        Me.txtStatus.Name = "txtStatus"
        Me.txtStatus.Size = New System.Drawing.Size(16, 20)
        Me.txtStatus.TabIndex = 2
        '
        'ErrStatus
        '
        Me.ErrStatus.ContainerControl = Me
        '
        'lblYear
        '
        Me.lblYear.AutoSize = True
        Me.lblYear.Location = New System.Drawing.Point(37, 80)
        Me.lblYear.Name = "lblYear"
        Me.lblYear.Size = New System.Drawing.Size(29, 13)
        Me.lblYear.TabIndex = 3
        Me.lblYear.Text = "Year"
        '
        'txtYear
        '
        Me.txtYear.Location = New System.Drawing.Point(157, 80)
        Me.txtYear.MaxLength = 4
        Me.txtYear.Name = "txtYear"
        Me.txtYear.Size = New System.Drawing.Size(34, 20)
        Me.txtYear.TabIndex = 2
        '
        'ErrYear
        '
        Me.ErrYear.ContainerControl = Me
        '
        'lblTemGrpCode
        '
        Me.lblTemGrpCode.AutoSize = True
        Me.lblTemGrpCode.Location = New System.Drawing.Point(37, 100)
        Me.lblTemGrpCode.Name = "lblTemGrpCode"
        Me.lblTemGrpCode.Size = New System.Drawing.Size(79, 13)
        Me.lblTemGrpCode.TabIndex = 4
        Me.lblTemGrpCode.Text = "Template Code"
        '
        'cmbTemGrpCode
        '
        Me.cmbTemGrpCode.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.cmbTemGrpCode.Location = New System.Drawing.Point(157, 100)
        Me.cmbTemGrpCode.Name = "cmbTemGrpCode"
        Me.cmbTemGrpCode.Size = New System.Drawing.Size(250, 21)
        Me.cmbTemGrpCode.TabIndex = 3
        '
        'ErrTemGrpCode
        '
        Me.ErrTemGrpCode.ContainerControl = Me
        '
        'lblDescriptionL
        '
        Me.lblDescriptionL.AutoSize = True
        Me.lblDescriptionL.Location = New System.Drawing.Point(37, 120)
        Me.lblDescriptionL.Name = "lblDescriptionL"
        Me.lblDescriptionL.Size = New System.Drawing.Size(87, 13)
        Me.lblDescriptionL.TabIndex = 5
        Me.lblDescriptionL.Text = "Long Description"
        '
        'txtDescriptionL
        '
        Me.txtDescriptionL.Location = New System.Drawing.Point(157, 120)
        Me.txtDescriptionL.MaxLength = 40
        Me.txtDescriptionL.Name = "txtDescriptionL"
        Me.txtDescriptionL.Size = New System.Drawing.Size(250, 20)
        Me.txtDescriptionL.TabIndex = 4
        '
        'ErrDescriptionL
        '
        Me.ErrDescriptionL.ContainerControl = Me
        '
        'frmPrMsPeriodGroups
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.SystemColors.GradientActiveCaption
        Me.ClientSize = New System.Drawing.Size(987, 551)
        Me.Controls.Add(Me.lblCode)
        Me.Controls.Add(Me.txtCode)
        Me.Controls.Add(Me.lblStatus)
        Me.Controls.Add(Me.txtStatus)
        Me.Controls.Add(Me.lblYear)
        Me.Controls.Add(Me.txtYear)
        Me.Controls.Add(Me.lblTemGrpCode)
        Me.Controls.Add(Me.cmbTemGrpCode)
        Me.Controls.Add(Me.lblDescriptionL)
        Me.Controls.Add(Me.txtDescriptionL)
        Me.Controls.Add(Me.TSC1)
        Me.Controls.Add(Me.sspStatus)
        Me.Controls.Add(Me.DG1)
        Me.Name = "frmPrMsPeriodGroups"
        Me.Text = "Period Groups"
        Me.sspStatus.ResumeLayout(False)
        Me.sspStatus.PerformLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.TSC1.TopToolStripPanel.ResumeLayout(False)
        Me.TSC1.TopToolStripPanel.PerformLayout()
        Me.TSC1.ResumeLayout(False)
        Me.TSC1.PerformLayout()
        Me.TS1.ResumeLayout(False)
        Me.TS1.PerformLayout()
        CType(Me.ErrCode, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrStatus, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrYear, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrTemGrpCode, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDescriptionL, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
Friend WithEvents  lblCode As System.Windows.Forms.Label
Friend WithEvents  txtCode As System.Windows.Forms.TextBox
Friend WithEvents ErrCode As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcPrdGrp_Code As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblStatus As System.Windows.Forms.Label
Friend WithEvents  txtStatus As System.Windows.Forms.TextBox
Friend WithEvents ErrStatus As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcPrdGrp_Status As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblYear As System.Windows.Forms.Label
Friend WithEvents  txtYear As System.Windows.Forms.TextBox
Friend WithEvents ErrYear As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcPrdGpr_Year As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblTemGrpCode As System.Windows.Forms.Label
Friend WithEvents  cmbTemGrpCode As System.Windows.Forms.ComboBox
Friend WithEvents ErrTemGrpCode As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcTemGrp_Code As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblDescriptionL As System.Windows.Forms.Label
Friend WithEvents  txtDescriptionL As System.Windows.Forms.TextBox
Friend WithEvents ErrDescriptionL As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcPrdGrp_DescriptionL As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents sspStatus As System.Windows.Forms.StatusStrip
Friend WithEvents lblSSStatus As System.Windows.Forms.ToolStripStatusLabel
Friend WithEvents DG1 As System.Windows.Forms.DataGridView
Friend WithEvents TSC1 As System.Windows.Forms.ToolStripContainer
Friend WithEvents TS1 As System.Windows.Forms.ToolStrip
Friend WithEvents TSBNew As System.Windows.Forms.ToolStripButton
Friend WithEvents TSBSave As System.Windows.Forms.ToolStripButton
Friend WithEvents TSBDelete As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBExcel As System.Windows.Forms.ToolStripButton
End Class
