<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmPrMsEmployeeExtraDetails
Inherits System.Windows.Forms.Form
<System.Diagnostics.DebuggerNonUserCode()> _
Protected Overrides Sub Dispose(ByVal disposing As Boolean)
If Disposing AndAlso components IsNot Nothing Then
components.Dispose()
End If
MyBase.Dispose(Disposing)
End Sub
Private components As System.ComponentModel.IContainer
' AutoGenerated Form by SC INSOFT LIMITED
<System.Diagnostics.DebuggerStepThrough()> _
Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmPrMsEmployeeExtraDetails))
        Me.sspStatus = New System.Windows.Forms.StatusStrip()
        Me.lblSSStatus = New System.Windows.Forms.ToolStripStatusLabel()
        Me.TSC1 = New System.Windows.Forms.ToolStripContainer()
        Me.TS1 = New System.Windows.Forms.ToolStrip()
        Me.TSBNew = New System.Windows.Forms.ToolStripButton()
        Me.TSBExcel = New System.Windows.Forms.ToolStripButton()
        Me.TSBSave = New System.Windows.Forms.ToolStripButton()
        Me.TSBDelete = New System.Windows.Forms.ToolStripButton()
        Me.ErrEmp_Code = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblEmp_StartDateToPrevServ = New System.Windows.Forms.Label()
        Me.ErrEmp_StartDateToPrevServ = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblPosCat_Code = New System.Windows.Forms.Label()
        Me.ErrPosCat_Code = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblPosRnk_Code = New System.Windows.Forms.Label()
        Me.ErrPosRnk_Code = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblEmp_RetirementDate63 = New System.Windows.Forms.Label()
        Me.ErrEmp_RetirementDate63 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblEmp_RetirementDate65 = New System.Windows.Forms.Label()
        Me.ErrEmp_RetirementDate65 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblEmp_ComDate400Months = New System.Windows.Forms.Label()
        Me.ErrEmp_ComDate400Months = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblEmp_ExtraRatePerHour = New System.Windows.Forms.Label()
        Me.txtEmp_ExtraRatePerHour = New System.Windows.Forms.TextBox()
        Me.ErrEmp_ExtraRatePerHour = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblEmp_DOfNextRateIncrease = New System.Windows.Forms.Label()
        Me.ErrEmp_DOfNextRateIncrease = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblEmp_IsTop = New System.Windows.Forms.Label()
        Me.ErrEmp_IsTop = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblEmp_ProvidentFund = New System.Windows.Forms.Label()
        Me.ErrEmp_ProvidentFund = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblEmp_PensionFund = New System.Windows.Forms.Label()
        Me.ErrEmp_PensionFund = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblEmp_DOfStartPrFund = New System.Windows.Forms.Label()
        Me.ErrEmp_DOfStartPrFund = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblEmp_10PercentDecrease = New System.Windows.Forms.Label()
        Me.ErrEmp_10PercentDecrease = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.DateStartDateToPrevServ = New System.Windows.Forms.DateTimePicker()
        Me.DateRetirementDate63 = New System.Windows.Forms.DateTimePicker()
        Me.DateRetirementDate65 = New System.Windows.Forms.DateTimePicker()
        Me.DateDOfNextRateIncrease = New System.Windows.Forms.DateTimePicker()
        Me.DateDOfStartPrFund = New System.Windows.Forms.DateTimePicker()
        Me.DateComDate400Months = New System.Windows.Forms.DateTimePicker()
        Me.Label6 = New System.Windows.Forms.Label()
        Me.txtEmployeeName = New System.Windows.Forms.TextBox()
        Me.Label5 = New System.Windows.Forms.Label()
        Me.txtEmp_Code = New System.Windows.Forms.TextBox()
        Me.ComboIsTop = New System.Windows.Forms.ComboBox()
        Me.ComboProFund = New System.Windows.Forms.ComboBox()
        Me.ComboPenFund = New System.Windows.Forms.ComboBox()
        Me.Combo10Percent = New System.Windows.Forms.ComboBox()
        Me.ButtonRefScale1 = New System.Windows.Forms.Button()
        Me.ButtonAddScale1 = New System.Windows.Forms.Button()
        Me.ButtonRefScale2 = New System.Windows.Forms.Button()
        Me.ButtonAddScale2 = New System.Windows.Forms.Button()
        Me.ComboScale1 = New System.Windows.Forms.ComboBox()
        Me.ComboScale2 = New System.Windows.Forms.ComboBox()
        Me.btnAutoCalc = New System.Windows.Forms.Button()
        Me.ComboScale3 = New System.Windows.Forms.ComboBox()
        Me.ButtonRefScale3 = New System.Windows.Forms.Button()
        Me.ButtonAddScale3 = New System.Windows.Forms.Button()
        Me.Label1 = New System.Windows.Forms.Label()
        Me.BtnNext = New System.Windows.Forms.Button()
        Me.BtnPrevius = New System.Windows.Forms.Button()
        Me.sspStatus.SuspendLayout()
        Me.TSC1.TopToolStripPanel.SuspendLayout()
        Me.TSC1.SuspendLayout()
        Me.TS1.SuspendLayout()
        CType(Me.ErrEmp_Code, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEmp_StartDateToPrevServ, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrPosCat_Code, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrPosRnk_Code, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEmp_RetirementDate63, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEmp_RetirementDate65, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEmp_ComDate400Months, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEmp_ExtraRatePerHour, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEmp_DOfNextRateIncrease, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEmp_IsTop, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEmp_ProvidentFund, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEmp_PensionFund, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEmp_DOfStartPrFund, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEmp_10PercentDecrease, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'sspStatus
        '
        Me.sspStatus.BackColor = System.Drawing.SystemColors.Control
        Me.sspStatus.ImageScalingSize = New System.Drawing.Size(20, 20)
        Me.sspStatus.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.lblSSStatus})
        Me.sspStatus.Location = New System.Drawing.Point(0, 514)
        Me.sspStatus.Name = "sspStatus"
        Me.sspStatus.Size = New System.Drawing.Size(652, 22)
        Me.sspStatus.TabIndex = 3
        Me.sspStatus.Text = "StatusStrip"
        '
        'lblSSStatus
        '
        Me.lblSSStatus.Name = "lblSSStatus"
        Me.lblSSStatus.Size = New System.Drawing.Size(0, 17)
        '
        'TSC1
        '
        Me.TSC1.BottomToolStripPanelVisible = False
        '
        'TSC1.ContentPanel
        '
        Me.TSC1.ContentPanel.Size = New System.Drawing.Size(652, 1)
        Me.TSC1.Dock = System.Windows.Forms.DockStyle.Top
        Me.TSC1.LeftToolStripPanelVisible = False
        Me.TSC1.Location = New System.Drawing.Point(0, 0)
        Me.TSC1.Name = "TSC1"
        Me.TSC1.RightToolStripPanelVisible = False
        Me.TSC1.Size = New System.Drawing.Size(652, 26)
        Me.TSC1.TabIndex = 12
        Me.TSC1.Text = "TSC1"
        '
        'TSC1.TopToolStripPanel
        '
        Me.TSC1.TopToolStripPanel.Controls.Add(Me.TS1)
        '
        'TS1
        '
        Me.TS1.Dock = System.Windows.Forms.DockStyle.None
        Me.TS1.ImageScalingSize = New System.Drawing.Size(20, 20)
        Me.TS1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.TSBNew, Me.TSBExcel, Me.TSBSave, Me.TSBDelete})
        Me.TS1.Location = New System.Drawing.Point(3, 0)
        Me.TS1.Name = "TS1"
        Me.TS1.Size = New System.Drawing.Size(132, 25)
        Me.TS1.TabIndex = 0
        '
        'TSBNew
        '
        Me.TSBNew.AutoSize = False
        Me.TSBNew.Enabled = False
        Me.TSBNew.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBNew.Name = "TSBNew"
        Me.TSBNew.Size = New System.Drawing.Size(60, 22)
        Me.TSBNew.Text = "New"
        Me.TSBNew.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.TSBNew.Visible = False
        '
        'TSBExcel
        '
        Me.TSBExcel.AutoSize = False
        Me.TSBExcel.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBExcel.Name = "TSBExcel"
        Me.TSBExcel.Size = New System.Drawing.Size(60, 22)
        Me.TSBExcel.Text = "Excel"
        Me.TSBExcel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBSave
        '
        Me.TSBSave.AutoSize = False
        Me.TSBSave.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBSave.Name = "TSBSave"
        Me.TSBSave.Size = New System.Drawing.Size(60, 22)
        Me.TSBSave.Text = "Save"
        Me.TSBSave.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBDelete
        '
        Me.TSBDelete.AutoSize = False
        Me.TSBDelete.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBDelete.Name = "TSBDelete"
        Me.TSBDelete.Size = New System.Drawing.Size(60, 22)
        Me.TSBDelete.Text = "Delete"
        Me.TSBDelete.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.TSBDelete.Visible = False
        '
        'ErrEmp_Code
        '
        Me.ErrEmp_Code.ContainerControl = Me
        '
        'lblEmp_StartDateToPrevServ
        '
        Me.lblEmp_StartDateToPrevServ.AutoSize = True
        Me.lblEmp_StartDateToPrevServ.Location = New System.Drawing.Point(10, 128)
        Me.lblEmp_StartDateToPrevServ.Name = "lblEmp_StartDateToPrevServ"
        Me.lblEmp_StartDateToPrevServ.Size = New System.Drawing.Size(197, 13)
        Me.lblEmp_StartDateToPrevServ.TabIndex = 2
        Me.lblEmp_StartDateToPrevServ.Text = "Date of Employment to Previous Service"
        '
        'ErrEmp_StartDateToPrevServ
        '
        Me.ErrEmp_StartDateToPrevServ.ContainerControl = Me
        '
        'lblPosCat_Code
        '
        Me.lblPosCat_Code.AutoSize = True
        Me.lblPosCat_Code.Location = New System.Drawing.Point(10, 152)
        Me.lblPosCat_Code.Name = "lblPosCat_Code"
        Me.lblPosCat_Code.Size = New System.Drawing.Size(74, 13)
        Me.lblPosCat_Code.TabIndex = 3
        Me.lblPosCat_Code.Text = "Position Scale"
        '
        'ErrPosCat_Code
        '
        Me.ErrPosCat_Code.ContainerControl = Me
        '
        'lblPosRnk_Code
        '
        Me.lblPosRnk_Code.AutoSize = True
        Me.lblPosRnk_Code.Location = New System.Drawing.Point(10, 176)
        Me.lblPosRnk_Code.Name = "lblPosRnk_Code"
        Me.lblPosRnk_Code.Size = New System.Drawing.Size(71, 13)
        Me.lblPosRnk_Code.TabIndex = 4
        Me.lblPosRnk_Code.Text = "Current Scale"
        '
        'ErrPosRnk_Code
        '
        Me.ErrPosRnk_Code.ContainerControl = Me
        '
        'lblEmp_RetirementDate63
        '
        Me.lblEmp_RetirementDate63.AutoSize = True
        Me.lblEmp_RetirementDate63.Location = New System.Drawing.Point(10, 224)
        Me.lblEmp_RetirementDate63.Name = "lblEmp_RetirementDate63"
        Me.lblEmp_RetirementDate63.Size = New System.Drawing.Size(99, 13)
        Me.lblEmp_RetirementDate63.TabIndex = 5
        Me.lblEmp_RetirementDate63.Text = "Retirement Date 63"
        '
        'ErrEmp_RetirementDate63
        '
        Me.ErrEmp_RetirementDate63.ContainerControl = Me
        '
        'lblEmp_RetirementDate65
        '
        Me.lblEmp_RetirementDate65.AutoSize = True
        Me.lblEmp_RetirementDate65.Location = New System.Drawing.Point(10, 245)
        Me.lblEmp_RetirementDate65.Name = "lblEmp_RetirementDate65"
        Me.lblEmp_RetirementDate65.Size = New System.Drawing.Size(99, 13)
        Me.lblEmp_RetirementDate65.TabIndex = 6
        Me.lblEmp_RetirementDate65.Text = "Retirement Date 65"
        '
        'ErrEmp_RetirementDate65
        '
        Me.ErrEmp_RetirementDate65.ContainerControl = Me
        '
        'lblEmp_ComDate400Months
        '
        Me.lblEmp_ComDate400Months.AutoSize = True
        Me.lblEmp_ComDate400Months.Location = New System.Drawing.Point(10, 266)
        Me.lblEmp_ComDate400Months.Name = "lblEmp_ComDate400Months"
        Me.lblEmp_ComDate400Months.Size = New System.Drawing.Size(143, 13)
        Me.lblEmp_ComDate400Months.TabIndex = 7
        Me.lblEmp_ComDate400Months.Text = "400 Months completion Date"
        '
        'ErrEmp_ComDate400Months
        '
        Me.ErrEmp_ComDate400Months.ContainerControl = Me
        '
        'lblEmp_ExtraRatePerHour
        '
        Me.lblEmp_ExtraRatePerHour.AutoSize = True
        Me.lblEmp_ExtraRatePerHour.Location = New System.Drawing.Point(10, 286)
        Me.lblEmp_ExtraRatePerHour.Name = "lblEmp_ExtraRatePerHour"
        Me.lblEmp_ExtraRatePerHour.Size = New System.Drawing.Size(102, 13)
        Me.lblEmp_ExtraRatePerHour.TabIndex = 8
        Me.lblEmp_ExtraRatePerHour.Text = "Extra Rate Per Hour"
        '
        'txtEmp_ExtraRatePerHour
        '
        Me.txtEmp_ExtraRatePerHour.Location = New System.Drawing.Point(211, 284)
        Me.txtEmp_ExtraRatePerHour.MaxLength = 15
        Me.txtEmp_ExtraRatePerHour.Name = "txtEmp_ExtraRatePerHour"
        Me.txtEmp_ExtraRatePerHour.Size = New System.Drawing.Size(100, 20)
        Me.txtEmp_ExtraRatePerHour.TabIndex = 8
        '
        'ErrEmp_ExtraRatePerHour
        '
        Me.ErrEmp_ExtraRatePerHour.ContainerControl = Me
        '
        'lblEmp_DOfNextRateIncrease
        '
        Me.lblEmp_DOfNextRateIncrease.AutoSize = True
        Me.lblEmp_DOfNextRateIncrease.Location = New System.Drawing.Point(10, 309)
        Me.lblEmp_DOfNextRateIncrease.Name = "lblEmp_DOfNextRateIncrease"
        Me.lblEmp_DOfNextRateIncrease.Size = New System.Drawing.Size(137, 13)
        Me.lblEmp_DOfNextRateIncrease.TabIndex = 9
        Me.lblEmp_DOfNextRateIncrease.Text = "Date of Next Rate Increase"
        '
        'ErrEmp_DOfNextRateIncrease
        '
        Me.ErrEmp_DOfNextRateIncrease.ContainerControl = Me
        '
        'lblEmp_IsTop
        '
        Me.lblEmp_IsTop.AutoSize = True
        Me.lblEmp_IsTop.Location = New System.Drawing.Point(10, 328)
        Me.lblEmp_IsTop.Name = "lblEmp_IsTop"
        Me.lblEmp_IsTop.Size = New System.Drawing.Size(37, 13)
        Me.lblEmp_IsTop.TabIndex = 10
        Me.lblEmp_IsTop.Text = "Is Top"
        '
        'ErrEmp_IsTop
        '
        Me.ErrEmp_IsTop.ContainerControl = Me
        '
        'lblEmp_ProvidentFund
        '
        Me.lblEmp_ProvidentFund.AutoSize = True
        Me.lblEmp_ProvidentFund.Location = New System.Drawing.Point(8, 351)
        Me.lblEmp_ProvidentFund.Name = "lblEmp_ProvidentFund"
        Me.lblEmp_ProvidentFund.Size = New System.Drawing.Size(101, 13)
        Me.lblEmp_ProvidentFund.TabIndex = 11
        Me.lblEmp_ProvidentFund.Text = "Has Provident Fund"
        '
        'ErrEmp_ProvidentFund
        '
        Me.ErrEmp_ProvidentFund.ContainerControl = Me
        '
        'lblEmp_PensionFund
        '
        Me.lblEmp_PensionFund.AutoSize = True
        Me.lblEmp_PensionFund.Location = New System.Drawing.Point(10, 374)
        Me.lblEmp_PensionFund.Name = "lblEmp_PensionFund"
        Me.lblEmp_PensionFund.Size = New System.Drawing.Size(99, 13)
        Me.lblEmp_PensionFund.TabIndex = 12
        Me.lblEmp_PensionFund.Text = "Pension Fund Type"
        '
        'ErrEmp_PensionFund
        '
        Me.ErrEmp_PensionFund.ContainerControl = Me
        '
        'lblEmp_DOfStartPrFund
        '
        Me.lblEmp_DOfStartPrFund.AutoSize = True
        Me.lblEmp_DOfStartPrFund.Location = New System.Drawing.Point(10, 398)
        Me.lblEmp_DOfStartPrFund.Name = "lblEmp_DOfStartPrFund"
        Me.lblEmp_DOfStartPrFund.Size = New System.Drawing.Size(124, 13)
        Me.lblEmp_DOfStartPrFund.TabIndex = 13
        Me.lblEmp_DOfStartPrFund.Text = "Date Of Prov. Fund Start"
        '
        'ErrEmp_DOfStartPrFund
        '
        Me.ErrEmp_DOfStartPrFund.ContainerControl = Me
        '
        'lblEmp_10PercentDecrease
        '
        Me.lblEmp_10PercentDecrease.AutoSize = True
        Me.lblEmp_10PercentDecrease.Location = New System.Drawing.Point(10, 418)
        Me.lblEmp_10PercentDecrease.Name = "lblEmp_10PercentDecrease"
        Me.lblEmp_10PercentDecrease.Size = New System.Drawing.Size(108, 13)
        Me.lblEmp_10PercentDecrease.TabIndex = 14
        Me.lblEmp_10PercentDecrease.Text = "10 Percent Decrease"
        '
        'ErrEmp_10PercentDecrease
        '
        Me.ErrEmp_10PercentDecrease.ContainerControl = Me
        '
        'DateStartDateToPrevServ
        '
        Me.DateStartDateToPrevServ.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.DateStartDateToPrevServ.Location = New System.Drawing.Point(211, 128)
        Me.DateStartDateToPrevServ.Margin = New System.Windows.Forms.Padding(2)
        Me.DateStartDateToPrevServ.Name = "DateStartDateToPrevServ"
        Me.DateStartDateToPrevServ.Size = New System.Drawing.Size(84, 20)
        Me.DateStartDateToPrevServ.TabIndex = 15
        '
        'DateRetirementDate63
        '
        Me.DateRetirementDate63.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.DateRetirementDate63.Location = New System.Drawing.Point(211, 220)
        Me.DateRetirementDate63.Margin = New System.Windows.Forms.Padding(2)
        Me.DateRetirementDate63.Name = "DateRetirementDate63"
        Me.DateRetirementDate63.Size = New System.Drawing.Size(84, 20)
        Me.DateRetirementDate63.TabIndex = 16
        '
        'DateRetirementDate65
        '
        Me.DateRetirementDate65.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.DateRetirementDate65.Location = New System.Drawing.Point(211, 241)
        Me.DateRetirementDate65.Margin = New System.Windows.Forms.Padding(2)
        Me.DateRetirementDate65.Name = "DateRetirementDate65"
        Me.DateRetirementDate65.Size = New System.Drawing.Size(84, 20)
        Me.DateRetirementDate65.TabIndex = 17
        '
        'DateDOfNextRateIncrease
        '
        Me.DateDOfNextRateIncrease.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.DateDOfNextRateIncrease.Location = New System.Drawing.Point(211, 305)
        Me.DateDOfNextRateIncrease.Margin = New System.Windows.Forms.Padding(2)
        Me.DateDOfNextRateIncrease.Name = "DateDOfNextRateIncrease"
        Me.DateDOfNextRateIncrease.Size = New System.Drawing.Size(84, 20)
        Me.DateDOfNextRateIncrease.TabIndex = 18
        '
        'DateDOfStartPrFund
        '
        Me.DateDOfStartPrFund.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.DateDOfStartPrFund.Location = New System.Drawing.Point(211, 394)
        Me.DateDOfStartPrFund.Margin = New System.Windows.Forms.Padding(2)
        Me.DateDOfStartPrFund.Name = "DateDOfStartPrFund"
        Me.DateDOfStartPrFund.Size = New System.Drawing.Size(84, 20)
        Me.DateDOfStartPrFund.TabIndex = 19
        '
        'DateComDate400Months
        '
        Me.DateComDate400Months.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.DateComDate400Months.Location = New System.Drawing.Point(211, 262)
        Me.DateComDate400Months.Margin = New System.Windows.Forms.Padding(2)
        Me.DateComDate400Months.Name = "DateComDate400Months"
        Me.DateComDate400Months.Size = New System.Drawing.Size(84, 20)
        Me.DateComDate400Months.TabIndex = 20
        '
        'Label6
        '
        Me.Label6.AutoSize = True
        Me.Label6.Location = New System.Drawing.Point(10, 63)
        Me.Label6.Name = "Label6"
        Me.Label6.Size = New System.Drawing.Size(84, 13)
        Me.Label6.TabIndex = 88
        Me.Label6.Text = "Employee Name"
        '
        'txtEmployeeName
        '
        Me.txtEmployeeName.Location = New System.Drawing.Point(130, 64)
        Me.txtEmployeeName.MaxLength = 15
        Me.txtEmployeeName.Name = "txtEmployeeName"
        Me.txtEmployeeName.ReadOnly = True
        Me.txtEmployeeName.Size = New System.Drawing.Size(316, 20)
        Me.txtEmployeeName.TabIndex = 87
        '
        'Label5
        '
        Me.Label5.AutoSize = True
        Me.Label5.Location = New System.Drawing.Point(10, 37)
        Me.Label5.Name = "Label5"
        Me.Label5.Size = New System.Drawing.Size(81, 13)
        Me.Label5.TabIndex = 86
        Me.Label5.Text = "Employee Code"
        '
        'txtEmp_Code
        '
        Me.txtEmp_Code.Location = New System.Drawing.Point(130, 38)
        Me.txtEmp_Code.MaxLength = 15
        Me.txtEmp_Code.Name = "txtEmp_Code"
        Me.txtEmp_Code.ReadOnly = True
        Me.txtEmp_Code.Size = New System.Drawing.Size(100, 20)
        Me.txtEmp_Code.TabIndex = 85
        '
        'ComboIsTop
        '
        Me.ComboIsTop.AutoCompleteCustomSource.AddRange(New String() {"YES", "NO"})
        Me.ComboIsTop.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.ComboIsTop.FormattingEnabled = True
        Me.ComboIsTop.Items.AddRange(New Object() {"YES", "NO"})
        Me.ComboIsTop.Location = New System.Drawing.Point(211, 326)
        Me.ComboIsTop.Margin = New System.Windows.Forms.Padding(2)
        Me.ComboIsTop.Name = "ComboIsTop"
        Me.ComboIsTop.Size = New System.Drawing.Size(84, 21)
        Me.ComboIsTop.TabIndex = 89
        '
        'ComboProFund
        '
        Me.ComboProFund.AutoCompleteCustomSource.AddRange(New String() {"YES", "NO"})
        Me.ComboProFund.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.ComboProFund.FormattingEnabled = True
        Me.ComboProFund.Items.AddRange(New Object() {"YES", "NO"})
        Me.ComboProFund.Location = New System.Drawing.Point(211, 349)
        Me.ComboProFund.Margin = New System.Windows.Forms.Padding(2)
        Me.ComboProFund.Name = "ComboProFund"
        Me.ComboProFund.Size = New System.Drawing.Size(84, 21)
        Me.ComboProFund.TabIndex = 90
        '
        'ComboPenFund
        '
        Me.ComboPenFund.AutoCompleteCustomSource.AddRange(New String() {"OLD", "NEW", "NO"})
        Me.ComboPenFund.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.ComboPenFund.FormattingEnabled = True
        Me.ComboPenFund.Items.AddRange(New Object() {"NEW", "OLD", "NO"})
        Me.ComboPenFund.Location = New System.Drawing.Point(211, 371)
        Me.ComboPenFund.Margin = New System.Windows.Forms.Padding(2)
        Me.ComboPenFund.Name = "ComboPenFund"
        Me.ComboPenFund.Size = New System.Drawing.Size(84, 21)
        Me.ComboPenFund.TabIndex = 91
        '
        'Combo10Percent
        '
        Me.Combo10Percent.AutoCompleteCustomSource.AddRange(New String() {"YES", "NO"})
        Me.Combo10Percent.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.Combo10Percent.FormattingEnabled = True
        Me.Combo10Percent.Items.AddRange(New Object() {"YES", "NO"})
        Me.Combo10Percent.Location = New System.Drawing.Point(211, 415)
        Me.Combo10Percent.Margin = New System.Windows.Forms.Padding(2)
        Me.Combo10Percent.Name = "Combo10Percent"
        Me.Combo10Percent.Size = New System.Drawing.Size(84, 21)
        Me.Combo10Percent.TabIndex = 92
        '
        'ButtonRefScale1
        '
        Me.ButtonRefScale1.Location = New System.Drawing.Point(562, 146)
        Me.ButtonRefScale1.Name = "ButtonRefScale1"
        Me.ButtonRefScale1.Size = New System.Drawing.Size(24, 23)
        Me.ButtonRefScale1.TabIndex = 100
        Me.ButtonRefScale1.Text = "R"
        Me.ButtonRefScale1.UseVisualStyleBackColor = True
        Me.ButtonRefScale1.Visible = False
        '
        'ButtonAddScale1
        '
        Me.ButtonAddScale1.Location = New System.Drawing.Point(541, 146)
        Me.ButtonAddScale1.Name = "ButtonAddScale1"
        Me.ButtonAddScale1.Size = New System.Drawing.Size(24, 23)
        Me.ButtonAddScale1.TabIndex = 99
        Me.ButtonAddScale1.Text = "+"
        Me.ButtonAddScale1.UseVisualStyleBackColor = True
        Me.ButtonAddScale1.Visible = False
        '
        'ButtonRefScale2
        '
        Me.ButtonRefScale2.Location = New System.Drawing.Point(562, 171)
        Me.ButtonRefScale2.Name = "ButtonRefScale2"
        Me.ButtonRefScale2.Size = New System.Drawing.Size(24, 23)
        Me.ButtonRefScale2.TabIndex = 102
        Me.ButtonRefScale2.Text = "R"
        Me.ButtonRefScale2.UseVisualStyleBackColor = True
        Me.ButtonRefScale2.Visible = False
        '
        'ButtonAddScale2
        '
        Me.ButtonAddScale2.Location = New System.Drawing.Point(540, 171)
        Me.ButtonAddScale2.Name = "ButtonAddScale2"
        Me.ButtonAddScale2.Size = New System.Drawing.Size(24, 23)
        Me.ButtonAddScale2.TabIndex = 101
        Me.ButtonAddScale2.Text = "+"
        Me.ButtonAddScale2.UseVisualStyleBackColor = True
        Me.ButtonAddScale2.Visible = False
        '
        'ComboScale1
        '
        Me.ComboScale1.AutoCompleteCustomSource.AddRange(New String() {"YES", "NO"})
        Me.ComboScale1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.ComboScale1.FormattingEnabled = True
        Me.ComboScale1.Location = New System.Drawing.Point(211, 149)
        Me.ComboScale1.Margin = New System.Windows.Forms.Padding(2)
        Me.ComboScale1.Name = "ComboScale1"
        Me.ComboScale1.Size = New System.Drawing.Size(326, 21)
        Me.ComboScale1.TabIndex = 103
        '
        'ComboScale2
        '
        Me.ComboScale2.AutoCompleteCustomSource.AddRange(New String() {"YES", "NO"})
        Me.ComboScale2.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.ComboScale2.FormattingEnabled = True
        Me.ComboScale2.Location = New System.Drawing.Point(211, 171)
        Me.ComboScale2.Margin = New System.Windows.Forms.Padding(2)
        Me.ComboScale2.Name = "ComboScale2"
        Me.ComboScale2.Size = New System.Drawing.Size(326, 21)
        Me.ComboScale2.TabIndex = 104
        '
        'btnAutoCalc
        '
        Me.btnAutoCalc.Location = New System.Drawing.Point(465, 35)
        Me.btnAutoCalc.Margin = New System.Windows.Forms.Padding(2)
        Me.btnAutoCalc.Name = "btnAutoCalc"
        Me.btnAutoCalc.Size = New System.Drawing.Size(121, 53)
        Me.btnAutoCalc.TabIndex = 105
        Me.btnAutoCalc.Text = "Calculate Dates based on Employee Starting Date / Birth date"
        Me.btnAutoCalc.UseVisualStyleBackColor = True
        '
        'ComboScale3
        '
        Me.ComboScale3.AutoCompleteCustomSource.AddRange(New String() {"YES", "NO"})
        Me.ComboScale3.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.ComboScale3.FormattingEnabled = True
        Me.ComboScale3.Location = New System.Drawing.Point(211, 195)
        Me.ComboScale3.Margin = New System.Windows.Forms.Padding(2)
        Me.ComboScale3.Name = "ComboScale3"
        Me.ComboScale3.Size = New System.Drawing.Size(326, 21)
        Me.ComboScale3.TabIndex = 109
        '
        'ButtonRefScale3
        '
        Me.ButtonRefScale3.Location = New System.Drawing.Point(562, 195)
        Me.ButtonRefScale3.Name = "ButtonRefScale3"
        Me.ButtonRefScale3.Size = New System.Drawing.Size(24, 23)
        Me.ButtonRefScale3.TabIndex = 108
        Me.ButtonRefScale3.Text = "R"
        Me.ButtonRefScale3.UseVisualStyleBackColor = True
        Me.ButtonRefScale3.Visible = False
        '
        'ButtonAddScale3
        '
        Me.ButtonAddScale3.Location = New System.Drawing.Point(540, 195)
        Me.ButtonAddScale3.Name = "ButtonAddScale3"
        Me.ButtonAddScale3.Size = New System.Drawing.Size(24, 23)
        Me.ButtonAddScale3.TabIndex = 107
        Me.ButtonAddScale3.Text = "+"
        Me.ButtonAddScale3.UseVisualStyleBackColor = True
        Me.ButtonAddScale3.Visible = False
        '
        'Label1
        '
        Me.Label1.AutoSize = True
        Me.Label1.Location = New System.Drawing.Point(10, 200)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(70, 13)
        Me.Label1.TabIndex = 106
        Me.Label1.Text = "Current Rank"
        '
        'BtnNext
        '
        Me.BtnNext.Image = CType(resources.GetObject("BtnNext.Image"), System.Drawing.Image)
        Me.BtnNext.Location = New System.Drawing.Point(373, 35)
        Me.BtnNext.Name = "BtnNext"
        Me.BtnNext.Size = New System.Drawing.Size(75, 23)
        Me.BtnNext.TabIndex = 83
        Me.BtnNext.UseVisualStyleBackColor = True
        '
        'BtnPrevius
        '
        Me.BtnPrevius.Image = CType(resources.GetObject("BtnPrevius.Image"), System.Drawing.Image)
        Me.BtnPrevius.Location = New System.Drawing.Point(292, 35)
        Me.BtnPrevius.Name = "BtnPrevius"
        Me.BtnPrevius.Size = New System.Drawing.Size(75, 23)
        Me.BtnPrevius.TabIndex = 84
        Me.BtnPrevius.UseVisualStyleBackColor = True
        '
        'frmPrMsEmployeeExtraDetails
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.SystemColors.GradientActiveCaption
        Me.ClientSize = New System.Drawing.Size(652, 536)
        Me.Controls.Add(Me.ComboScale3)
        Me.Controls.Add(Me.ButtonRefScale3)
        Me.Controls.Add(Me.ButtonAddScale3)
        Me.Controls.Add(Me.Label1)
        Me.Controls.Add(Me.btnAutoCalc)
        Me.Controls.Add(Me.ComboScale2)
        Me.Controls.Add(Me.ComboScale1)
        Me.Controls.Add(Me.ButtonRefScale2)
        Me.Controls.Add(Me.ButtonAddScale2)
        Me.Controls.Add(Me.ButtonRefScale1)
        Me.Controls.Add(Me.ButtonAddScale1)
        Me.Controls.Add(Me.Combo10Percent)
        Me.Controls.Add(Me.ComboPenFund)
        Me.Controls.Add(Me.ComboProFund)
        Me.Controls.Add(Me.ComboIsTop)
        Me.Controls.Add(Me.Label6)
        Me.Controls.Add(Me.txtEmployeeName)
        Me.Controls.Add(Me.Label5)
        Me.Controls.Add(Me.txtEmp_Code)
        Me.Controls.Add(Me.BtnNext)
        Me.Controls.Add(Me.BtnPrevius)
        Me.Controls.Add(Me.DateComDate400Months)
        Me.Controls.Add(Me.DateDOfStartPrFund)
        Me.Controls.Add(Me.DateDOfNextRateIncrease)
        Me.Controls.Add(Me.DateRetirementDate65)
        Me.Controls.Add(Me.DateRetirementDate63)
        Me.Controls.Add(Me.DateStartDateToPrevServ)
        Me.Controls.Add(Me.lblEmp_StartDateToPrevServ)
        Me.Controls.Add(Me.lblPosCat_Code)
        Me.Controls.Add(Me.lblPosRnk_Code)
        Me.Controls.Add(Me.lblEmp_RetirementDate63)
        Me.Controls.Add(Me.lblEmp_RetirementDate65)
        Me.Controls.Add(Me.lblEmp_ComDate400Months)
        Me.Controls.Add(Me.lblEmp_ExtraRatePerHour)
        Me.Controls.Add(Me.txtEmp_ExtraRatePerHour)
        Me.Controls.Add(Me.lblEmp_DOfNextRateIncrease)
        Me.Controls.Add(Me.lblEmp_IsTop)
        Me.Controls.Add(Me.lblEmp_ProvidentFund)
        Me.Controls.Add(Me.lblEmp_PensionFund)
        Me.Controls.Add(Me.lblEmp_DOfStartPrFund)
        Me.Controls.Add(Me.lblEmp_10PercentDecrease)
        Me.Controls.Add(Me.TSC1)
        Me.Controls.Add(Me.sspStatus)
        Me.Name = "frmPrMsEmployeeExtraDetails"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "EmployeeExtraDetails"
        Me.sspStatus.ResumeLayout(False)
        Me.sspStatus.PerformLayout()
        Me.TSC1.TopToolStripPanel.ResumeLayout(False)
        Me.TSC1.TopToolStripPanel.PerformLayout()
        Me.TSC1.ResumeLayout(False)
        Me.TSC1.PerformLayout()
        Me.TS1.ResumeLayout(False)
        Me.TS1.PerformLayout()
        CType(Me.ErrEmp_Code, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEmp_StartDateToPrevServ, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrPosCat_Code, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrPosRnk_Code, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEmp_RetirementDate63, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEmp_RetirementDate65, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEmp_ComDate400Months, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEmp_ExtraRatePerHour, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEmp_DOfNextRateIncrease, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEmp_IsTop, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEmp_ProvidentFund, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEmp_PensionFund, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEmp_DOfStartPrFund, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEmp_10PercentDecrease, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
    Friend WithEvents ErrEmp_Code As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblEmp_StartDateToPrevServ As System.Windows.Forms.Label
    Friend WithEvents ErrEmp_StartDateToPrevServ As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblPosCat_Code As System.Windows.Forms.Label
    Friend WithEvents ErrPosCat_Code As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblPosRnk_Code As System.Windows.Forms.Label
    Friend WithEvents ErrPosRnk_Code As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblEmp_RetirementDate63 As System.Windows.Forms.Label
    Friend WithEvents ErrEmp_RetirementDate63 As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblEmp_RetirementDate65 As System.Windows.Forms.Label
    Friend WithEvents ErrEmp_RetirementDate65 As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblEmp_ComDate400Months As System.Windows.Forms.Label
    Friend WithEvents ErrEmp_ComDate400Months As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblEmp_ExtraRatePerHour As System.Windows.Forms.Label
    Friend WithEvents txtEmp_ExtraRatePerHour As System.Windows.Forms.TextBox
    Friend WithEvents ErrEmp_ExtraRatePerHour As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblEmp_DOfNextRateIncrease As System.Windows.Forms.Label
    Friend WithEvents ErrEmp_DOfNextRateIncrease As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblEmp_IsTop As System.Windows.Forms.Label
    Friend WithEvents ErrEmp_IsTop As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblEmp_ProvidentFund As System.Windows.Forms.Label
    Friend WithEvents ErrEmp_ProvidentFund As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblEmp_PensionFund As System.Windows.Forms.Label
    Friend WithEvents ErrEmp_PensionFund As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblEmp_DOfStartPrFund As System.Windows.Forms.Label
    Friend WithEvents ErrEmp_DOfStartPrFund As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblEmp_10PercentDecrease As System.Windows.Forms.Label
    Friend WithEvents ErrEmp_10PercentDecrease As System.Windows.Forms.ErrorProvider
    Friend WithEvents sspStatus As System.Windows.Forms.StatusStrip
    Friend WithEvents lblSSStatus As System.Windows.Forms.ToolStripStatusLabel
    Friend WithEvents TSC1 As System.Windows.Forms.ToolStripContainer
    Friend WithEvents TS1 As System.Windows.Forms.ToolStrip
    Friend WithEvents TSBNew As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBSave As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBDelete As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBExcel As System.Windows.Forms.ToolStripButton
    Friend WithEvents DateDOfStartPrFund As DateTimePicker
    Friend WithEvents DateDOfNextRateIncrease As DateTimePicker
    Friend WithEvents DateRetirementDate65 As DateTimePicker
    Friend WithEvents DateRetirementDate63 As DateTimePicker
    Friend WithEvents DateStartDateToPrevServ As DateTimePicker
    Friend WithEvents DateComDate400Months As DateTimePicker
    Friend WithEvents Label6 As Label
    Friend WithEvents txtEmployeeName As TextBox
    Friend WithEvents Label5 As Label
    Friend WithEvents txtEmp_Code As TextBox
    Friend WithEvents BtnNext As Button
    Friend WithEvents BtnPrevius As Button
    Friend WithEvents Combo10Percent As ComboBox
    Friend WithEvents ComboPenFund As ComboBox
    Friend WithEvents ComboProFund As ComboBox
    Friend WithEvents ComboIsTop As ComboBox
    Friend WithEvents ComboScale2 As ComboBox
    Friend WithEvents ComboScale1 As ComboBox
    Friend WithEvents ButtonRefScale2 As Button
    Friend WithEvents ButtonAddScale2 As Button
    Friend WithEvents ButtonRefScale1 As Button
    Friend WithEvents ButtonAddScale1 As Button
    Friend WithEvents btnAutoCalc As Button
    Friend WithEvents ComboScale3 As ComboBox
    Friend WithEvents ButtonRefScale3 As Button
    Friend WithEvents ButtonAddScale3 As Button
    Friend WithEvents Label1 As Label
End Class
