' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 12/12/2007 09:40:12
'
'
Public Class cAaSsInterfaceToNodalDbTier
    '
    Inherits cDataTier
    '
    Protected Function GetByPK(ByVal tId As Integer) As DataSet
        Dim Str As String
        Str = " SELECT" & _
                " Bat_Id," & _
                " Bat_FromID," & _
                " Bat_ToID," & _
                " Bat_CreationTimes," & _
                " Bat_CreationDate," & _
                " Bat_CreatedBy," & _
                " Bat_UpdateDate," & _
                " Bat_UpdatedBy" & _
            "  FROM AaSsInterfaceToNodal" & _
            "  WHERE Bat_Id = " & tId
        Return MyBase.GetData(Str)
    End Function
    Protected Function Save(ByRef _cAaSsInterfaceToNodal As cAaSsInterfaceToNodal) As Boolean
        Dim SpParams As New ArrayList
        Dim SpNames As New ArrayList
        Dim Flag As Boolean = False
        With _cAaSsInterfaceToNodal
            SpParams.Add(.Id)                                                '(0)
            SpNames.Add("Bat_Id")                                            '(0)
            SpParams.Add(.FromID)                                            '(1)
            SpNames.Add("Bat_FromID")                                        '(1)
            SpParams.Add(.ToID)                                              '(2)
            SpNames.Add("Bat_ToID")                                          '(2)
            SpParams.Add(.CreationTimes)                                     '(3)
            SpNames.Add("Bat_CreationTimes")                                 '(3)
            SpParams.Add(.CreationDate)                                      '(4)
            SpNames.Add("Bat_CreationDate")                                  '(4)
            SpParams.Add(.CreatedBy)                                         '(5)
            SpNames.Add("Bat_CreatedBy")                                     '(5)
            SpParams.Add(.UpdateDate)                                        '(6)
            SpNames.Add("Bat_UpdateDate")                                    '(6)
            SpParams.Add(.UpdatedBy)                                         '(7)
            SpNames.Add("Bat_UpdatedBy")                                     '(7)
        End With
        SpParams.Add(CInt(0))                                            '(8)
        SpNames.Add("NewId")                                            '(8)
        If Me.StoredProcedure("AaSsInterfaceToNodal_Save_Update", SpParams, SpNames, 8) Then
            If _cAaSsInterfaceToNodal.Id = 0 Then
                _cAaSsInterfaceToNodal.Id = DbNullToInt(SpParams(8))
            End If
            Return True
        Else
            Return False
        End If
    End Function
    Protected Function Delete(ByVal tId As Integer) As Boolean
        Dim Str As String
        Dim Flag As Boolean = True
        Dim Exx As New System.Exception
        Try
            BeginTransaction()
            Str = " DELETE FROM AaSsInterfaceToNodal" & _
               " WHERE Bat_Id = " & tId
            If MyBase.ExecuteNonQuery(Str) = -1 Then
                Throw Exx
            End If
            CommitTransaction()
        Catch ex As Exception
            Rollback()
            Utils.ShowException(ex)
            Flag = False
        End Try
        Return Flag
    End Function
    Protected Function CheckDeleteRecords(ByVal tCode As Integer) As DataSet
        Dim ds As DataSet
        '    Generation Note : 12/12/2007 09:40:12 :- No Foriegn Key Constraints where found
        ds = Nothing
        Return ds
    End Function
End Class

