' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 13/02/2008 09:42:51
'
'
Public Class cPrTxEmployeeHiringDbTier
'
Inherits cDataTier
'
Protected Function GetByPK(ByVal tId As Integer) as DataSet
Dim Str as String
Str = " SELECT" & _
        " EmpHir_id," & _
        " Emp_Code," & _
        " EmpHir_Date," & _
        " EmpHir_StartDate," & _
        " EmpHir_StartSalary," & _
        " EmpHir_PFStartDate," & _
        " Usr_Id" & _
    "  FROM PrTxEmployeeHiring" & _
    "  WHERE EmpHir_id = " & tId
Return MyBase.GetData(Str)
End Function
Protected Function Save(ByRef _cPrTxEmployeeHiring AS cPrTxEmployeeHiring) As Boolean
Dim SpParams As New ArrayList
Dim SpNames As New ArrayList
Dim Flag As Boolean = False
With _cPrTxEmployeeHiring
   SpParams.Add(.Id)                                                '(0)
   SpNames.Add("EmpHir_id")                                         '(0)
   SpParams.Add(.Code)                                              '(1)
   SpNames.Add("Emp_Code")                                          '(1)
   SpParams.Add(.HiringDate)                                        '(2)
   SpNames.Add("EmpHir_Date")                                       '(2)
   SpParams.Add(.StartDate)                                         '(3)
   SpNames.Add("EmpHir_StartDate")                                  '(3)
   SpParams.Add(.StartSalary)                                       '(4)
   SpNames.Add("EmpHir_StartSalary")                                '(4)
   SpParams.Add(.PFStartDate)                                       '(5)
   SpNames.Add("EmpHir_PFStartDate")                                '(5)
   SpParams.Add(.Usr_Id)                                            '(6)
   SpNames.Add("Usr_Id")                                            '(6)
End With
   SpNames.Add("NewId")                                             '(7)
   SpParams.Add(CInt(0))                                            '(7)
If Me.StoredProcedure("AG_PrTxEmployeeHiring_Save_Update",SpParams, SpNames,7) Then
   If _cPrTxEmployeeHiring.Id = 0 Then
        _cPrTxEmployeeHiring.Id = DbNullToInt(SpParams(7))
   End if
  Return True
Else
  Return False
End if
End Function
Protected Function Delete(ByVal tId As Integer) as Boolean
Dim Str as String
Dim Flag As Boolean = True
Dim Exx As New System.Exception
   Try
         BeginTransaction()
         Str = " DELETE FROM PrTxEmployeeHiring" & _
            " WHERE EmpHir_id = " & tId
         If MyBase.ExecuteNonQuery(Str) = -1 Then
                 Throw Exx
         End If
         CommitTransaction()
   Catch ex as Exception
            Rollback()
            Utils.ShowException(ex)
            Flag = False
   End Try
Return Flag
End Function
Protected Function CheckDeleteRecords(ByVal tCode As Integer) as DataSet
 Dim ds As DataSet
'    Generation Note : 13/02/2008 09:42:51 :- No Foriegn Key Constraints where found
     ds = nothing
     Return ds
End Function
End Class
