<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmPrSsParameters
Inherits System.Windows.Forms.Form
<System.Diagnostics.DebuggerNonUserCode()> _
Protected Overrides Sub Dispose(ByVal disposing As Boolean)
If Disposing AndAlso components IsNot Nothing Then
components.Dispose()
End If
MyBase.Dispose(Disposing)
End Sub
Private components As System.ComponentModel.IContainer
' AutoGenerated Form by Nodalsoft
<System.Diagnostics.DebuggerStepThrough()> _
Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmPrSsParameters))
        Me.sspStatus = New System.Windows.Forms.StatusStrip
        Me.lblSSStatus = New System.Windows.Forms.ToolStripStatusLabel
        Me.DG1 = New System.Windows.Forms.DataGridView
        Me.dgcPar_Id = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcPar_Section = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcPar_Item = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcPar_Value = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcPar_Description = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcPar_System = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcPar_Type = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.TSC1 = New System.Windows.Forms.ToolStripContainer
        Me.TS1 = New System.Windows.Forms.ToolStrip
        Me.TSBNew = New System.Windows.Forms.ToolStripButton
        Me.TSBSave = New System.Windows.Forms.ToolStripButton
        Me.TSBDelete = New System.Windows.Forms.ToolStripButton
        Me.TSBExcel = New System.Windows.Forms.ToolStripButton
        Me.lblId = New System.Windows.Forms.Label
        Me.txtId = New System.Windows.Forms.TextBox
        Me.ErrId = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblSection = New System.Windows.Forms.Label
        Me.txtSection = New System.Windows.Forms.TextBox
        Me.ErrSection = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblItem = New System.Windows.Forms.Label
        Me.txtItem = New System.Windows.Forms.TextBox
        Me.ErrItem = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblValue1 = New System.Windows.Forms.Label
        Me.txtValue1 = New System.Windows.Forms.TextBox
        Me.ErrValue1 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDescription = New System.Windows.Forms.Label
        Me.txtDescription = New System.Windows.Forms.TextBox
        Me.ErrDescription = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblSystem1 = New System.Windows.Forms.Label
        Me.txtSystem1 = New System.Windows.Forms.TextBox
        Me.ErrSystem1 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblType1 = New System.Windows.Forms.Label
        Me.txtType1 = New System.Windows.Forms.TextBox
        Me.ErrType1 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.CBSortBy = New System.Windows.Forms.CheckBox
        Me.sspStatus.SuspendLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.TSC1.TopToolStripPanel.SuspendLayout()
        Me.TSC1.SuspendLayout()
        Me.TS1.SuspendLayout()
        CType(Me.ErrId, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrSection, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrItem, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrValue1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDescription, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrSystem1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrType1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'sspStatus
        '
        Me.sspStatus.BackColor = System.Drawing.SystemColors.Control
        Me.sspStatus.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.lblSSStatus})
        Me.sspStatus.Location = New System.Drawing.Point(0, 529)
        Me.sspStatus.Name = "sspStatus"
        Me.sspStatus.Size = New System.Drawing.Size(987, 22)
        Me.sspStatus.TabIndex = 3
        Me.sspStatus.Text = "StatusStrip"
        '
        'lblSSStatus
        '
        Me.lblSSStatus.Name = "lblSSStatus"
        Me.lblSSStatus.Size = New System.Drawing.Size(0, 17)
        '
        'DG1
        '
        Me.DG1.AllowUserToAddRows = False
        Me.DG1.AllowUserToDeleteRows = False
        Me.DG1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DG1.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.dgcPar_Id, Me.dgcPar_Section, Me.dgcPar_Item, Me.dgcPar_Value, Me.dgcPar_Description, Me.dgcPar_System, Me.dgcPar_Type})
        Me.DG1.Location = New System.Drawing.Point(12, 195)
        Me.DG1.Name = "DG1"
        Me.DG1.ReadOnly = True
        Me.DG1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
        Me.DG1.Size = New System.Drawing.Size(963, 320)
        Me.DG1.TabIndex = 10
        '
        'dgcPar_Id
        '
        Me.dgcPar_Id.DataPropertyName = "Par_Id"
        Me.dgcPar_Id.FillWeight = 150.0!
        Me.dgcPar_Id.HeaderText = "Id"
        Me.dgcPar_Id.Name = "dgcPar_Id"
        Me.dgcPar_Id.ReadOnly = True
        Me.dgcPar_Id.Width = 64
        '
        'dgcPar_Section
        '
        Me.dgcPar_Section.DataPropertyName = "Par_Section"
        Me.dgcPar_Section.FillWeight = 150.0!
        Me.dgcPar_Section.HeaderText = "Section"
        Me.dgcPar_Section.Name = "dgcPar_Section"
        Me.dgcPar_Section.ReadOnly = True
        Me.dgcPar_Section.Width = 190
        '
        'dgcPar_Item
        '
        Me.dgcPar_Item.DataPropertyName = "Par_Item"
        Me.dgcPar_Item.FillWeight = 150.0!
        Me.dgcPar_Item.HeaderText = "Item"
        Me.dgcPar_Item.Name = "dgcPar_Item"
        Me.dgcPar_Item.ReadOnly = True
        Me.dgcPar_Item.Width = 190
        '
        'dgcPar_Value
        '
        Me.dgcPar_Value.DataPropertyName = "Par_Value"
        Me.dgcPar_Value.FillWeight = 150.0!
        Me.dgcPar_Value.HeaderText = "Value"
        Me.dgcPar_Value.Name = "dgcPar_Value"
        Me.dgcPar_Value.ReadOnly = True
        Me.dgcPar_Value.Width = 610
        '
        'dgcPar_Description
        '
        Me.dgcPar_Description.DataPropertyName = "Par_Description"
        Me.dgcPar_Description.FillWeight = 150.0!
        Me.dgcPar_Description.HeaderText = "Description"
        Me.dgcPar_Description.Name = "dgcPar_Description"
        Me.dgcPar_Description.ReadOnly = True
        Me.dgcPar_Description.Width = 1510
        '
        'dgcPar_System
        '
        Me.dgcPar_System.DataPropertyName = "Par_System"
        Me.dgcPar_System.FillWeight = 150.0!
        Me.dgcPar_System.HeaderText = "System"
        Me.dgcPar_System.Name = "dgcPar_System"
        Me.dgcPar_System.ReadOnly = True
        Me.dgcPar_System.Width = 60
        '
        'dgcPar_Type
        '
        Me.dgcPar_Type.DataPropertyName = "Par_Type"
        Me.dgcPar_Type.FillWeight = 150.0!
        Me.dgcPar_Type.HeaderText = "Type"
        Me.dgcPar_Type.Name = "dgcPar_Type"
        Me.dgcPar_Type.ReadOnly = True
        Me.dgcPar_Type.Width = 60
        '
        'TSC1
        '
        Me.TSC1.BottomToolStripPanelVisible = False
        '
        'TSC1.ContentPanel
        '
        Me.TSC1.ContentPanel.Size = New System.Drawing.Size(987, 1)
        Me.TSC1.Dock = System.Windows.Forms.DockStyle.Top
        Me.TSC1.LeftToolStripPanelVisible = False
        Me.TSC1.Location = New System.Drawing.Point(0, 0)
        Me.TSC1.Name = "TSC1"
        Me.TSC1.RightToolStripPanelVisible = False
        Me.TSC1.Size = New System.Drawing.Size(987, 26)
        Me.TSC1.TabIndex = 12
        Me.TSC1.Text = "TSC1"
        '
        'TSC1.TopToolStripPanel
        '
        Me.TSC1.TopToolStripPanel.Controls.Add(Me.TS1)
        '
        'TS1
        '
        Me.TS1.Dock = System.Windows.Forms.DockStyle.None
        Me.TS1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.TSBNew, Me.TSBSave, Me.TSBDelete, Me.TSBExcel})
        Me.TS1.Location = New System.Drawing.Point(3, 0)
        Me.TS1.Name = "TS1"
        Me.TS1.Size = New System.Drawing.Size(252, 25)
        Me.TS1.TabIndex = 0
        '
        'TSBNew
        '
        Me.TSBNew.AutoSize = False
        Me.TSBNew.Image = CType(resources.GetObject("TSBNew.Image"), System.Drawing.Image)
        Me.TSBNew.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBNew.Name = "TSBNew"
        Me.TSBNew.Size = New System.Drawing.Size(60, 22)
        Me.TSBNew.Text = "New"
        Me.TSBNew.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBSave
        '
        Me.TSBSave.AutoSize = False
        Me.TSBSave.Image = CType(resources.GetObject("TSBSave.Image"), System.Drawing.Image)
        Me.TSBSave.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBSave.Name = "TSBSave"
        Me.TSBSave.Size = New System.Drawing.Size(60, 22)
        Me.TSBSave.Text = "Save"
        Me.TSBSave.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBDelete
        '
        Me.TSBDelete.AutoSize = False
        Me.TSBDelete.Enabled = False
        Me.TSBDelete.Image = CType(resources.GetObject("TSBDelete.Image"), System.Drawing.Image)
        Me.TSBDelete.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBDelete.Name = "TSBDelete"
        Me.TSBDelete.Size = New System.Drawing.Size(60, 22)
        Me.TSBDelete.Text = "Delete"
        Me.TSBDelete.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBExcel
        '
        Me.TSBExcel.AutoSize = False
        Me.TSBExcel.Image = Global.NodalPay.My.Resources.Resources.excel
        Me.TSBExcel.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBExcel.Name = "TSBExcel"
        Me.TSBExcel.Size = New System.Drawing.Size(60, 22)
        Me.TSBExcel.Text = "Excel"
        Me.TSBExcel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'lblId
        '
        Me.lblId.AutoSize = True
        Me.lblId.Location = New System.Drawing.Point(37, 40)
        Me.lblId.Name = "lblId"
        Me.lblId.Size = New System.Drawing.Size(16, 13)
        Me.lblId.TabIndex = 0
        Me.lblId.Text = "Id"
        '
        'txtId
        '
        Me.txtId.Location = New System.Drawing.Point(157, 40)
        Me.txtId.MaxLength = 9
        Me.txtId.Name = "txtId"
        Me.txtId.Size = New System.Drawing.Size(64, 20)
        Me.txtId.TabIndex = 1
        '
        'ErrId
        '
        Me.ErrId.ContainerControl = Me
        '
        'lblSection
        '
        Me.lblSection.AutoSize = True
        Me.lblSection.Location = New System.Drawing.Point(37, 60)
        Me.lblSection.Name = "lblSection"
        Me.lblSection.Size = New System.Drawing.Size(43, 13)
        Me.lblSection.TabIndex = 2
        Me.lblSection.Text = "Section"
        '
        'txtSection
        '
        Me.txtSection.Location = New System.Drawing.Point(157, 60)
        Me.txtSection.MaxLength = 30
        Me.txtSection.Name = "txtSection"
        Me.txtSection.Size = New System.Drawing.Size(190, 20)
        Me.txtSection.TabIndex = 2
        '
        'ErrSection
        '
        Me.ErrSection.ContainerControl = Me
        '
        'lblItem
        '
        Me.lblItem.AutoSize = True
        Me.lblItem.Location = New System.Drawing.Point(37, 80)
        Me.lblItem.Name = "lblItem"
        Me.lblItem.Size = New System.Drawing.Size(27, 13)
        Me.lblItem.TabIndex = 3
        Me.lblItem.Text = "Item"
        '
        'txtItem
        '
        Me.txtItem.Location = New System.Drawing.Point(157, 80)
        Me.txtItem.MaxLength = 30
        Me.txtItem.Name = "txtItem"
        Me.txtItem.Size = New System.Drawing.Size(190, 20)
        Me.txtItem.TabIndex = 3
        '
        'ErrItem
        '
        Me.ErrItem.ContainerControl = Me
        '
        'lblValue1
        '
        Me.lblValue1.AutoSize = True
        Me.lblValue1.Location = New System.Drawing.Point(37, 100)
        Me.lblValue1.Name = "lblValue1"
        Me.lblValue1.Size = New System.Drawing.Size(34, 13)
        Me.lblValue1.TabIndex = 4
        Me.lblValue1.Text = "Value"
        '
        'txtValue1
        '
        Me.txtValue1.Location = New System.Drawing.Point(157, 100)
        Me.txtValue1.MaxLength = 100
        Me.txtValue1.Name = "txtValue1"
        Me.txtValue1.Size = New System.Drawing.Size(610, 20)
        Me.txtValue1.TabIndex = 4
        '
        'ErrValue1
        '
        Me.ErrValue1.ContainerControl = Me
        '
        'lblDescription
        '
        Me.lblDescription.AutoSize = True
        Me.lblDescription.Location = New System.Drawing.Point(37, 120)
        Me.lblDescription.Name = "lblDescription"
        Me.lblDescription.Size = New System.Drawing.Size(60, 13)
        Me.lblDescription.TabIndex = 5
        Me.lblDescription.Text = "Description"
        '
        'txtDescription
        '
        Me.txtDescription.Location = New System.Drawing.Point(157, 120)
        Me.txtDescription.MaxLength = 250
        Me.txtDescription.Name = "txtDescription"
        Me.txtDescription.Size = New System.Drawing.Size(800, 20)
        Me.txtDescription.TabIndex = 5
        '
        'ErrDescription
        '
        Me.ErrDescription.ContainerControl = Me
        '
        'lblSystem1
        '
        Me.lblSystem1.AutoSize = True
        Me.lblSystem1.Location = New System.Drawing.Point(37, 140)
        Me.lblSystem1.Name = "lblSystem1"
        Me.lblSystem1.Size = New System.Drawing.Size(41, 13)
        Me.lblSystem1.TabIndex = 6
        Me.lblSystem1.Text = "System"
        '
        'txtSystem1
        '
        Me.txtSystem1.Location = New System.Drawing.Point(157, 140)
        Me.txtSystem1.MaxLength = 1
        Me.txtSystem1.Name = "txtSystem1"
        Me.txtSystem1.Size = New System.Drawing.Size(16, 20)
        Me.txtSystem1.TabIndex = 6
        '
        'ErrSystem1
        '
        Me.ErrSystem1.ContainerControl = Me
        '
        'lblType1
        '
        Me.lblType1.AutoSize = True
        Me.lblType1.Location = New System.Drawing.Point(37, 160)
        Me.lblType1.Name = "lblType1"
        Me.lblType1.Size = New System.Drawing.Size(31, 13)
        Me.lblType1.TabIndex = 7
        Me.lblType1.Text = "Type"
        '
        'txtType1
        '
        Me.txtType1.Location = New System.Drawing.Point(157, 160)
        Me.txtType1.MaxLength = 1
        Me.txtType1.Name = "txtType1"
        Me.txtType1.Size = New System.Drawing.Size(16, 20)
        Me.txtType1.TabIndex = 7
        '
        'ErrType1
        '
        Me.ErrType1.ContainerControl = Me
        '
        'CBSortBy
        '
        Me.CBSortBy.AutoSize = True
        Me.CBSortBy.Location = New System.Drawing.Point(556, 163)
        Me.CBSortBy.Name = "CBSortBy"
        Me.CBSortBy.Size = New System.Drawing.Size(99, 17)
        Me.CBSortBy.TabIndex = 13
        Me.CBSortBy.Text = "Sort By Section"
        Me.CBSortBy.UseVisualStyleBackColor = True
        '
        'frmPrSsParameters
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.SystemColors.GradientActiveCaption
        Me.ClientSize = New System.Drawing.Size(987, 551)
        Me.Controls.Add(Me.CBSortBy)
        Me.Controls.Add(Me.lblId)
        Me.Controls.Add(Me.txtId)
        Me.Controls.Add(Me.lblSection)
        Me.Controls.Add(Me.txtSection)
        Me.Controls.Add(Me.lblItem)
        Me.Controls.Add(Me.txtItem)
        Me.Controls.Add(Me.lblValue1)
        Me.Controls.Add(Me.txtValue1)
        Me.Controls.Add(Me.lblDescription)
        Me.Controls.Add(Me.txtDescription)
        Me.Controls.Add(Me.lblSystem1)
        Me.Controls.Add(Me.txtSystem1)
        Me.Controls.Add(Me.lblType1)
        Me.Controls.Add(Me.txtType1)
        Me.Controls.Add(Me.TSC1)
        Me.Controls.Add(Me.sspStatus)
        Me.Controls.Add(Me.DG1)
        Me.Name = "frmPrSsParameters"
        Me.Text = "Parameters"
        Me.sspStatus.ResumeLayout(False)
        Me.sspStatus.PerformLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.TSC1.TopToolStripPanel.ResumeLayout(False)
        Me.TSC1.TopToolStripPanel.PerformLayout()
        Me.TSC1.ResumeLayout(False)
        Me.TSC1.PerformLayout()
        Me.TS1.ResumeLayout(False)
        Me.TS1.PerformLayout()
        CType(Me.ErrId, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrSection, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrItem, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrValue1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDescription, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrSystem1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrType1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
Friend WithEvents  lblId As System.Windows.Forms.Label
Friend WithEvents  txtId As System.Windows.Forms.TextBox
Friend WithEvents ErrId As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcPar_Id As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblSection As System.Windows.Forms.Label
Friend WithEvents  txtSection As System.Windows.Forms.TextBox
Friend WithEvents ErrSection As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcPar_Section As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblItem As System.Windows.Forms.Label
Friend WithEvents  txtItem As System.Windows.Forms.TextBox
Friend WithEvents ErrItem As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcPar_Item As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblValue1 As System.Windows.Forms.Label
Friend WithEvents  txtValue1 As System.Windows.Forms.TextBox
Friend WithEvents ErrValue1 As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcPar_Value As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblDescription As System.Windows.Forms.Label
Friend WithEvents  txtDescription As System.Windows.Forms.TextBox
Friend WithEvents ErrDescription As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcPar_Description As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblSystem1 As System.Windows.Forms.Label
Friend WithEvents  txtSystem1 As System.Windows.Forms.TextBox
Friend WithEvents ErrSystem1 As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcPar_System As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblType1 As System.Windows.Forms.Label
Friend WithEvents  txtType1 As System.Windows.Forms.TextBox
Friend WithEvents ErrType1 As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcPar_Type As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents sspStatus As System.Windows.Forms.StatusStrip
Friend WithEvents lblSSStatus As System.Windows.Forms.ToolStripStatusLabel
Friend WithEvents DG1 As System.Windows.Forms.DataGridView
Friend WithEvents TSC1 As System.Windows.Forms.ToolStripContainer
Friend WithEvents TS1 As System.Windows.Forms.ToolStrip
Friend WithEvents TSBNew As System.Windows.Forms.ToolStripButton
Friend WithEvents TSBSave As System.Windows.Forms.ToolStripButton
Friend WithEvents TSBDelete As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBExcel As System.Windows.Forms.ToolStripButton
    Friend WithEvents CBSortBy As System.Windows.Forms.CheckBox
End Class
