<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmPrSsSocialInsurance
Inherits System.Windows.Forms.Form
<System.Diagnostics.DebuggerNonUserCode()> _
Protected Overrides Sub Dispose(ByVal disposing As Boolean)
If Disposing AndAlso components IsNot Nothing Then
components.Dispose()
End If
MyBase.Dispose(Disposing)
End Sub
Private components As System.ComponentModel.IContainer
' AutoGenerated Form by Nodalsoft
<System.Diagnostics.DebuggerStepThrough()> _
Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmPrSsSocialInsurance))
        Me.sspStatus = New System.Windows.Forms.StatusStrip
        Me.lblSSStatus = New System.Windows.Forms.ToolStripStatusLabel
        Me.DG1 = New System.Windows.Forms.DataGridView
        Me.dgcSocInc_Code = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcSocInc_Desc = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcSocInc_DedValue = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcSocIns_ConValue = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.TSC1 = New System.Windows.Forms.ToolStripContainer
        Me.TS1 = New System.Windows.Forms.ToolStrip
        Me.TSBNew = New System.Windows.Forms.ToolStripButton
        Me.TSBSave = New System.Windows.Forms.ToolStripButton
        Me.TSBDelete = New System.Windows.Forms.ToolStripButton
        Me.TSBExcel = New System.Windows.Forms.ToolStripButton
        Me.lblCode = New System.Windows.Forms.Label
        Me.txtCode = New System.Windows.Forms.TextBox
        Me.ErrCode = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDesc = New System.Windows.Forms.Label
        Me.txtDesc = New System.Windows.Forms.TextBox
        Me.ErrDesc = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDedValue = New System.Windows.Forms.Label
        Me.txtDedValue = New System.Windows.Forms.TextBox
        Me.ErrDedValue = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblConValue = New System.Windows.Forms.Label
        Me.txtConValue = New System.Windows.Forms.TextBox
        Me.ErrConValue = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.sspStatus.SuspendLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.TSC1.TopToolStripPanel.SuspendLayout()
        Me.TSC1.SuspendLayout()
        Me.TS1.SuspendLayout()
        CType(Me.ErrCode, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDesc, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDedValue, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrConValue, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'sspStatus
        '
        Me.sspStatus.BackColor = System.Drawing.SystemColors.Control
        Me.sspStatus.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.lblSSStatus})
        Me.sspStatus.Location = New System.Drawing.Point(0, 529)
        Me.sspStatus.Name = "sspStatus"
        Me.sspStatus.Size = New System.Drawing.Size(987, 22)
        Me.sspStatus.TabIndex = 3
        Me.sspStatus.Text = "StatusStrip"
        '
        'lblSSStatus
        '
        Me.lblSSStatus.Name = "lblSSStatus"
        Me.lblSSStatus.Size = New System.Drawing.Size(0, 17)
        '
        'DG1
        '
        Me.DG1.AllowUserToAddRows = False
        Me.DG1.AllowUserToDeleteRows = False
        Me.DG1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DG1.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.dgcSocInc_Code, Me.dgcSocInc_Desc, Me.dgcSocInc_DedValue, Me.dgcSocIns_ConValue})
        Me.DG1.Location = New System.Drawing.Point(12, 125)
        Me.DG1.Name = "DG1"
        Me.DG1.ReadOnly = True
        Me.DG1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
        Me.DG1.Size = New System.Drawing.Size(963, 387)
        Me.DG1.TabIndex = 10
        '
        'dgcSocInc_Code
        '
        Me.dgcSocInc_Code.DataPropertyName = "SocInc_Code"
        Me.dgcSocInc_Code.FillWeight = 150.0!
        Me.dgcSocInc_Code.HeaderText = "Code"
        Me.dgcSocInc_Code.Name = "dgcSocInc_Code"
        Me.dgcSocInc_Code.ReadOnly = True
        Me.dgcSocInc_Code.Width = 60
        '
        'dgcSocInc_Desc
        '
        Me.dgcSocInc_Desc.DataPropertyName = "SocInc_Desc"
        Me.dgcSocInc_Desc.FillWeight = 150.0!
        Me.dgcSocInc_Desc.HeaderText = "Description"
        Me.dgcSocInc_Desc.Name = "dgcSocInc_Desc"
        Me.dgcSocInc_Desc.ReadOnly = True
        Me.dgcSocInc_Desc.Width = 250
        '
        'dgcSocInc_DedValue
        '
        Me.dgcSocInc_DedValue.DataPropertyName = "SocInc_DedValue"
        Me.dgcSocInc_DedValue.FillWeight = 150.0!
        Me.dgcSocInc_DedValue.HeaderText = "Deduction Value"
        Me.dgcSocInc_DedValue.Name = "dgcSocInc_DedValue"
        Me.dgcSocInc_DedValue.ReadOnly = True
        '
        'dgcSocIns_ConValue
        '
        Me.dgcSocIns_ConValue.DataPropertyName = "SocIns_ConValue"
        Me.dgcSocIns_ConValue.FillWeight = 150.0!
        Me.dgcSocIns_ConValue.HeaderText = "Contribution Value"
        Me.dgcSocIns_ConValue.Name = "dgcSocIns_ConValue"
        Me.dgcSocIns_ConValue.ReadOnly = True
        '
        'TSC1
        '
        Me.TSC1.BottomToolStripPanelVisible = False
        '
        'TSC1.ContentPanel
        '
        Me.TSC1.ContentPanel.Size = New System.Drawing.Size(987, 1)
        Me.TSC1.Dock = System.Windows.Forms.DockStyle.Top
        Me.TSC1.LeftToolStripPanelVisible = False
        Me.TSC1.Location = New System.Drawing.Point(0, 0)
        Me.TSC1.Name = "TSC1"
        Me.TSC1.RightToolStripPanelVisible = False
        Me.TSC1.Size = New System.Drawing.Size(987, 26)
        Me.TSC1.TabIndex = 12
        Me.TSC1.Text = "TSC1"
        '
        'TSC1.TopToolStripPanel
        '
        Me.TSC1.TopToolStripPanel.Controls.Add(Me.TS1)
        '
        'TS1
        '
        Me.TS1.Dock = System.Windows.Forms.DockStyle.None
        Me.TS1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.TSBNew, Me.TSBSave, Me.TSBDelete, Me.TSBExcel})
        Me.TS1.Location = New System.Drawing.Point(3, 0)
        Me.TS1.Name = "TS1"
        Me.TS1.Size = New System.Drawing.Size(252, 25)
        Me.TS1.TabIndex = 0
        '
        'TSBNew
        '
        Me.TSBNew.AutoSize = False
        Me.TSBNew.Image = CType(resources.GetObject("TSBNew.Image"), System.Drawing.Image)
        Me.TSBNew.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBNew.Name = "TSBNew"
        Me.TSBNew.Size = New System.Drawing.Size(60, 22)
        Me.TSBNew.Text = "New"
        Me.TSBNew.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBSave
        '
        Me.TSBSave.AutoSize = False
        Me.TSBSave.Image = CType(resources.GetObject("TSBSave.Image"), System.Drawing.Image)
        Me.TSBSave.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBSave.Name = "TSBSave"
        Me.TSBSave.Size = New System.Drawing.Size(60, 22)
        Me.TSBSave.Text = "Save"
        Me.TSBSave.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBDelete
        '
        Me.TSBDelete.AutoSize = False
        Me.TSBDelete.Enabled = False
        Me.TSBDelete.Image = CType(resources.GetObject("TSBDelete.Image"), System.Drawing.Image)
        Me.TSBDelete.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBDelete.Name = "TSBDelete"
        Me.TSBDelete.Size = New System.Drawing.Size(60, 22)
        Me.TSBDelete.Text = "Delete"
        Me.TSBDelete.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBExcel
        '
        Me.TSBExcel.AutoSize = False
        Me.TSBExcel.Image = Global.NodalPay.My.Resources.Resources.excel
        Me.TSBExcel.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBExcel.Name = "TSBExcel"
        Me.TSBExcel.Size = New System.Drawing.Size(60, 22)
        Me.TSBExcel.Text = "Excel"
        Me.TSBExcel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'lblCode
        '
        Me.lblCode.AutoSize = True
        Me.lblCode.Location = New System.Drawing.Point(37, 40)
        Me.lblCode.Name = "lblCode"
        Me.lblCode.Size = New System.Drawing.Size(32, 13)
        Me.lblCode.TabIndex = 0
        Me.lblCode.Text = "Code"
        '
        'txtCode
        '
        Me.txtCode.Location = New System.Drawing.Point(157, 40)
        Me.txtCode.MaxLength = 4
        Me.txtCode.Name = "txtCode"
        Me.txtCode.Size = New System.Drawing.Size(34, 20)
        Me.txtCode.TabIndex = 1
        '
        'ErrCode
        '
        Me.ErrCode.ContainerControl = Me
        '
        'lblDesc
        '
        Me.lblDesc.AutoSize = True
        Me.lblDesc.Location = New System.Drawing.Point(37, 60)
        Me.lblDesc.Name = "lblDesc"
        Me.lblDesc.Size = New System.Drawing.Size(60, 13)
        Me.lblDesc.TabIndex = 2
        Me.lblDesc.Text = "Description"
        '
        'txtDesc
        '
        Me.txtDesc.Location = New System.Drawing.Point(157, 60)
        Me.txtDesc.MaxLength = 40
        Me.txtDesc.Name = "txtDesc"
        Me.txtDesc.Size = New System.Drawing.Size(250, 20)
        Me.txtDesc.TabIndex = 2
        '
        'ErrDesc
        '
        Me.ErrDesc.ContainerControl = Me
        '
        'lblDedValue
        '
        Me.lblDedValue.AutoSize = True
        Me.lblDedValue.Location = New System.Drawing.Point(37, 80)
        Me.lblDedValue.Name = "lblDedValue"
        Me.lblDedValue.Size = New System.Drawing.Size(86, 13)
        Me.lblDedValue.TabIndex = 3
        Me.lblDedValue.Text = "Deduction Value"
        '
        'txtDedValue
        '
        Me.txtDedValue.Location = New System.Drawing.Point(157, 80)
        Me.txtDedValue.MaxLength = 15
        Me.txtDedValue.Name = "txtDedValue"
        Me.txtDedValue.Size = New System.Drawing.Size(100, 20)
        Me.txtDedValue.TabIndex = 3
        '
        'ErrDedValue
        '
        Me.ErrDedValue.ContainerControl = Me
        '
        'lblConValue
        '
        Me.lblConValue.AutoSize = True
        Me.lblConValue.Location = New System.Drawing.Point(37, 100)
        Me.lblConValue.Name = "lblConValue"
        Me.lblConValue.Size = New System.Drawing.Size(93, 13)
        Me.lblConValue.TabIndex = 4
        Me.lblConValue.Text = "Contribution Value"
        '
        'txtConValue
        '
        Me.txtConValue.Location = New System.Drawing.Point(157, 100)
        Me.txtConValue.MaxLength = 15
        Me.txtConValue.Name = "txtConValue"
        Me.txtConValue.Size = New System.Drawing.Size(100, 20)
        Me.txtConValue.TabIndex = 4
        '
        'ErrConValue
        '
        Me.ErrConValue.ContainerControl = Me
        '
        'frmPrSsSocialInsurance
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.SystemColors.GradientActiveCaption
        Me.ClientSize = New System.Drawing.Size(987, 551)
        Me.Controls.Add(Me.lblCode)
        Me.Controls.Add(Me.txtCode)
        Me.Controls.Add(Me.lblDesc)
        Me.Controls.Add(Me.txtDesc)
        Me.Controls.Add(Me.lblDedValue)
        Me.Controls.Add(Me.txtDedValue)
        Me.Controls.Add(Me.lblConValue)
        Me.Controls.Add(Me.txtConValue)
        Me.Controls.Add(Me.TSC1)
        Me.Controls.Add(Me.sspStatus)
        Me.Controls.Add(Me.DG1)
        Me.Name = "frmPrSsSocialInsurance"
        Me.Text = "Social Insurance"
        Me.sspStatus.ResumeLayout(False)
        Me.sspStatus.PerformLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.TSC1.TopToolStripPanel.ResumeLayout(False)
        Me.TSC1.TopToolStripPanel.PerformLayout()
        Me.TSC1.ResumeLayout(False)
        Me.TSC1.PerformLayout()
        Me.TS1.ResumeLayout(False)
        Me.TS1.PerformLayout()
        CType(Me.ErrCode, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDesc, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDedValue, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrConValue, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
Friend WithEvents  lblCode As System.Windows.Forms.Label
Friend WithEvents  txtCode As System.Windows.Forms.TextBox
Friend WithEvents ErrCode As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcSocInc_Code As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblDesc As System.Windows.Forms.Label
Friend WithEvents  txtDesc As System.Windows.Forms.TextBox
Friend WithEvents ErrDesc As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcSocInc_Desc As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblDedValue As System.Windows.Forms.Label
Friend WithEvents  txtDedValue As System.Windows.Forms.TextBox
Friend WithEvents ErrDedValue As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcSocInc_DedValue As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblConValue As System.Windows.Forms.Label
Friend WithEvents  txtConValue As System.Windows.Forms.TextBox
Friend WithEvents ErrConValue As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcSocIns_ConValue As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents sspStatus As System.Windows.Forms.StatusStrip
Friend WithEvents lblSSStatus As System.Windows.Forms.ToolStripStatusLabel
Friend WithEvents DG1 As System.Windows.Forms.DataGridView
Friend WithEvents TSC1 As System.Windows.Forms.ToolStripContainer
Friend WithEvents TS1 As System.Windows.Forms.ToolStrip
Friend WithEvents TSBNew As System.Windows.Forms.ToolStripButton
Friend WithEvents TSBSave As System.Windows.Forms.ToolStripButton
Friend WithEvents TSBDelete As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBExcel As System.Windows.Forms.ToolStripButton
End Class
