<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmPrSsEmployeeStatus
Inherits System.Windows.Forms.Form
<System.Diagnostics.DebuggerNonUserCode()> _
Protected Overrides Sub Dispose(ByVal disposing As Boolean)
If Disposing AndAlso components IsNot Nothing Then
components.Dispose()
End If
MyBase.Dispose(Disposing)
End Sub
Private components As System.ComponentModel.IContainer
' AutoGenerated Form by Nodalsoft
<System.Diagnostics.DebuggerStepThrough()> _
Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmPrSsEmployeeStatus))
        Me.sspStatus = New System.Windows.Forms.StatusStrip
        Me.lblSSStatus = New System.Windows.Forms.ToolStripStatusLabel
        Me.DG1 = New System.Windows.Forms.DataGridView
        Me.dgcEmpSta_Code = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmpSta_DescriptionL = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmpSta_DescriptionS = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.TSC1 = New System.Windows.Forms.ToolStripContainer
        Me.TS1 = New System.Windows.Forms.ToolStrip
        Me.TSBNew = New System.Windows.Forms.ToolStripButton
        Me.TSBSave = New System.Windows.Forms.ToolStripButton
        Me.TSBDelete = New System.Windows.Forms.ToolStripButton
        Me.TSBExcel = New System.Windows.Forms.ToolStripButton
        Me.lblEmpSta_Code = New System.Windows.Forms.Label
        Me.txtEmpSta_Code = New System.Windows.Forms.TextBox
        Me.ErrEmpSta_Code = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblEmpSta_DescriptionL = New System.Windows.Forms.Label
        Me.txtEmpSta_DescriptionL = New System.Windows.Forms.TextBox
        Me.ErrEmpSta_DescriptionL = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblEmpSta_DescriptionS = New System.Windows.Forms.Label
        Me.txtEmpSta_DescriptionS = New System.Windows.Forms.TextBox
        Me.ErrEmpSta_DescriptionS = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.sspStatus.SuspendLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.TSC1.TopToolStripPanel.SuspendLayout()
        Me.TSC1.SuspendLayout()
        Me.TS1.SuspendLayout()
        CType(Me.ErrEmpSta_Code, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEmpSta_DescriptionL, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEmpSta_DescriptionS, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'sspStatus
        '
        Me.sspStatus.BackColor = System.Drawing.SystemColors.Control
        Me.sspStatus.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.lblSSStatus})
        Me.sspStatus.Location = New System.Drawing.Point(0, 529)
        Me.sspStatus.Name = "sspStatus"
        Me.sspStatus.Size = New System.Drawing.Size(987, 22)
        Me.sspStatus.TabIndex = 3
        Me.sspStatus.Text = "StatusStrip"
        '
        'lblSSStatus
        '
        Me.lblSSStatus.Name = "lblSSStatus"
        Me.lblSSStatus.Size = New System.Drawing.Size(0, 17)
        '
        'DG1
        '
        Me.DG1.AllowUserToAddRows = False
        Me.DG1.AllowUserToDeleteRows = False
        Me.DG1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DG1.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.dgcEmpSta_Code, Me.dgcEmpSta_DescriptionL, Me.dgcEmpSta_DescriptionS})
        Me.DG1.Location = New System.Drawing.Point(12, 115)
        Me.DG1.Name = "DG1"
        Me.DG1.ReadOnly = True
        Me.DG1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
        Me.DG1.Size = New System.Drawing.Size(963, 400)
        Me.DG1.TabIndex = 10
        '
        'dgcEmpSta_Code
        '
        Me.dgcEmpSta_Code.DataPropertyName = "EmpSta_Code"
        Me.dgcEmpSta_Code.FillWeight = 150.0!
        Me.dgcEmpSta_Code.HeaderText = "Code"
        Me.dgcEmpSta_Code.Name = "dgcEmpSta_Code"
        Me.dgcEmpSta_Code.ReadOnly = True
        Me.dgcEmpSta_Code.Width = 60
        '
        'dgcEmpSta_DescriptionL
        '
        Me.dgcEmpSta_DescriptionL.DataPropertyName = "EmpSta_DescriptionL"
        Me.dgcEmpSta_DescriptionL.FillWeight = 150.0!
        Me.dgcEmpSta_DescriptionL.HeaderText = "DescriptionL"
        Me.dgcEmpSta_DescriptionL.Name = "dgcEmpSta_DescriptionL"
        Me.dgcEmpSta_DescriptionL.ReadOnly = True
        Me.dgcEmpSta_DescriptionL.Width = 250
        '
        'dgcEmpSta_DescriptionS
        '
        Me.dgcEmpSta_DescriptionS.DataPropertyName = "EmpSta_DescriptionS"
        Me.dgcEmpSta_DescriptionS.FillWeight = 150.0!
        Me.dgcEmpSta_DescriptionS.HeaderText = "DescriptionS"
        Me.dgcEmpSta_DescriptionS.Name = "dgcEmpSta_DescriptionS"
        Me.dgcEmpSta_DescriptionS.ReadOnly = True
        '
        'TSC1
        '
        Me.TSC1.BottomToolStripPanelVisible = False
        '
        'TSC1.ContentPanel
        '
        Me.TSC1.ContentPanel.Size = New System.Drawing.Size(987, 1)
        Me.TSC1.Dock = System.Windows.Forms.DockStyle.Top
        Me.TSC1.LeftToolStripPanelVisible = False
        Me.TSC1.Location = New System.Drawing.Point(0, 0)
        Me.TSC1.Name = "TSC1"
        Me.TSC1.RightToolStripPanelVisible = False
        Me.TSC1.Size = New System.Drawing.Size(987, 26)
        Me.TSC1.TabIndex = 12
        Me.TSC1.Text = "TSC1"
        '
        'TSC1.TopToolStripPanel
        '
        Me.TSC1.TopToolStripPanel.Controls.Add(Me.TS1)
        '
        'TS1
        '
        Me.TS1.Dock = System.Windows.Forms.DockStyle.None
        Me.TS1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.TSBNew, Me.TSBSave, Me.TSBDelete, Me.TSBExcel})
        Me.TS1.Location = New System.Drawing.Point(3, 0)
        Me.TS1.Name = "TS1"
        Me.TS1.Size = New System.Drawing.Size(252, 25)
        Me.TS1.TabIndex = 0
        '
        'TSBNew
        '
        Me.TSBNew.AutoSize = False
        Me.TSBNew.Image = CType(resources.GetObject("TSBNew.Image"), System.Drawing.Image)
        Me.TSBNew.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBNew.Name = "TSBNew"
        Me.TSBNew.Size = New System.Drawing.Size(60, 22)
        Me.TSBNew.Text = "New"
        Me.TSBNew.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBSave
        '
        Me.TSBSave.AutoSize = False
        Me.TSBSave.Image = CType(resources.GetObject("TSBSave.Image"), System.Drawing.Image)
        Me.TSBSave.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBSave.Name = "TSBSave"
        Me.TSBSave.Size = New System.Drawing.Size(60, 22)
        Me.TSBSave.Text = "Save"
        Me.TSBSave.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBDelete
        '
        Me.TSBDelete.AutoSize = False
        Me.TSBDelete.Enabled = False
        Me.TSBDelete.Image = CType(resources.GetObject("TSBDelete.Image"), System.Drawing.Image)
        Me.TSBDelete.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBDelete.Name = "TSBDelete"
        Me.TSBDelete.Size = New System.Drawing.Size(60, 22)
        Me.TSBDelete.Text = "Delete"
        Me.TSBDelete.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBExcel
        '
        Me.TSBExcel.AutoSize = False
        Me.TSBExcel.Image = Global.NodalPay.My.Resources.Resources.excel
        Me.TSBExcel.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBExcel.Name = "TSBExcel"
        Me.TSBExcel.Size = New System.Drawing.Size(60, 22)
        Me.TSBExcel.Text = "Excel"
        Me.TSBExcel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'lblEmpSta_Code
        '
        Me.lblEmpSta_Code.AutoSize = True
        Me.lblEmpSta_Code.Location = New System.Drawing.Point(37, 40)
        Me.lblEmpSta_Code.Name = "lblEmpSta_Code"
        Me.lblEmpSta_Code.Size = New System.Drawing.Size(32, 13)
        Me.lblEmpSta_Code.TabIndex = 0
        Me.lblEmpSta_Code.Text = "Code"
        '
        'txtEmpSta_Code
        '
        Me.txtEmpSta_Code.Location = New System.Drawing.Point(157, 40)
        Me.txtEmpSta_Code.MaxLength = 1
        Me.txtEmpSta_Code.Name = "txtEmpSta_Code"
        Me.txtEmpSta_Code.Size = New System.Drawing.Size(31, 20)
        Me.txtEmpSta_Code.TabIndex = 1
        '
        'ErrEmpSta_Code
        '
        Me.ErrEmpSta_Code.ContainerControl = Me
        '
        'lblEmpSta_DescriptionL
        '
        Me.lblEmpSta_DescriptionL.AutoSize = True
        Me.lblEmpSta_DescriptionL.Location = New System.Drawing.Point(37, 60)
        Me.lblEmpSta_DescriptionL.Name = "lblEmpSta_DescriptionL"
        Me.lblEmpSta_DescriptionL.Size = New System.Drawing.Size(66, 13)
        Me.lblEmpSta_DescriptionL.TabIndex = 2
        Me.lblEmpSta_DescriptionL.Text = "DescriptionL"
        '
        'txtEmpSta_DescriptionL
        '
        Me.txtEmpSta_DescriptionL.Location = New System.Drawing.Point(157, 60)
        Me.txtEmpSta_DescriptionL.MaxLength = 40
        Me.txtEmpSta_DescriptionL.Name = "txtEmpSta_DescriptionL"
        Me.txtEmpSta_DescriptionL.Size = New System.Drawing.Size(250, 20)
        Me.txtEmpSta_DescriptionL.TabIndex = 2
        '
        'ErrEmpSta_DescriptionL
        '
        Me.ErrEmpSta_DescriptionL.ContainerControl = Me
        '
        'lblEmpSta_DescriptionS
        '
        Me.lblEmpSta_DescriptionS.AutoSize = True
        Me.lblEmpSta_DescriptionS.Location = New System.Drawing.Point(37, 80)
        Me.lblEmpSta_DescriptionS.Name = "lblEmpSta_DescriptionS"
        Me.lblEmpSta_DescriptionS.Size = New System.Drawing.Size(67, 13)
        Me.lblEmpSta_DescriptionS.TabIndex = 3
        Me.lblEmpSta_DescriptionS.Text = "DescriptionS"
        '
        'txtEmpSta_DescriptionS
        '
        Me.txtEmpSta_DescriptionS.Location = New System.Drawing.Point(157, 80)
        Me.txtEmpSta_DescriptionS.MaxLength = 15
        Me.txtEmpSta_DescriptionS.Name = "txtEmpSta_DescriptionS"
        Me.txtEmpSta_DescriptionS.Size = New System.Drawing.Size(100, 20)
        Me.txtEmpSta_DescriptionS.TabIndex = 3
        '
        'ErrEmpSta_DescriptionS
        '
        Me.ErrEmpSta_DescriptionS.ContainerControl = Me
        '
        'frmPrSsEmployeeStatus
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.SystemColors.GradientActiveCaption
        Me.ClientSize = New System.Drawing.Size(987, 551)
        Me.Controls.Add(Me.lblEmpSta_Code)
        Me.Controls.Add(Me.txtEmpSta_Code)
        Me.Controls.Add(Me.lblEmpSta_DescriptionL)
        Me.Controls.Add(Me.txtEmpSta_DescriptionL)
        Me.Controls.Add(Me.lblEmpSta_DescriptionS)
        Me.Controls.Add(Me.txtEmpSta_DescriptionS)
        Me.Controls.Add(Me.TSC1)
        Me.Controls.Add(Me.sspStatus)
        Me.Controls.Add(Me.DG1)
        Me.Name = "frmPrSsEmployeeStatus"
        Me.Text = "Employee Status"
        Me.sspStatus.ResumeLayout(False)
        Me.sspStatus.PerformLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.TSC1.TopToolStripPanel.ResumeLayout(False)
        Me.TSC1.TopToolStripPanel.PerformLayout()
        Me.TSC1.ResumeLayout(False)
        Me.TSC1.PerformLayout()
        Me.TS1.ResumeLayout(False)
        Me.TS1.PerformLayout()
        CType(Me.ErrEmpSta_Code, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEmpSta_DescriptionL, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEmpSta_DescriptionS, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
Friend WithEvents  lblEmpSta_Code As System.Windows.Forms.Label
Friend WithEvents  txtEmpSta_Code As System.Windows.Forms.TextBox
Friend WithEvents ErrEmpSta_Code As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcEmpSta_Code As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblEmpSta_DescriptionL As System.Windows.Forms.Label
Friend WithEvents  txtEmpSta_DescriptionL As System.Windows.Forms.TextBox
Friend WithEvents ErrEmpSta_DescriptionL As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcEmpSta_DescriptionL As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblEmpSta_DescriptionS As System.Windows.Forms.Label
Friend WithEvents  txtEmpSta_DescriptionS As System.Windows.Forms.TextBox
Friend WithEvents ErrEmpSta_DescriptionS As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcEmpSta_DescriptionS As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents sspStatus As System.Windows.Forms.StatusStrip
Friend WithEvents lblSSStatus As System.Windows.Forms.ToolStripStatusLabel
Friend WithEvents DG1 As System.Windows.Forms.DataGridView
Friend WithEvents TSC1 As System.Windows.Forms.ToolStripContainer
Friend WithEvents TS1 As System.Windows.Forms.ToolStrip
Friend WithEvents TSBNew As System.Windows.Forms.ToolStripButton
Friend WithEvents TSBSave As System.Windows.Forms.ToolStripButton
Friend WithEvents TSBDelete As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBExcel As System.Windows.Forms.ToolStripButton
End Class
