' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 27/03/2008 12:18:40
'
'
Public Class cPrMsEmployeeEarningsDbTier
    '
    Inherits cDataTier
    '
    Protected Function GetByPK(ByVal tId As Integer) As DataSet
        Dim Str As String
        Str = " SELECT" & _
                " EmpErn_Id," & _
                " Emp_Code," & _
                " ErnCod_Code," & _
                " EmpErn_Value," & _
                " TemGrp_Code" & _
            "  FROM PrMsEmployeeEarnings" & _
            "  WHERE EmpErn_Id = " & tId
        Return MyBase.GetData(Str)
    End Function
    Protected Function GetByEmpCodeErnCode(ByVal tEmpCode As String, ByVal tErnCode As String) As DataSet
        Dim Str As String
        Str = " SELECT" & _
                " EmpErn_Id," & _
                " Emp_Code," & _
                " ErnCod_Code," & _
                " EmpErn_Value," & _
                " TemGrp_Code" & _
                "  FROM PrMsEmployeeEarnings" & _
                "  WHERE Emp_Code = " & enQuoteString(tEmpCode) & _
                " AND ErnCod_Code=" & enQuoteString(tErnCode)
        Return MyBase.GetData(Str)
    End Function
    Protected Function Save(ByRef _cPrMsEmployeeEarnings As cPrMsEmployeeEarnings) As Boolean
        Dim SpParams As New ArrayList
        Dim SpNames As New ArrayList
        Dim Flag As Boolean = False
        With _cPrMsEmployeeEarnings
            SpParams.Add(.Id)                                                '(0)
            SpNames.Add("EmpErn_Id")                                         '(0)
            SpParams.Add(.EmpCode)                                           '(1)
            SpNames.Add("Emp_Code")                                          '(1)
            SpParams.Add(.ErnCode)                                           '(2)
            SpNames.Add("ErnCod_Code")                                       '(2)
            SpParams.Add(.MyValue)                                           '(3)
            SpNames.Add("EmpErn_Value")                                      '(3)
            SpParams.Add(.TemGrpCode)                                        '(4)
            SpNames.Add("TemGrp_Code")                                       '(4)
        End With
        SpNames.Add("NewId")                                             '(5)
        SpParams.Add(CInt(0))                                            '(5)
        If Me.StoredProcedure("AG_PrMsEmployeeEarnings_Save_Update", SpParams, SpNames, 5) Then
            If _cPrMsEmployeeEarnings.Id = 0 Then
                _cPrMsEmployeeEarnings.Id = DbNullToInt(SpParams(5))
            End If
            Return True
        Else
            Return False
        End If
    End Function
    Protected Function Delete(ByVal tId As Integer) As Boolean
        Dim Str As String
        Dim Flag As Boolean = True
        Dim Exx As New System.Exception
        Try
            BeginTransaction()
            Str = " DELETE FROM PrMsEmployeeEarnings" & _
               " WHERE EmpErn_Id = " & tId
            If MyBase.ExecuteNonQuery(Str) = -1 Then
                Throw Exx
            End If
            CommitTransaction()
        Catch ex As Exception
            Rollback()
            Utils.ShowException(ex)
            Flag = False
        End Try
        Return Flag
    End Function
    Protected Function CheckDeleteRecords(ByVal tCode As Integer) As DataSet
        Dim ds As DataSet
        '    Generation Note : 27/03/2008 12:18:40 :- No Foriegn Key Constraints where found
        ds = Nothing
        Return ds
    End Function
End Class
