' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 13/02/2008 09:42:50
'
'
Public Class cPrMsTemplateDeductionsDbTier
    '
    Inherits cDataTier
    '
    Protected Function GetByPK(ByVal tId As Integer) As DataSet
        Dim Str As String
        Str = " SELECT" & _
                " TemDed_id," & _
                " TemGrp_Code," & _
                " DedCod_Code," & _
                " TemDed_DisplayName," & _
                " TemDed_IsDispalyed," & _
                " TemDed_Sequence," & _
                " TemDed_TypeMode," & _
                " TemDed_FromMode," & _
                " TemDed_CreationDate," & _
                " TemDed_CalcFormula," & _
                " TemDed_CreatedBy," & _
                " TemDed_AmendDate," & _
                " TemDed_AmendBy," & _
                " TemDed_NavCreditAccount," & _
                " TemDed_NavDebitAccount, " & _
                " TemDed_ReportingSequence " & _
            "  FROM PrMsTemplateDeductions" & _
            "  WHERE TemDed_id = " & tId
        Return MyBase.GetData(Str)
    End Function
    Protected Function GetByIndex(ByVal tTemplateGroupCode As String, ByVal tDeductionCode As String) As DataSet
        Dim Str As String
        Str = " SELECT" & _
                " TemDed_id," & _
                " TemGrp_Code," & _
                " DedCod_Code," & _
                " TemDed_DisplayName," & _
                " TemDed_IsDispalyed," & _
                " TemDed_Sequence," & _
                " TemDed_TypeMode," & _
                " TemDed_FromMode," & _
                " TemDed_CreationDate," & _
                " TemDed_CalcFormula," & _
                " TemDed_CreatedBy," & _
                " TemDed_AmendDate," & _
                " TemDed_AmendBy," & _
                " TemDed_NavCreditAccount," & _
                " TemDed_NavDebitAccount, " & _
                " TemDed_ReportingSequence " & _
                "  FROM PrMsTemplateDeductions" & _
                "  WHERE TemGrp_Code = " & enQuoteString(tTemplateGroupCode) & _
                "  AND DedCod_Code=" & enQuoteString(tDeductionCode)

        Return MyBase.GetData(Str)
    End Function
    Protected Function Save(ByRef _cPrMsTemplateDeductions As cPrMsTemplateDeductions) As Boolean
        Dim SpParams As New ArrayList
        Dim SpNames As New ArrayList
        Dim Flag As Boolean = False
        With _cPrMsTemplateDeductions
            SpParams.Add(.Id)                                                '(0)
            SpNames.Add("TemDed_id")                                         '(0)
            SpParams.Add(.TemGrpCode)                                        '(1)
            SpNames.Add("TemGrp_Code")                                       '(1)
            SpParams.Add(.DedCodCode)                                        '(2)
            SpNames.Add("DedCod_Code")                                       '(2)
            SpParams.Add(.DisplayName)                                       '(3)
            SpNames.Add("TemDed_DisplayName")                                '(3)
            SpParams.Add(.IsDispalyed)                                       '(4)
            SpNames.Add("TemDed_IsDispalyed")                                '(4)
            SpParams.Add(.Sequence)                                          '(5)
            SpNames.Add("TemDed_Sequence")                                   '(5)
            SpParams.Add(.TypeMode)                                          '(6)
            SpNames.Add("TemDed_TypeMode")                                   '(6)
            SpParams.Add(.FromMode)                                          '(7)
            SpNames.Add("TemDed_FromMode")                                   '(7)
            SpParams.Add(.CreationDate)                                      '(8)
            SpNames.Add("TemDed_CreationDate")                               '(8)
            SpParams.Add(.CalcFormula)                                       '(9)
            SpNames.Add("TemDed_CalcFormula")                                '(9)
            SpParams.Add(.CreatedBy)                                         '(10)
            SpNames.Add("TemDed_CreatedBy")                                  '(10)
            SpParams.Add(.AmendDate)                                         '(11)
            SpNames.Add("TemDed_AmendDate")                                  '(11)
            SpParams.Add(.AmendBy)                                           '(12)
            SpNames.Add("TemDed_AmendBy")                                    '(12)
            SpParams.Add(.ConsolDesc)                                  '(13)
            SpNames.Add("TemDed_NavCreditAccount")                           '(13)
            SpParams.Add(.NavDebitAccount)                                   '(14)
            SpNames.Add("TemDed_NavDebitAccount")                            '(14)
            SpParams.Add(.ReportingSequence)                                   '(15)
            SpNames.Add("TemDed_ReportingSequence")                            '(15)
        End With
        SpNames.Add("NewId")                                             '(16)
        SpParams.Add(CInt(0))                                            '(16)
        If Me.StoredProcedure("AG_PrMsTemplateDeductions_Save_Update", SpParams, SpNames, 16) Then
            If _cPrMsTemplateDeductions.Id = 0 Then
                _cPrMsTemplateDeductions.Id = DbNullToInt(SpParams(16))
            End If
            Return True
        Else
            Return False
        End If
    End Function
    Protected Function Delete(ByVal tId As Integer) As Boolean
        Dim Str As String
        Dim Flag As Boolean = True
        Dim Exx As New System.Exception
        Try
            BeginTransaction()
            Str = " DELETE FROM PrMsTemplateDeductions" & _
               " WHERE TemDed_id = " & tId
            If MyBase.ExecuteNonQuery(Str) = -1 Then
                Throw Exx
            End If
            CommitTransaction()
        Catch ex As Exception
            Rollback()
            Utils.ShowException(ex)
            Flag = False
        End Try
        Return Flag
    End Function
    Protected Function CheckDeleteRecords(ByVal tCode As Integer) As DataSet
        Dim ds As DataSet
        '    Generation Note : 13/02/2008 09:42:50 :- No Foriegn Key Constraints where found
        ds = Nothing
        Return ds
    End Function
End Class
