' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 13/02/2008 09:42:45
'
'
Public Class cAaSsUsersDbTier
    '
    Inherits cDataTier
    '
    Protected Function GetByPK(ByVal tId As Integer) As DataSet
        Dim Str As String
        Str = " SELECT" & _
                " Usr_Id," & _
                " Usr_UserName," & _
                " Usr_FullName," & _
                " Usr_CreatedOn," & _
                " Usr_IsEnabled," & _
                " Usr_IsSA," & _
                " Usr_MyRole" & _
            "  FROM AaSsUsers" & _
            "  WHERE Usr_Id = " & tId
        Return MyBase.GetData(Str)
    End Function
    Protected Function Save(ByRef _cAaSsUsers As cAaSsUsers) As Boolean
        Dim SpParams As New ArrayList
        Dim SpNames As New ArrayList
        Dim Flag As Boolean = False
        With _cAaSsUsers
            SpParams.Add(.Id)                                                '(0)
            SpNames.Add("Usr_Id")                                            '(0)
            SpParams.Add(.UserName)                                          '(1)
            SpNames.Add("Usr_UserName")                                      '(1)
            SpParams.Add(.FullName)                                          '(2)
            SpNames.Add("Usr_FullName")                                      '(2)
            SpParams.Add(.CreatedOn)                                         '(3)
            SpNames.Add("Usr_CreatedOn")                                     '(3)
            SpParams.Add(.IsEnabled)                                         '(4)
            SpNames.Add("Usr_IsEnabled")                                     '(4)
            SpParams.Add(.IsSA)                                              '(5)
            SpNames.Add("Usr_IsSA")                                          '(5)
            SpParams.Add(.MyRole)                                            '(6)
            SpNames.Add("Usr_MyRole")                                        '(6)
        End With
        SpNames.Add("NewId")                                             '(7)
        SpParams.Add(CInt(0))                                            '(7)
        If Me.StoredProcedure("AG_AaSsUsers_Save_Update", SpParams, SpNames, 7) Then
            If _cAaSsUsers.Id = 0 Then
                _cAaSsUsers.Id = DbNullToInt(SpParams(7))
            End If
            Return True
        Else
            Return False
        End If
    End Function
    Protected Function Delete(ByVal tId As Integer) As Boolean
        Dim Str As String
        Dim Flag As Boolean = True
        Dim Exx As New System.Exception
        Try
            BeginTransaction()
            Str = " DELETE FROM AaSsUsers" & _
               " WHERE Usr_Id = " & tId
            If MyBase.ExecuteNonQuery(Str) = -1 Then
                Throw Exx
            End If
            CommitTransaction()
        Catch ex As Exception
            Rollback()
            Utils.ShowException(ex)
            Flag = False
        End Try
        Return Flag
    End Function
    Protected Function CheckDeleteRecords(ByVal tCode As Integer) As DataSet
        Dim Str As String
        Str = " " & _
        "SELECT COUNT(Emp_AmendBy) " & _
        " FROM PrMsEmployees" & _
        " WHERE Emp_AmendBy = " & tCode & _
        " " & _
        "SELECT COUNT(Emp_CreatedBy) " & _
        " FROM PrMsEmployees" & _
        " WHERE Emp_CreatedBy = " & tCode & _
        " " & _
        "SELECT COUNT(TemCon_AmendBy) " & _
        " FROM PrMsTemplateContributions" & _
        " WHERE TemCon_AmendBy = " & tCode & _
        " " & _
        "SELECT COUNT(TemCon_CreatedBy) " & _
        " FROM PrMsTemplateContributions" & _
        " WHERE TemCon_CreatedBy = " & tCode & _
        " " & _
        "SELECT COUNT(TemDed_AmendBy) " & _
        " FROM PrMsTemplateDeductions" & _
        " WHERE TemDed_AmendBy = " & tCode & _
        " " & _
        "SELECT COUNT(TemDed_CreatedBy) " & _
        " FROM PrMsTemplateDeductions" & _
        " WHERE TemDed_CreatedBy = " & tCode & _
        " " & _
        "SELECT COUNT(TemErn_AmendBy) " & _
        " FROM PrMsTemplateEarnings" & _
        " WHERE TemErn_AmendBy = " & tCode & _
        " " & _
        "SELECT COUNT(TemErn_CreatedBy) " & _
        " FROM PrMsTemplateEarnings" & _
        " WHERE TemErn_CreatedBy = " & tCode & _
        " " & _
        "SELECT COUNT(TaxTbl_AmendBy) " & _
        " FROM PrSsTaxTable" & _
        " WHERE TaxTbl_AmendBy = " & tCode & _
        " " & _
        "SELECT COUNT(TaxTbl_CreatedBy) " & _
        " FROM PrSsTaxTable" & _
        " WHERE TaxTbl_CreatedBy = " & tCode & _
        " " & _
        "SELECT COUNT(Usr_Id) " & _
        " FROM PrTxEmployeeDiscounts" & _
        " WHERE Usr_Id = " & tCode & _
        " " & _
        "SELECT COUNT(Usr_Id) " & _
        " FROM PrTxEmployeeHiring" & _
        " WHERE Usr_Id = " & tCode & _
        " " & _
        "SELECT COUNT(Usr_Id) " & _
        " FROM PrTxEmployeeSalary" & _
        " WHERE Usr_Id = " & tCode & _
        " " & _
        " "
        Return GetData(Str)
    End Function
End Class
