<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmAaSsPlaceHolder
Inherits System.Windows.Forms.Form
<System.Diagnostics.DebuggerNonUserCode()> _
Protected Overrides Sub Dispose(ByVal disposing As Boolean)
If Disposing AndAlso components IsNot Nothing Then
components.Dispose()
End If
MyBase.Dispose(Disposing)
End Sub
Private components As System.ComponentModel.IContainer
' AutoGenerated Form by Nodalsoft
<System.Diagnostics.DebuggerStepThrough()> _
Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmAaSsPlaceHolder))
        Me.sspStatus = New System.Windows.Forms.StatusStrip
        Me.lblSSStatus = New System.Windows.Forms.ToolStripStatusLabel
        Me.DG1 = New System.Windows.Forms.DataGridView
        Me.dgcAaSsPlaceHolder_dim_Key = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcAaSsPlaceHolder_dim_Value = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.TSC1 = New System.Windows.Forms.ToolStripContainer
        Me.TS1 = New System.Windows.Forms.ToolStrip
        Me.TSBNew = New System.Windows.Forms.ToolStripButton
        Me.TSBSave = New System.Windows.Forms.ToolStripButton
        Me.TSBDelete = New System.Windows.Forms.ToolStripButton
        Me.TSBExcel = New System.Windows.Forms.ToolStripButton
        Me.lbldim_Key = New System.Windows.Forms.Label
        Me.txtdim_Key = New System.Windows.Forms.TextBox
        Me.Errdim_Key = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lbldim_Value = New System.Windows.Forms.Label
        Me.txtdim_Value = New System.Windows.Forms.TextBox
        Me.Errdim_Value = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.sspStatus.SuspendLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.TSC1.TopToolStripPanel.SuspendLayout()
        Me.TSC1.SuspendLayout()
        Me.TS1.SuspendLayout()
        CType(Me.Errdim_Key, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.Errdim_Value, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'sspStatus
        '
        Me.sspStatus.BackColor = System.Drawing.SystemColors.Control
        Me.sspStatus.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.lblSSStatus})
        Me.sspStatus.Location = New System.Drawing.Point(0, 529)
        Me.sspStatus.Name = "sspStatus"
        Me.sspStatus.Size = New System.Drawing.Size(987, 22)
        Me.sspStatus.TabIndex = 3
        Me.sspStatus.Text = "StatusStrip"
        '
        'lblSSStatus
        '
        Me.lblSSStatus.Name = "lblSSStatus"
        Me.lblSSStatus.Size = New System.Drawing.Size(0, 17)
        '
        'DG1
        '
        Me.DG1.AllowUserToAddRows = False
        Me.DG1.AllowUserToDeleteRows = False
        Me.DG1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DG1.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.dgcAaSsPlaceHolder_dim_Key, Me.dgcAaSsPlaceHolder_dim_Value})
        Me.DG1.Location = New System.Drawing.Point(12, 100)
        Me.DG1.Name = "DG1"
        Me.DG1.ReadOnly = True
        Me.DG1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
        Me.DG1.Size = New System.Drawing.Size(963, 416)
        Me.DG1.TabIndex = 10
        '
        'dgcAaSsPlaceHolder_dim_Key
        '
        Me.dgcAaSsPlaceHolder_dim_Key.DataPropertyName = "AaSsPlaceHolder_dim_Key"
        Me.dgcAaSsPlaceHolder_dim_Key.FillWeight = 150.0!
        Me.dgcAaSsPlaceHolder_dim_Key.HeaderText = "dim_Key"
        Me.dgcAaSsPlaceHolder_dim_Key.Name = "dgcAaSsPlaceHolder_dim_Key"
        Me.dgcAaSsPlaceHolder_dim_Key.ReadOnly = True
        Me.dgcAaSsPlaceHolder_dim_Key.Width = 64
        '
        'dgcAaSsPlaceHolder_dim_Value
        '
        Me.dgcAaSsPlaceHolder_dim_Value.DataPropertyName = "AaSsPlaceHolder_dim_Value"
        Me.dgcAaSsPlaceHolder_dim_Value.FillWeight = 150.0!
        Me.dgcAaSsPlaceHolder_dim_Value.HeaderText = "dim_Value"
        Me.dgcAaSsPlaceHolder_dim_Value.Name = "dgcAaSsPlaceHolder_dim_Value"
        Me.dgcAaSsPlaceHolder_dim_Value.ReadOnly = True
        Me.dgcAaSsPlaceHolder_dim_Value.Width = 70
        '
        'TSC1
        '
        Me.TSC1.BottomToolStripPanelVisible = False
        '
        'TSC1.ContentPanel
        '
        Me.TSC1.ContentPanel.Size = New System.Drawing.Size(987, 1)
        Me.TSC1.Dock = System.Windows.Forms.DockStyle.Top
        Me.TSC1.LeftToolStripPanelVisible = False
        Me.TSC1.Location = New System.Drawing.Point(0, 0)
        Me.TSC1.Name = "TSC1"
        Me.TSC1.RightToolStripPanelVisible = False
        Me.TSC1.Size = New System.Drawing.Size(987, 26)
        Me.TSC1.TabIndex = 12
        Me.TSC1.Text = "TSC1"
        '
        'TSC1.TopToolStripPanel
        '
        Me.TSC1.TopToolStripPanel.Controls.Add(Me.TS1)
        '
        'TS1
        '
        Me.TS1.Dock = System.Windows.Forms.DockStyle.None
        Me.TS1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.TSBNew, Me.TSBSave, Me.TSBDelete, Me.TSBExcel})
        Me.TS1.Location = New System.Drawing.Point(3, 0)
        Me.TS1.Name = "TS1"
        Me.TS1.Size = New System.Drawing.Size(252, 25)
        Me.TS1.TabIndex = 0
        '
        'TSBNew
        '
        Me.TSBNew.AutoSize = False
        Me.TSBNew.Image = CType(resources.GetObject("TSBNew.Image"), System.Drawing.Image)
        Me.TSBNew.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBNew.Name = "TSBNew"
        Me.TSBNew.Size = New System.Drawing.Size(60, 22)
        Me.TSBNew.Text = "New"
        Me.TSBNew.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBSave
        '
        Me.TSBSave.AutoSize = False
        Me.TSBSave.Image = CType(resources.GetObject("TSBSave.Image"), System.Drawing.Image)
        Me.TSBSave.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBSave.Name = "TSBSave"
        Me.TSBSave.Size = New System.Drawing.Size(60, 22)
        Me.TSBSave.Text = "Save"
        Me.TSBSave.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBDelete
        '
        Me.TSBDelete.AutoSize = False
        Me.TSBDelete.Enabled = False
        Me.TSBDelete.Image = CType(resources.GetObject("TSBDelete.Image"), System.Drawing.Image)
        Me.TSBDelete.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBDelete.Name = "TSBDelete"
        Me.TSBDelete.Size = New System.Drawing.Size(60, 22)
        Me.TSBDelete.Text = "Delete"
        Me.TSBDelete.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBExcel
        '
        Me.TSBExcel.AutoSize = False
        Me.TSBExcel.Image = Global.NodalPay.My.Resources.Resources.excel
        Me.TSBExcel.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBExcel.Name = "TSBExcel"
        Me.TSBExcel.Size = New System.Drawing.Size(60, 22)
        Me.TSBExcel.Text = "Excel"
        Me.TSBExcel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'lbldim_Key
        '
        Me.lbldim_Key.AutoSize = True
        Me.lbldim_Key.Location = New System.Drawing.Point(37, 40)
        Me.lbldim_Key.Name = "lbldim_Key"
        Me.lbldim_Key.Size = New System.Drawing.Size(47, 13)
        Me.lbldim_Key.TabIndex = 0
        Me.lbldim_Key.Text = "dim_Key"
        '
        'txtdim_Key
        '
        Me.txtdim_Key.Location = New System.Drawing.Point(157, 40)
        Me.txtdim_Key.MaxLength = 9
        Me.txtdim_Key.Name = "txtdim_Key"
        Me.txtdim_Key.Size = New System.Drawing.Size(64, 20)
        Me.txtdim_Key.TabIndex = 1
        '
        'Errdim_Key
        '
        Me.Errdim_Key.ContainerControl = Me
        '
        'lbldim_Value
        '
        Me.lbldim_Value.AutoSize = True
        Me.lbldim_Value.Location = New System.Drawing.Point(37, 60)
        Me.lbldim_Value.Name = "lbldim_Value"
        Me.lbldim_Value.Size = New System.Drawing.Size(56, 13)
        Me.lbldim_Value.TabIndex = 2
        Me.lbldim_Value.Text = "dim_Value"
        '
        'txtdim_Value
        '
        Me.txtdim_Value.Location = New System.Drawing.Point(157, 60)
        Me.txtdim_Value.MaxLength = 10
        Me.txtdim_Value.Name = "txtdim_Value"
        Me.txtdim_Value.Size = New System.Drawing.Size(70, 20)
        Me.txtdim_Value.TabIndex = 2
        '
        'Errdim_Value
        '
        Me.Errdim_Value.ContainerControl = Me
        '
        'frmAaSsPlaceHolder
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.SystemColors.GradientActiveCaption
        Me.ClientSize = New System.Drawing.Size(987, 551)
        Me.Controls.Add(Me.lbldim_Key)
        Me.Controls.Add(Me.txtdim_Key)
        Me.Controls.Add(Me.lbldim_Value)
        Me.Controls.Add(Me.txtdim_Value)
        Me.Controls.Add(Me.TSC1)
        Me.Controls.Add(Me.sspStatus)
        Me.Controls.Add(Me.DG1)
        Me.Name = "frmAaSsPlaceHolder"
        Me.Text = "Place Holder"
        Me.sspStatus.ResumeLayout(False)
        Me.sspStatus.PerformLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.TSC1.TopToolStripPanel.ResumeLayout(False)
        Me.TSC1.TopToolStripPanel.PerformLayout()
        Me.TSC1.ResumeLayout(False)
        Me.TSC1.PerformLayout()
        Me.TS1.ResumeLayout(False)
        Me.TS1.PerformLayout()
        CType(Me.Errdim_Key, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.Errdim_Value, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
Friend WithEvents  lbldim_Key As System.Windows.Forms.Label
Friend WithEvents  txtdim_Key As System.Windows.Forms.TextBox
Friend WithEvents Errdim_Key As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcAaSsPlaceHolder_dim_Key As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lbldim_Value As System.Windows.Forms.Label
Friend WithEvents  txtdim_Value As System.Windows.Forms.TextBox
Friend WithEvents Errdim_Value As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcAaSsPlaceHolder_dim_Value As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents sspStatus As System.Windows.Forms.StatusStrip
Friend WithEvents lblSSStatus As System.Windows.Forms.ToolStripStatusLabel
Friend WithEvents DG1 As System.Windows.Forms.DataGridView
Friend WithEvents TSC1 As System.Windows.Forms.ToolStripContainer
Friend WithEvents TS1 As System.Windows.Forms.ToolStrip
Friend WithEvents TSBNew As System.Windows.Forms.ToolStripButton
Friend WithEvents TSBSave As System.Windows.Forms.ToolStripButton
Friend WithEvents TSBDelete As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBExcel As System.Windows.Forms.ToolStripButton
End Class
