' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 13/02/2008 09:42:50
'
'
Public Class cPrMsTemplateGroupDbTier
    '
    Inherits cDataTier
    '
    Protected Function GetByPK(ByVal tCode As String) As DataSet
        Dim Str As String
        Str = " SELECT" & _
                " TemGrp_Code," & _
                " PayTyp_Code," & _
                " TemGrp_DescriptionL," & _
                " TemGrp_DescriptionS," & _
                " TemGrp_IsActive," & _
                " TemGrp_DayUnits," & _
                " TemGrp_GLAnl1," & _
                " TemGrp_GLAnl2," & _
                " Com_Code" & _
            "  FROM PrMsTemplateGroup" & _
            "  WHERE TemGrp_Code = '" & tCode & "'"
        Return MyBase.GetData(Str)
    End Function
    Protected Function Save(ByVal _cPrMsTemplateGroup As cPrMsTemplateGroup) As Boolean
        Dim SpParams As New ArrayList
        Dim SpNames As New ArrayList
        Dim Flag As Boolean = False
        With _cPrMsTemplateGroup
            SpParams.Add(.Code)                                              '(0)
            SpNames.Add("TemGrp_Code")                                       '(0)
            SpParams.Add(.PayTypCode)                                        '(1)
            SpNames.Add("PayTyp_Code")                                       '(1)
            SpParams.Add(.DescriptionL)                                      '(2)
            SpNames.Add("TemGrp_DescriptionL")                               '(2)
            SpParams.Add(.DescriptionS)                                      '(3)
            SpNames.Add("TemGrp_DescriptionS")                               '(3)
            SpParams.Add(.IsActive)                                          '(4)
            SpNames.Add("TemGrp_IsActive")                                   '(4)
            SpParams.Add(.DayUnits)                                          '(5)
            SpNames.Add("TemGrp_DayUnits")                                   '(5)
            SpParams.Add(.GLAnl1)                                            '(6)
            SpNames.Add("TemGrp_GLAnl1")                                     '(6)
            SpParams.Add(.GLAnl2)                                            '(7)
            SpNames.Add("TemGrp_GLAnl2")                                     '(7)
            SpParams.Add(.CompanyCode)                                       '(8)
            SpNames.Add("Com_Code")                                          '(8)
        End With
        If Me.StoredProcedure("AG_PrMsTemplateGroup_Save_Update", SpParams, SpNames) Then
            Return True
        Else
            Return False
        End If
    End Function
    Protected Function Delete(ByVal tCode As String) As Boolean
        Dim Str As String
        Dim Flag As Boolean = True
        Dim Exx As New System.Exception
        Try
            BeginTransaction()
            Str = " DELETE FROM PrMsTemplateGroup" & _
               " WHERE TemGrp_Code = '" & tCode & "'"
            If MyBase.ExecuteNonQuery(Str) = -1 Then
                Throw Exx
            End If
            CommitTransaction()
        Catch ex As Exception
            Rollback()
            Utils.ShowException(ex)
            Flag = False
        End Try
        Return Flag
    End Function
    Protected Function CheckDeleteRecords(ByVal tCode As String) As DataSet
        Dim Str As String
        Str = " " & _
        "SELECT COUNT(TemGrp_Code) " & _
        " FROM PrMsEmployees" & _
        " WHERE TemGrp_Code = '" & tCode & "'" & _
        " " & _
        "SELECT COUNT(TemGrp_Code) " & _
        " FROM PrMsPeriodGroups" & _
        " WHERE TemGrp_Code = '" & tCode & "'" & _
        " " & _
        "SELECT COUNT(TemGrp_Code) " & _
        " FROM PrMsTemplateContributions" & _
        " WHERE TemGrp_Code = '" & tCode & "'" & _
        " " & _
        "SELECT COUNT(TemGrp_Code) " & _
        " FROM PrMsTemplateDeductions" & _
        " WHERE TemGrp_Code = '" & tCode & "'" & _
        " " & _
        "SELECT COUNT(TemGrp_Code) " & _
        " FROM PrMsTemplateEarnings" & _
        " WHERE TemGrp_Code = '" & tCode & "'" & _
        " " & _
        " "
        Return GetData(Str)
    End Function
End Class
