' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 06/11/07 9:50:34 AM
'
'
Public Class cFiMsBudgetDbTier
    '
    Inherits cDataTier
    '
    Protected Function GetByPK(ByVal tBud_Code As String) As DataSet
        Dim Str As String
        Str = " SELECT" & _
                " Bud_Code," & _
                " Bud_DescriptionL," & _
                " Bud_DescriptionS," & _
                " Bud_CreationDate," & _
                " Bud_AmendDate," & _
                " Bud_IsActive" & _
            "  FROM FiMsBudget" & _
            "  WHERE Bud_Code = '" & tBud_Code & "'"
        Return MyBase.GetData(Str)
    End Function
    Protected Function Save(ByVal _cFiMsBudget As cFiMsBudget) As Boolean
        Dim SpParams As New ArrayList
        Dim SpNames As New ArrayList
        Dim Flag As Boolean = False
        With _cFiMsBudget
            SpParams.Add(.Bud_Code)                                          '(0)
            SpNames.Add("Bud_Code")                                          '(0)
            SpParams.Add(.Bud_DescriptionL)                                  '(1)
            SpNames.Add("Bud_DescriptionL")                                  '(1)
            SpParams.Add(.Bud_DescriptionS)                                  '(2)
            SpNames.Add("Bud_DescriptionS")                                  '(2)
            SpParams.Add(.Bud_CreationDate)                                  '(3)
            SpNames.Add("Bud_CreationDate")                                  '(3)
            SpParams.Add(.Bud_AmendDate)                                     '(4)
            SpNames.Add("Bud_AmendDate")                                     '(4)
            SpParams.Add(.Bud_IsActive)                                      '(5)
            SpNames.Add("Bud_IsActive")                                      '(5)
        End With
        If Me.StoredProcedure("AG_FiMsBudget_Save_Update", SpParams, SpNames) Then
            Return True
        Else
            Return False
        End If
    End Function
    Protected Function Delete(ByVal tBud_Code As String) As Boolean
        Dim Str As String
        Dim Flag As Boolean = True
        Dim Exx As System.Exception
        Try
            BeginTransaction()
            Str = " DELETE FROM FiMsBudget" & _
               " WHERE Bud_Code = '" & tBud_Code & "'"
            If MyBase.ExecuteNonQuery(Str) = -1 Then
                Throw Exx
            End If
            CommitTransaction()
        Catch ex As Exception
            Rollback()
            Utils.ShowException(ex)
            Flag = False
        End Try
        Return Flag
    End Function
    Protected Function CheckDeleteRecords(ByVal tCode As String) As DataSet
        Dim Str As String
        Str = " " & _
        "SELECT COUNT(Bud_Code) " & _
        " FROM FiTxBudgetLines" & _
        " WHERE Bud_Code = '" & tCode & "'" & _
        " " & _
        " "
        Return GetData(Str)
    End Function
End Class

