' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 19/05/2008 16:04:46
'
'
Public Class cPrTxTrxnHeaderDbTier
    '
    Inherits cDataTier
    '
    Protected Function GetByPK(ByVal tTrxHdr_Id As Integer) As DataSet
        Dim Str As String
        Str = " SELECT" & _
                " TrxHdr_Id," & _
                " Emp_Code," & _
                " PrdGrp_Code," & _
                " PrdCod_Code," & _
                " PayCat_Code," & _
                " TrxHdr_Date," & _
                " TrxHdr_Status," & _
                " TrxHdr_TotalErnPeriod," & _
                " TrxHdr_TotalErnYTD," & _
                " TrxHdr_TotalDedPeriod," & _
                " TrxHdr_TotalDedYTD," & _
                " TrxHdr_TotalConPeriod," & _
                " TrxHdr_TotalConYTD," & _
                " TrxHdr_SIIncome," & _
                " TrxHdr_TaxableIncome," & _
                " TrxHdr_PaymentMethod," & _
                " TrxHdr_PaymentRef," & _
                " TrxHdr_PeriodUnits," & _
                " TrxHdr_AnnualUnits," & _
                " TrxHdr_AnnualLeave," & _
                " TrxHdr_LifeInsurance," & _
                " TrxHdr_Discounts," & _
                " TrxHdr_Interfacestatus," & _
                " TrxHdr_Overtime1," & _
                " TrxHdr_Overtime2," & _
                " TrxHdr_SIUnits," & _
                " TrxHdr_MonthlySalary," & _
                " TrxHdr_NetSalary," & _
                " TrxHdr_PeriodInsurable, " & _
                " TemGrp_Code," & _
                " TrxHdr_ChequeNo," & _
                " TrxHdr_TaxableFromOther, " & _
                " TrxHdr_CurrencySymbol, " & _
                " TrxHdr_Rate, " & _
                " TrxHdr_NormalDays, " & _
                " TrxHdr_Salary1, " & _
                " TrxHdr_Salary2, " & _
                " TrxHdr_Overtime3," & _
                " TrxHdr_Sectors," & _
                " TrxHdr_Dutyhours," & _
                " TrxHdr_FlightHours," & _
                " TrxHdr_Commission," & _
                " TrxHdr_PBAmount," & _
                " TrxHdr_PBRate," & _
                " TrxHdr_Overlay," & _
                " TrxHdr_PeriodSplit, " & _
                " TrxHdr_PeriodSplitSI, " & _
                " TrxHdr_A1, " & _
                " TrxHdr_A2, " & _
                " TrxHdr_A3, " & _
                " TrxHdr_A4, " & _
                " TrxHdr_A5, " & _
                " TrxHdr_Union, " & _
                " TrxHdr_Position, " & _
                " TrxHdr_COLA, " & _
                " TrxHdr_MyRate, " & _
                " TrxHdr_FE, " & _
                " TrxHdr_NetYTD, " & _
                " TrxHdr_PFOnAgreedSalary, " & _
                " TrxHdr_BasisOnSalary, " & _
                " TrxHdr_GesiD, " & _
                " TrxHdr_GesiC, " & _
                " TrxHdr_Medical, " & _
                " Com_Code," & _
                " TrxHdr_Year, " & _
                " TrxHdr_GESIableAmount, " & _
                " Trxhdr_BIK_GESID," & _
                " Trxhdr_BIK_GESIC," & _
                " Trxhdr_BIK_Gesiable, " & _
                " Trxhdr_AnalGen1, " & _
                " Trxhdr_Maternity, " & _
                " Trxhdr_FEPercent, " & _
                " Trxhdr_FEControlAmount " & _
                "  FROM PrTxTrxnHeader" & _
                "  WHERE TrxHdr_Id = " & tTrxHdr_Id
        Return MyBase.GetData(Str)
    End Function
    Protected Function GetByEmployeeCodeAndPeriod(ByVal tEmpCode As String, ByVal tPeriodCode As String) As DataSet
        Dim Str As String
        Str = " SELECT" & _
                " TrxHdr_Id," & _
                " Emp_Code," & _
                " PrdGrp_Code," & _
                " PrdCod_Code," & _
                " PayCat_Code," & _
                " TrxHdr_Date," & _
                " TrxHdr_Status," & _
                " TrxHdr_TotalErnPeriod," & _
                " TrxHdr_TotalErnYTD," & _
                " TrxHdr_TotalDedPeriod," & _
                " TrxHdr_TotalDedYTD," & _
                " TrxHdr_TotalConPeriod," & _
                " TrxHdr_TotalConYTD," & _
                " TrxHdr_SIIncome," & _
                " TrxHdr_TaxableIncome," & _
                " TrxHdr_PaymentMethod," & _
                " TrxHdr_PaymentRef," & _
                " TrxHdr_PeriodUnits," & _
                " TrxHdr_AnnualUnits," & _
                " TrxHdr_AnnualLeave," & _
                " TrxHdr_LifeInsurance," & _
                " TrxHdr_Discounts," & _
                " TrxHdr_Interfacestatus," & _
                " TrxHdr_Overtime1," & _
                " TrxHdr_Overtime2," & _
                " TrxHdr_SIUnits," & _
                " TrxHdr_MonthlySalary," & _
                " TrxHdr_NetSalary," & _
                " TrxHdr_PeriodInsurable," & _
                " TemGrp_Code," & _
                " TrxHdr_ChequeNo, " & _
                " TrxHdr_TaxableFromOther, " & _
                " TrxHdr_CurrencySymbol, " & _
                " TrxHdr_Rate, " & _
                " TrxHdr_NormalDays, " & _
                " TrxHdr_Salary1, " & _
                " TrxHdr_Salary2, " & _
                " TrxHdr_Overtime3," & _
                " TrxHdr_Sectors," & _
                " TrxHdr_Dutyhours," & _
                " TrxHdr_FlightHours," & _
                " TrxHdr_Commission," & _
                " TrxHdr_PBAmount," & _
                " TrxHdr_PBRate," & _
                " TrxHdr_Overlay," & _
                " TrxHdr_PeriodSplit, " & _
                " TrxHdr_PeriodSplitSI, " & _
                " TrxHdr_A1, " & _
                " TrxHdr_A2, " & _
                " TrxHdr_A3, " & _
                " TrxHdr_A4, " & _
                " TrxHdr_A5, " & _
                " TrxHdr_Union, " & _
                " TrxHdr_Position, " & _
                " TrxHdr_COLA, " & _
                " TrxHdr_MyRate, " & _
                " TrxHdr_FE, " & _
                " TrxHdr_NetYTD, " & _
                " TrxHdr_PFOnAgreedSalary, " & _
                " TrxHdr_BasisOnSalary, " & _
                " TrxHdr_GesiD, " & _
                " TrxHdr_GesiC, " & _
                " TrxHdr_Medical, " & _
                " Com_Code," & _
                " TrxHdr_Year, " & _
                " TrxHdr_GESIableAmount, " & _
                " Trxhdr_BIK_GESID," & _
                " Trxhdr_BIK_GESIC," & _
                " Trxhdr_BIK_Gesiable, " & _
                " Trxhdr_AnalGen1, " & _
                " Trxhdr_Maternity, " & _
                " Trxhdr_FEPercent, " & _
                " Trxhdr_FEControlAmount " & _
            "  FROM PrTxTrxnHeader" & _
            "  WHERE  Emp_Code=" & enQuoteString(tEmpCode) & _
            "  AND PrdCod_Code=" & enQuoteString(tPeriodCode)
        Return MyBase.GetData(Str)
    End Function
    Protected Function Save(ByRef _cPrTxTrxnHeader As cPrTxTrxnHeader) As Boolean
        Dim SpParams As New ArrayList
        Dim SpNames As New ArrayList
        Dim Flag As Boolean = False
        With _cPrTxTrxnHeader
            SpParams.Add(.Id)                                                '(0)
            SpNames.Add("TrxHdr_Id")                                         '(0)
            SpParams.Add(.Emp_Code)                                          '(1)
            SpNames.Add("Emp_Code")                                          '(1)
            SpParams.Add(.PrdGrp_Code)                                       '(2)
            SpNames.Add("PrdGrp_Code")                                       '(2)
            SpParams.Add(.PrdCod_Code)                                       '(3)
            SpNames.Add("PrdCod_Code")                                       '(3)
            SpParams.Add(.PayCat_Code)                                       '(4)
            SpNames.Add("PayCat_Code")                                       '(4)
            SpParams.Add(.MyDate)                                            '(5)
            SpNames.Add("TrxHdr_Date")                                       '(5)
            SpParams.Add(.Status)                                            '(6)
            SpNames.Add("TrxHdr_Status")                                     '(6)
            SpParams.Add(.TotalErnPeriod)                                    '(7)
            SpNames.Add("TrxHdr_TotalErnPeriod")                             '(7)
            SpParams.Add(.TotalErnYTD)                                       '(8)
            SpNames.Add("TrxHdr_TotalErnYTD")                                '(8)
            SpParams.Add(.TotalDedPeriod)                                    '(9)
            SpNames.Add("TrxHdr_TotalDedPeriod")                             '(9)
            SpParams.Add(.TotalDedYTD)                                       '(10)
            SpNames.Add("TrxHdr_TotalDedYTD")                                '(10)
            SpParams.Add(.TotalConPeriod)                                    '(11)
            SpNames.Add("TrxHdr_TotalConPeriod")                             '(11)
            SpParams.Add(.TotalConYTD)                                       '(12)
            SpNames.Add("TrxHdr_TotalConYTD")                                '(12)
            SpParams.Add(.SIIncome)                                          '(13)
            SpNames.Add("TrxHdr_SIIncome")                                   '(13)
            SpParams.Add(.TaxableIncome)                                     '(14)
            SpNames.Add("TrxHdr_TaxableIncome")                              '(14)
            SpParams.Add(.PaymentMethod)                                     '(15)
            SpNames.Add("TrxHdr_PaymentMethod")                              '(15)
            SpParams.Add(.PaymentRef)                                        '(16)
            SpNames.Add("TrxHdr_PaymentRef")                                 '(16)
            SpParams.Add(.PeriodUnits)                                       '(17)
            SpNames.Add("TrxHdr_PeriodUnits")                                '(17)
            SpParams.Add(.AnnualUnits)                                       '(18)
            SpNames.Add("TrxHdr_AnnualUnits")                                '(18)
            SpParams.Add(.AnnualLeave)                                       '(19)
            SpNames.Add("TrxHdr_AnnualLeave")                                '(19)
            SpParams.Add(.LifeInsurance)                                     '(20)
            SpNames.Add("TrxHdr_LifeInsurance")                              '(20)
            SpParams.Add(.Discounts)                                         '(21)
            SpNames.Add("TrxHdr_Discounts")                                  '(21)
            SpParams.Add(.InterfaceStatus)                                   '(22)
            SpNames.Add("TrxHdr_InterfaceStatus")                            '(22)
            SpParams.Add(.Overtime1)                                         '(23)
            SpNames.Add("TrxHdr_Overtime1")                                  '(23)
            SpParams.Add(.Overtime2)                                         '(24)
            SpNames.Add("TrxHdr_Overtime2")                                  '(24)
            SpParams.Add(.SIUnits)                                           '(25)
            SpNames.Add("TrxHdr_SIUnits")                                    '(25)
            SpParams.Add(.MonthlySalary)                                     '(26)
            SpNames.Add("TrxHdr_MonthlySalary")                              '(26)
            SpParams.Add(.NetSalary)                                         '(27)
            SpNames.Add("TrxHdr_NetSalary")                                  '(27)
            SpParams.Add(.PeriodInsurable)                                   '(28)
            SpNames.Add("TrxHdr_PeriodInsurable")                            '(28)
            SpParams.Add(.TemGrpCode)                                        '(29)
            SpNames.Add("TemGrp_Code")                                       '(29)
            SpParams.Add(.ChequeNo)                                          '(30)
            SpNames.Add("TrxHdr_ChequeNo")                                   '(30)
            SpParams.Add(.TaxableFromOther)                                 '(31)
            SpNames.Add("TrxHdr_TaxableFromOther")                           '(31)
            SpParams.Add(.Currency)                                         '(32)
            SpNames.Add("TrxHdr_CurrencySymbol")                            '(32)
            SpParams.Add(.CurRate)                                           '(33)
            SpNames.Add("TrxHdr_Rate")                                       '(33)
            SpParams.Add(.NormalDays)                                        '(34)
            SpNames.Add("TrxHdr_NormalDays")                                 '(34)
            SpParams.Add(.Salary1)                                           '(35)
            SpNames.Add("TrxHdr_Salary1")                                    '(35)
            SpParams.Add(.Salary2)                                           '(36)
            SpNames.Add("TrxHdr_Salary2")                                    '(36)
            SpParams.Add(.Overtime3)                                         '(37)
            SpNames.Add("TrxHdr_Overtime3")                                  '(37)

            SpParams.Add(.Sectors)                                           '(38)
            SpNames.Add("TrxHdr_Sectors")                                    '(38)
            SpParams.Add(.DutyHours)                                         '(39)
            SpNames.Add("TrxHdr_DutyHours")                                  '(39)
            SpParams.Add(.FlightHours)                                       '(40)
            SpNames.Add("TrxHdr_FlightHours")                                '(40)
            SpParams.Add(.Commission)                                        '(41)
            SpNames.Add("TrxHdr_Commission")                                 '(41)
            SpParams.Add(.PBAmount)                                          '(42)
            SpNames.Add("TrxHdr_PBamount")                                   '(42)
            SpParams.Add(.PBRate)                                            '(43)
            SpNames.Add("TrxHdr_PBRate")                                     '(43)
            SpParams.Add(.OverLay)                                            '(44)
            SpNames.Add("TrxHdr_Overlay")                                     '(44)
            SpParams.Add(.PeriodSplit)                                            '(45)
            SpNames.Add("TrxHdr_PeriodSplit")                                     '(45)
            SpParams.Add(.PeriodSplitSI)                                            '(46)
            SpNames.Add("TrxHdr_PeriodSplitSI")                                     '(46)

            SpParams.Add(.A1)                                                      '(47)
            SpNames.Add("TrxHdr_A1")                                               '(47)
            SpParams.Add(.A2)                                                      '(48)
            SpNames.Add("TrxHdr_A2")                                               '(48)
            SpParams.Add(.A3)                                                      '(49)
            SpNames.Add("TrxHdr_A3")                                               '(49)
            SpParams.Add(.A4)                                                      '(50)
            SpNames.Add("TrxHdr_A4")                                               '(50)
            SpParams.Add(.A5)                                                      '(51)
            SpNames.Add("TrxHdr_A5")                                               '(51)
            SpParams.Add(.Union)                                                   '(52)
            SpNames.Add("TrxHdr_Union")                                            '(52)
            SpParams.Add(.Position)                                                '(53)
            SpNames.Add("TrxHdr_Position")                                         '(53)
            SpParams.Add(.COLA)                                                    '(54)
            SpNames.Add("TrxHdr_COLA")                                             '(54)
            SpParams.Add(.MyRate)                                                  '(55)
            SpNames.Add("TrxHdr_myrate")                                           '(55)
            SpParams.Add(.MyFE)                                                  '(56)
            SpNames.Add("TrxHdr_FE")                                           '(56)
            SpParams.Add(.NetYTD)                                                  '(57)
            SpNames.Add("TrxHdr_NetYTD")                                           '(57)

            SpParams.Add(.PfOnAgreedSalary)                                                  '(58)
            SpNames.Add("TrxHdr_PFOnAgreedSalary")                                           '(58)
            SpParams.Add(.BasisOnSalary)                                                  '(59)
            SpNames.Add("TrxHdr_BasisOnSalary")                                           '(59)

            SpParams.Add(.GesiD)             '(60)
            SpNames.Add("TrxHdr_GesiD")      '(60)
            SpParams.Add(.GesiC)             '(61)
            SpNames.Add("TrxHdr_GesiC")      '(61)
            SpParams.Add(.Medical)           '(62)
            SpNames.Add("TrxHdr_Medical")    '(62)
            SpParams.Add(.Company)           '(63)
            SpNames.Add("Com_Code")          '(63)
            SpParams.Add(.Year)              '(64)
            SpNames.Add("TrxHdr_Year")       '(64)

            SpParams.Add(.GESIAbleAmount)      '(65)
            SpNames.Add("TrxHdr_GesiableAmount")  '(65)

            SpParams.Add(.BIK_GESID)         '(66)
            SpNames.Add("TrxHdr_BIK_GESID")  '(66)
            SpParams.Add(.BIK_GESIC)         '(67)
            SpNames.Add("TrxHdr_BIK_GESIC")  '(67)
            SpParams.Add(.BIK_GESIAble)         '(68)
            SpNames.Add("TrxHdr_BIK_GESIAble")  '(68)

            SpParams.Add(.analgen1)         '(69)
            SpNames.Add("TrxHdr_AnalGen1")  '(69)


            SpParams.Add(.Maternity)         '(70)
            SpNames.Add("TrxHdr_Maternity")  '(70)

            SpParams.Add(.FEPercent)         '(71)
            SpNames.Add("TrxHdr_FEPercent")  '(71)

            SpParams.Add(.FEControlAmount)         '(72)
            SpNames.Add("TrxHdr_FEControlAmount")  '(72)



        End With
        SpNames.Add("NewId")                                                 '(73)
        SpParams.Add(CInt(0))                                                '(73)
        If Me.StoredProcedure("AG_PrTxTrxnHeader_Save_Update", SpParams, SpNames, 73) Then
            If _cPrTxTrxnHeader.Id = 0 Then
                _cPrTxTrxnHeader.Id = DbNullToInt(SpParams(73))
            End If
            Return True
        Else
            Return False
        End If
    End Function
    Protected Function Delete(ByVal tTrxHdr_Id As Integer) As Boolean
        Dim Str As String
        Dim Flag As Boolean = True
        Dim Exx As New System.Exception
        Try
            BeginTransaction()
            Str = " DELETE FROM PrTxTrxnHeader" & _
               " WHERE TrxHdr_Id = " & tTrxHdr_Id
            If MyBase.ExecuteNonQuery(Str) = -1 Then
                Throw Exx
            End If
            CommitTransaction()
        Catch ex As Exception
            Rollback()
            Utils.ShowException(ex)
            Flag = False
        End Try
        Return Flag
    End Function
    Protected Function CheckDeleteRecords(ByVal tCode As Integer) As DataSet
        Dim Str As String
        Str = " " & _
        "SELECT COUNT(TrxHdr_Id) " & _
        " FROM PrTxTrxnLines" & _
        " WHERE TrxHdr_Id = " & tCode & _
        " " & _
        " "
        Return GetData(Str)
    End Function
End Class

