' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 13/02/2008 09:42:51
'
'
Public Class cPrSsParametersDbTier
    '
    Inherits cDataTier
    '
    Protected Function GetByPK(ByVal tId As Integer) As DataSet
        Dim Str As String
        Str = " SELECT" & _
                " Par_Id," & _
                " Par_Section," & _
                " Par_Item," & _
                " Par_Value," & _
                " Par_Description," & _
                " Par_System," & _
                " Par_Type" & _
            "  FROM PrSsParameters" & _
            "  WHERE Par_Id = " & tId
        Return MyBase.GetData(Str)
    End Function
    Protected Function GetByPK(ByVal tSection As String, ByVal tItem As String) As DataSet
        Dim Str As String
        Str = " SELECT" & _
                " Par_Id," & _
                " Par_Section," & _
                " Par_Item," & _
                " Par_Value," & _
                " Par_Description," & _
                " Par_System," & _
                " Par_Type" & _
            "  FROM PrSsParameters" & _
            "  WHERE Par_Section = " & enQuoteString(tSection) & _
            " and Par_Item = " & enQuoteString(tItem)
        Return MyBase.GetData(Str)
    End Function
    Protected Function Save(ByRef _cPrSsParameters As cPrSsParameters) As Boolean
        Dim SpParams As New ArrayList
        Dim SpNames As New ArrayList
        Dim Flag As Boolean = False
        With _cPrSsParameters
            SpParams.Add(.Id)                                                '(0)
            SpNames.Add("Par_Id")                                            '(0)
            SpParams.Add(.Section)                                           '(1)
            SpNames.Add("Par_Section")                                       '(1)
            SpParams.Add(.Item)                                              '(2)
            SpNames.Add("Par_Item")                                          '(2)
            SpParams.Add(.Value1)                                            '(3)
            SpNames.Add("Par_Value")                                         '(3)
            SpParams.Add(.Description)                                       '(4)
            SpNames.Add("Par_Description")                                   '(4)
            SpParams.Add(.System1)                                           '(5)
            SpNames.Add("Par_System")                                        '(5)
            SpParams.Add(.Type1)                                             '(6)
            SpNames.Add("Par_Type")                                          '(6)
        End With
        SpNames.Add("NewId")                                             '(7)
        SpParams.Add(CInt(0))                                            '(7)
        If Me.StoredProcedure("AG_PrSsParameters_Save_Update", SpParams, SpNames, 7) Then
            If _cPrSsParameters.Id = 0 Then
                _cPrSsParameters.Id = DbNullToInt(SpParams(7))
            End If
            Return True
        Else
            Return False
        End If
    End Function
    Protected Function Delete(ByVal tId As Integer) As Boolean
        Dim Str As String
        Dim Flag As Boolean = True
        Dim Exx As New System.Exception
        Try
            BeginTransaction()
            Str = " DELETE FROM PrSsParameters" & _
               " WHERE Par_Id = " & tId
            If MyBase.ExecuteNonQuery(Str) = -1 Then
                Throw Exx
            End If
            CommitTransaction()
        Catch ex As Exception
            Rollback()
            Utils.ShowException(ex)
            Flag = False
        End Try
        Return Flag
    End Function
    Protected Function CheckDeleteRecords(ByVal tCode As Integer) As DataSet
        Dim ds As DataSet
        '    Generation Note : 13/02/2008 09:42:51 :- No Foriegn Key Constraints where found
        ds = Nothing
        Return ds
    End Function
End Class
