<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmPrTxEmployeeSalary
    Inherits System.Windows.Forms.Form
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing AndAlso components IsNot Nothing Then
            components.Dispose()
        End If
        MyBase.Dispose(disposing)
    End Sub
    Private components As System.ComponentModel.IContainer
    ' AutoGenerated Form by Nodalsoft
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container
        Dim DataGridViewCellStyle1 As System.Windows.Forms.DataGridViewCellStyle = New System.Windows.Forms.DataGridViewCellStyle
        Dim DataGridViewCellStyle2 As System.Windows.Forms.DataGridViewCellStyle = New System.Windows.Forms.DataGridViewCellStyle
        Dim DataGridViewCellStyle3 As System.Windows.Forms.DataGridViewCellStyle = New System.Windows.Forms.DataGridViewCellStyle
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmPrTxEmployeeSalary))
        Me.sspStatus = New System.Windows.Forms.StatusStrip
        Me.lblSSStatus = New System.Windows.Forms.ToolStripStatusLabel
        Me.DG1 = New System.Windows.Forms.DataGridView
        Me.dgcEmpSal_id = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmp_Code = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmpSal_Date = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmpSal_Value = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmpSal_Basic = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmpSal_Cola = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmpSal_IsCola = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmpSal_EffPayDate = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcUsr_Id = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmpSal_EffArrearsDate = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.TSC1 = New System.Windows.Forms.ToolStripContainer
        Me.TS1 = New System.Windows.Forms.ToolStrip
        Me.TSBNew = New System.Windows.Forms.ToolStripButton
        Me.TSBSave = New System.Windows.Forms.ToolStripButton
        Me.TSBDelete = New System.Windows.Forms.ToolStripButton
        Me.TSBExcel = New System.Windows.Forms.ToolStripButton
        Me.BtnCalculateSalaryForCOLA = New System.Windows.Forms.ToolStripButton
        Me.lblId = New System.Windows.Forms.Label
        Me.txtId = New System.Windows.Forms.TextBox
        Me.ErrId = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.ErrEmp_Code = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDate1 = New System.Windows.Forms.Label
        Me.ErrDate1 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblSalaryValue = New System.Windows.Forms.Label
        Me.txtSalaryValue = New System.Windows.Forms.TextBox
        Me.ErrSalaryValue = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblBasic = New System.Windows.Forms.Label
        Me.txtBasic = New System.Windows.Forms.TextBox
        Me.ErrBasic = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblEffPayDate = New System.Windows.Forms.Label
        Me.ErrEffPayDate = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblCola = New System.Windows.Forms.Label
        Me.txtCola = New System.Windows.Forms.TextBox
        Me.ErrCola = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblEffArrearsDate = New System.Windows.Forms.Label
        Me.ErrEffArrearsDate = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.Usr = New System.Windows.Forms.Label
        Me.cmbUsr = New System.Windows.Forms.ComboBox
        Me.ErrUsr_Id = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblIsCola = New System.Windows.Forms.Label
        Me.ErrIsCola = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.DateArrears = New System.Windows.Forms.DateTimePicker
        Me.DateCreation = New System.Windows.Forms.DateTimePicker
        Me.DatePay = New System.Windows.Forms.DateTimePicker
        Me.CBIsCOLA = New System.Windows.Forms.CheckBox
        Me.btnCalculateBasic = New System.Windows.Forms.Button
        Me.Button1 = New System.Windows.Forms.Button
        Me.Label1 = New System.Windows.Forms.Label
        Me.txtUnitRate = New System.Windows.Forms.TextBox
        Me.Button2 = New System.Windows.Forms.Button
        Me.Button3 = New System.Windows.Forms.Button
        Me.txtCopyFrom = New System.Windows.Forms.TextBox
        Me.Button4 = New System.Windows.Forms.Button
        Me.Label6 = New System.Windows.Forms.Label
        Me.txtEmployeeName = New System.Windows.Forms.TextBox
        Me.Label5 = New System.Windows.Forms.Label
        Me.txtEmployeeCode = New System.Windows.Forms.TextBox
        Me.BtnNext = New System.Windows.Forms.Button
        Me.BtnPrevius = New System.Windows.Forms.Button
        Me.Label2 = New System.Windows.Forms.Label
        Me.txtSalary2ForRate = New System.Windows.Forms.TextBox
        Me.sspStatus.SuspendLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.TSC1.TopToolStripPanel.SuspendLayout()
        Me.TSC1.SuspendLayout()
        Me.TS1.SuspendLayout()
        CType(Me.ErrId, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEmp_Code, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDate1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrSalaryValue, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrBasic, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEffPayDate, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrCola, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEffArrearsDate, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrUsr_Id, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrIsCola, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'sspStatus
        '
        Me.sspStatus.BackColor = System.Drawing.SystemColors.Control
        Me.sspStatus.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.lblSSStatus})
        Me.sspStatus.Location = New System.Drawing.Point(0, 597)
        Me.sspStatus.Name = "sspStatus"
        Me.sspStatus.Size = New System.Drawing.Size(746, 22)
        Me.sspStatus.TabIndex = 3
        Me.sspStatus.Text = "StatusStrip"
        '
        'lblSSStatus
        '
        Me.lblSSStatus.Name = "lblSSStatus"
        Me.lblSSStatus.Size = New System.Drawing.Size(0, 17)
        '
        'DG1
        '
        Me.DG1.AllowUserToAddRows = False
        Me.DG1.AllowUserToDeleteRows = False
        Me.DG1.BackgroundColor = System.Drawing.SystemColors.Window
        Me.DG1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DG1.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.dgcEmpSal_id, Me.dgcEmp_Code, Me.dgcEmpSal_Date, Me.dgcEmpSal_Value, Me.dgcEmpSal_Basic, Me.dgcEmpSal_Cola, Me.dgcEmpSal_IsCola, Me.dgcEmpSal_EffPayDate, Me.dgcUsr_Id, Me.dgcEmpSal_EffArrearsDate})
        Me.DG1.Location = New System.Drawing.Point(12, 362)
        Me.DG1.Name = "DG1"
        Me.DG1.ReadOnly = True
        Me.DG1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
        Me.DG1.Size = New System.Drawing.Size(722, 245)
        Me.DG1.TabIndex = 10
        '
        'dgcEmpSal_id
        '
        Me.dgcEmpSal_id.DataPropertyName = "EmpSal_id"
        Me.dgcEmpSal_id.FillWeight = 150.0!
        Me.dgcEmpSal_id.HeaderText = "id"
        Me.dgcEmpSal_id.Name = "dgcEmpSal_id"
        Me.dgcEmpSal_id.ReadOnly = True
        Me.dgcEmpSal_id.Visible = False
        Me.dgcEmpSal_id.Width = 64
        '
        'dgcEmp_Code
        '
        Me.dgcEmp_Code.DataPropertyName = "Emp_Code"
        Me.dgcEmp_Code.FillWeight = 150.0!
        Me.dgcEmp_Code.HeaderText = "Employee Code"
        Me.dgcEmp_Code.Name = "dgcEmp_Code"
        Me.dgcEmp_Code.ReadOnly = True
        Me.dgcEmp_Code.Visible = False
        Me.dgcEmp_Code.Width = 106
        '
        'dgcEmpSal_Date
        '
        Me.dgcEmpSal_Date.DataPropertyName = "EmpSal_Date"
        DataGridViewCellStyle1.Format = "dd/MM/yyyy"
        Me.dgcEmpSal_Date.DefaultCellStyle = DataGridViewCellStyle1
        Me.dgcEmpSal_Date.FillWeight = 150.0!
        Me.dgcEmpSal_Date.HeaderText = "Date"
        Me.dgcEmpSal_Date.Name = "dgcEmpSal_Date"
        Me.dgcEmpSal_Date.ReadOnly = True
        Me.dgcEmpSal_Date.Width = 70
        '
        'dgcEmpSal_Value
        '
        Me.dgcEmpSal_Value.DataPropertyName = "EmpSal_Value"
        Me.dgcEmpSal_Value.FillWeight = 150.0!
        Me.dgcEmpSal_Value.HeaderText = "Salary Value"
        Me.dgcEmpSal_Value.Name = "dgcEmpSal_Value"
        Me.dgcEmpSal_Value.ReadOnly = True
        '
        'dgcEmpSal_Basic
        '
        Me.dgcEmpSal_Basic.DataPropertyName = "EmpSal_Basic"
        Me.dgcEmpSal_Basic.FillWeight = 150.0!
        Me.dgcEmpSal_Basic.HeaderText = "Basic Value"
        Me.dgcEmpSal_Basic.Name = "dgcEmpSal_Basic"
        Me.dgcEmpSal_Basic.ReadOnly = True
        '
        'dgcEmpSal_Cola
        '
        Me.dgcEmpSal_Cola.DataPropertyName = "EmpSal_Cola"
        Me.dgcEmpSal_Cola.FillWeight = 150.0!
        Me.dgcEmpSal_Cola.HeaderText = "Cola Value"
        Me.dgcEmpSal_Cola.Name = "dgcEmpSal_Cola"
        Me.dgcEmpSal_Cola.ReadOnly = True
        '
        'dgcEmpSal_IsCola
        '
        Me.dgcEmpSal_IsCola.DataPropertyName = "EmpSal_IsCola"
        Me.dgcEmpSal_IsCola.FillWeight = 150.0!
        Me.dgcEmpSal_IsCola.HeaderText = "Is Cola Enabled"
        Me.dgcEmpSal_IsCola.Name = "dgcEmpSal_IsCola"
        Me.dgcEmpSal_IsCola.ReadOnly = True
        Me.dgcEmpSal_IsCola.Width = 60
        '
        'dgcEmpSal_EffPayDate
        '
        Me.dgcEmpSal_EffPayDate.DataPropertyName = "EmpSal_EffPayDate"
        DataGridViewCellStyle2.Format = "dd/MM/yyyy"
        Me.dgcEmpSal_EffPayDate.DefaultCellStyle = DataGridViewCellStyle2
        Me.dgcEmpSal_EffPayDate.FillWeight = 150.0!
        Me.dgcEmpSal_EffPayDate.HeaderText = "Pay Date"
        Me.dgcEmpSal_EffPayDate.Name = "dgcEmpSal_EffPayDate"
        Me.dgcEmpSal_EffPayDate.ReadOnly = True
        Me.dgcEmpSal_EffPayDate.Width = 70
        '
        'dgcUsr_Id
        '
        Me.dgcUsr_Id.DataPropertyName = "Usr_Id"
        Me.dgcUsr_Id.FillWeight = 150.0!
        Me.dgcUsr_Id.HeaderText = "User Id"
        Me.dgcUsr_Id.Name = "dgcUsr_Id"
        Me.dgcUsr_Id.ReadOnly = True
        Me.dgcUsr_Id.Visible = False
        '
        'dgcEmpSal_EffArrearsDate
        '
        Me.dgcEmpSal_EffArrearsDate.DataPropertyName = "EmpSal_EffArrearsDate"
        DataGridViewCellStyle3.Format = "dd/MM/yyyy"
        Me.dgcEmpSal_EffArrearsDate.DefaultCellStyle = DataGridViewCellStyle3
        Me.dgcEmpSal_EffArrearsDate.FillWeight = 150.0!
        Me.dgcEmpSal_EffArrearsDate.HeaderText = "Arrears Date"
        Me.dgcEmpSal_EffArrearsDate.Name = "dgcEmpSal_EffArrearsDate"
        Me.dgcEmpSal_EffArrearsDate.ReadOnly = True
        Me.dgcEmpSal_EffArrearsDate.Width = 70
        '
        'TSC1
        '
        Me.TSC1.BottomToolStripPanelVisible = False
        '
        'TSC1.ContentPanel
        '
        Me.TSC1.ContentPanel.Size = New System.Drawing.Size(746, 1)
        Me.TSC1.Dock = System.Windows.Forms.DockStyle.Top
        Me.TSC1.LeftToolStripPanelVisible = False
        Me.TSC1.Location = New System.Drawing.Point(0, 0)
        Me.TSC1.Name = "TSC1"
        Me.TSC1.RightToolStripPanelVisible = False
        Me.TSC1.Size = New System.Drawing.Size(746, 26)
        Me.TSC1.TabIndex = 12
        Me.TSC1.Text = "TSC1"
        '
        'TSC1.TopToolStripPanel
        '
        Me.TSC1.TopToolStripPanel.Controls.Add(Me.TS1)
        '
        'TS1
        '
        Me.TS1.Dock = System.Windows.Forms.DockStyle.None
        Me.TS1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.TSBNew, Me.TSBSave, Me.TSBDelete, Me.TSBExcel, Me.BtnCalculateSalaryForCOLA})
        Me.TS1.Location = New System.Drawing.Point(3, 0)
        Me.TS1.Name = "TS1"
        Me.TS1.Size = New System.Drawing.Size(443, 25)
        Me.TS1.TabIndex = 0
        '
        'TSBNew
        '
        Me.TSBNew.AutoSize = False
        Me.TSBNew.Image = CType(resources.GetObject("TSBNew.Image"), System.Drawing.Image)
        Me.TSBNew.Name = "TSBNew"
        Me.TSBNew.Size = New System.Drawing.Size(60, 22)
        Me.TSBNew.Text = "New"
        Me.TSBNew.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBSave
        '
        Me.TSBSave.AutoSize = False
        Me.TSBSave.Image = CType(resources.GetObject("TSBSave.Image"), System.Drawing.Image)
        Me.TSBSave.Name = "TSBSave"
        Me.TSBSave.Size = New System.Drawing.Size(60, 22)
        Me.TSBSave.Text = "Save"
        Me.TSBSave.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBDelete
        '
        Me.TSBDelete.AutoSize = False
        Me.TSBDelete.Image = CType(resources.GetObject("TSBDelete.Image"), System.Drawing.Image)
        Me.TSBDelete.Name = "TSBDelete"
        Me.TSBDelete.Size = New System.Drawing.Size(60, 22)
        Me.TSBDelete.Text = "Delete"
        Me.TSBDelete.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBExcel
        '
        Me.TSBExcel.AutoSize = False
        Me.TSBExcel.Image = Global.NodalPay.My.Resources.Resources.excel
        Me.TSBExcel.Name = "TSBExcel"
        Me.TSBExcel.Size = New System.Drawing.Size(60, 22)
        Me.TSBExcel.Text = "Excel"
        Me.TSBExcel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'BtnCalculateSalaryForCOLA
        '
        Me.BtnCalculateSalaryForCOLA.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text
        Me.BtnCalculateSalaryForCOLA.Image = CType(resources.GetObject("BtnCalculateSalaryForCOLA.Image"), System.Drawing.Image)
        Me.BtnCalculateSalaryForCOLA.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.BtnCalculateSalaryForCOLA.Name = "BtnCalculateSalaryForCOLA"
        Me.BtnCalculateSalaryForCOLA.Size = New System.Drawing.Size(191, 22)
        Me.BtnCalculateSalaryForCOLA.Text = "Re-Calc Salary after COLA Change"
        '
        'lblId
        '
        Me.lblId.AutoSize = True
        Me.lblId.Location = New System.Drawing.Point(356, 255)
        Me.lblId.Name = "lblId"
        Me.lblId.Size = New System.Drawing.Size(15, 13)
        Me.lblId.TabIndex = 0
        Me.lblId.Text = "id"
        Me.lblId.Visible = False
        '
        'txtId
        '
        Me.txtId.Location = New System.Drawing.Point(342, 172)
        Me.txtId.MaxLength = 9
        Me.txtId.Name = "txtId"
        Me.txtId.Size = New System.Drawing.Size(70, 20)
        Me.txtId.TabIndex = 1
        Me.txtId.Visible = False
        '
        'ErrId
        '
        Me.ErrId.ContainerControl = Me
        '
        'ErrEmp_Code
        '
        Me.ErrEmp_Code.ContainerControl = Me
        '
        'lblDate1
        '
        Me.lblDate1.AutoSize = True
        Me.lblDate1.Location = New System.Drawing.Point(28, 250)
        Me.lblDate1.Name = "lblDate1"
        Me.lblDate1.Size = New System.Drawing.Size(72, 13)
        Me.lblDate1.TabIndex = 3
        Me.lblDate1.Text = "Creation Date"
        '
        'ErrDate1
        '
        Me.ErrDate1.ContainerControl = Me
        '
        'lblSalaryValue
        '
        Me.lblSalaryValue.AutoSize = True
        Me.lblSalaryValue.Location = New System.Drawing.Point(28, 110)
        Me.lblSalaryValue.Name = "lblSalaryValue"
        Me.lblSalaryValue.Size = New System.Drawing.Size(66, 13)
        Me.lblSalaryValue.TabIndex = 4
        Me.lblSalaryValue.Text = "Salary Value"
        '
        'txtSalaryValue
        '
        Me.txtSalaryValue.Location = New System.Drawing.Point(179, 110)
        Me.txtSalaryValue.MaxLength = 15
        Me.txtSalaryValue.Name = "txtSalaryValue"
        Me.txtSalaryValue.Size = New System.Drawing.Size(100, 20)
        Me.txtSalaryValue.TabIndex = 1
        '
        'ErrSalaryValue
        '
        Me.ErrSalaryValue.ContainerControl = Me
        '
        'lblBasic
        '
        Me.lblBasic.AutoSize = True
        Me.lblBasic.Location = New System.Drawing.Point(28, 130)
        Me.lblBasic.Name = "lblBasic"
        Me.lblBasic.Size = New System.Drawing.Size(63, 13)
        Me.lblBasic.TabIndex = 5
        Me.lblBasic.Text = "Basic Value"
        '
        'txtBasic
        '
        Me.txtBasic.Location = New System.Drawing.Point(179, 130)
        Me.txtBasic.MaxLength = 15
        Me.txtBasic.Name = "txtBasic"
        Me.txtBasic.Size = New System.Drawing.Size(100, 20)
        Me.txtBasic.TabIndex = 2
        '
        'ErrBasic
        '
        Me.ErrBasic.ContainerControl = Me
        '
        'lblEffPayDate
        '
        Me.lblEffPayDate.AutoSize = True
        Me.lblEffPayDate.Location = New System.Drawing.Point(28, 190)
        Me.lblEffPayDate.Name = "lblEffPayDate"
        Me.lblEffPayDate.Size = New System.Drawing.Size(96, 13)
        Me.lblEffPayDate.TabIndex = 6
        Me.lblEffPayDate.Text = "Effective Pay Date"
        '
        'ErrEffPayDate
        '
        Me.ErrEffPayDate.ContainerControl = Me
        '
        'lblCola
        '
        Me.lblCola.AutoSize = True
        Me.lblCola.Location = New System.Drawing.Point(28, 150)
        Me.lblCola.Name = "lblCola"
        Me.lblCola.Size = New System.Drawing.Size(58, 13)
        Me.lblCola.TabIndex = 7
        Me.lblCola.Text = "Cola Value"
        '
        'txtCola
        '
        Me.txtCola.Location = New System.Drawing.Point(179, 150)
        Me.txtCola.MaxLength = 15
        Me.txtCola.Name = "txtCola"
        Me.txtCola.Size = New System.Drawing.Size(100, 20)
        Me.txtCola.TabIndex = 3
        '
        'ErrCola
        '
        Me.ErrCola.ContainerControl = Me
        '
        'lblEffArrearsDate
        '
        Me.lblEffArrearsDate.AutoSize = True
        Me.lblEffArrearsDate.Location = New System.Drawing.Point(28, 210)
        Me.lblEffArrearsDate.Name = "lblEffArrearsDate"
        Me.lblEffArrearsDate.Size = New System.Drawing.Size(111, 13)
        Me.lblEffArrearsDate.TabIndex = 8
        Me.lblEffArrearsDate.Text = "Effective Arrears Date"
        '
        'ErrEffArrearsDate
        '
        Me.ErrEffArrearsDate.ContainerControl = Me
        '
        'Usr
        '
        Me.Usr.AutoSize = True
        Me.Usr.Location = New System.Drawing.Point(28, 230)
        Me.Usr.Name = "Usr"
        Me.Usr.Size = New System.Drawing.Size(59, 13)
        Me.Usr.TabIndex = 9
        Me.Usr.Text = "Created By"
        '
        'cmbUsr
        '
        Me.cmbUsr.Enabled = False
        Me.cmbUsr.Location = New System.Drawing.Point(179, 227)
        Me.cmbUsr.Name = "cmbUsr"
        Me.cmbUsr.Size = New System.Drawing.Size(100, 21)
        Me.cmbUsr.TabIndex = 6
        '
        'ErrUsr_Id
        '
        Me.ErrUsr_Id.ContainerControl = Me
        '
        'lblIsCola
        '
        Me.lblIsCola.AutoSize = True
        Me.lblIsCola.Location = New System.Drawing.Point(28, 170)
        Me.lblIsCola.Name = "lblIsCola"
        Me.lblIsCola.Size = New System.Drawing.Size(81, 13)
        Me.lblIsCola.TabIndex = 10
        Me.lblIsCola.Text = "Is Cola Enabled"
        '
        'ErrIsCola
        '
        Me.ErrIsCola.ContainerControl = Me
        '
        'DateArrears
        '
        Me.DateArrears.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.DateArrears.Location = New System.Drawing.Point(179, 207)
        Me.DateArrears.Name = "DateArrears"
        Me.DateArrears.Size = New System.Drawing.Size(100, 20)
        Me.DateArrears.TabIndex = 5
        '
        'DateCreation
        '
        Me.DateCreation.Enabled = False
        Me.DateCreation.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.DateCreation.Location = New System.Drawing.Point(179, 248)
        Me.DateCreation.Name = "DateCreation"
        Me.DateCreation.Size = New System.Drawing.Size(100, 20)
        Me.DateCreation.TabIndex = 14
        '
        'DatePay
        '
        Me.DatePay.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.DatePay.Location = New System.Drawing.Point(179, 187)
        Me.DatePay.Name = "DatePay"
        Me.DatePay.Size = New System.Drawing.Size(100, 20)
        Me.DatePay.TabIndex = 4
        '
        'CBIsCOLA
        '
        Me.CBIsCOLA.AutoSize = True
        Me.CBIsCOLA.Location = New System.Drawing.Point(180, 172)
        Me.CBIsCOLA.Name = "CBIsCOLA"
        Me.CBIsCOLA.Size = New System.Drawing.Size(15, 14)
        Me.CBIsCOLA.TabIndex = 16
        Me.CBIsCOLA.UseVisualStyleBackColor = True
        '
        'btnCalculateBasic
        '
        Me.btnCalculateBasic.Location = New System.Drawing.Point(285, 110)
        Me.btnCalculateBasic.Name = "btnCalculateBasic"
        Me.btnCalculateBasic.Size = New System.Drawing.Size(182, 23)
        Me.btnCalculateBasic.TabIndex = 17
        Me.btnCalculateBasic.Text = "Calculate Basic - COLA"
        Me.btnCalculateBasic.UseVisualStyleBackColor = True
        '
        'Button1
        '
        Me.Button1.Location = New System.Drawing.Point(406, 227)
        Me.Button1.Name = "Button1"
        Me.Button1.Size = New System.Drawing.Size(75, 23)
        Me.Button1.TabIndex = 18
        Me.Button1.Text = "Button1"
        Me.Button1.UseVisualStyleBackColor = True
        Me.Button1.Visible = False
        '
        'Label1
        '
        Me.Label1.AutoSize = True
        Me.Label1.Location = New System.Drawing.Point(28, 274)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(52, 13)
        Me.Label1.TabIndex = 20
        Me.Label1.Text = "Unit Rate"
        '
        'txtUnitRate
        '
        Me.txtUnitRate.Location = New System.Drawing.Point(179, 274)
        Me.txtUnitRate.MaxLength = 15
        Me.txtUnitRate.Name = "txtUnitRate"
        Me.txtUnitRate.Size = New System.Drawing.Size(100, 20)
        Me.txtUnitRate.TabIndex = 19
        '
        'Button2
        '
        Me.Button2.Location = New System.Drawing.Point(285, 130)
        Me.Button2.Name = "Button2"
        Me.Button2.Size = New System.Drawing.Size(182, 23)
        Me.Button2.TabIndex = 21
        Me.Button2.Text = "Calculate Salary - COLA"
        Me.Button2.UseVisualStyleBackColor = True
        '
        'Button3
        '
        Me.Button3.Location = New System.Drawing.Point(537, 105)
        Me.Button3.Name = "Button3"
        Me.Button3.Size = New System.Drawing.Size(100, 23)
        Me.Button3.TabIndex = 22
        Me.Button3.Text = "Copy From"
        Me.Button3.UseVisualStyleBackColor = True
        '
        'txtCopyFrom
        '
        Me.txtCopyFrom.Location = New System.Drawing.Point(537, 135)
        Me.txtCopyFrom.Name = "txtCopyFrom"
        Me.txtCopyFrom.Size = New System.Drawing.Size(100, 20)
        Me.txtCopyFrom.TabIndex = 23
        '
        'Button4
        '
        Me.Button4.Location = New System.Drawing.Point(285, 204)
        Me.Button4.Name = "Button4"
        Me.Button4.Size = New System.Drawing.Size(182, 23)
        Me.Button4.TabIndex = 24
        Me.Button4.Text = "Set Arrears Date Same as Pay Date"
        Me.Button4.UseVisualStyleBackColor = True
        '
        'Label6
        '
        Me.Label6.AutoSize = True
        Me.Label6.Location = New System.Drawing.Point(29, 60)
        Me.Label6.Name = "Label6"
        Me.Label6.Size = New System.Drawing.Size(84, 13)
        Me.Label6.TabIndex = 82
        Me.Label6.Text = "Employee Name"
        '
        'txtEmployeeName
        '
        Me.txtEmployeeName.Location = New System.Drawing.Point(149, 61)
        Me.txtEmployeeName.MaxLength = 15
        Me.txtEmployeeName.Name = "txtEmployeeName"
        Me.txtEmployeeName.ReadOnly = True
        Me.txtEmployeeName.Size = New System.Drawing.Size(316, 20)
        Me.txtEmployeeName.TabIndex = 81
        '
        'Label5
        '
        Me.Label5.AutoSize = True
        Me.Label5.Location = New System.Drawing.Point(29, 34)
        Me.Label5.Name = "Label5"
        Me.Label5.Size = New System.Drawing.Size(81, 13)
        Me.Label5.TabIndex = 80
        Me.Label5.Text = "Employee Code"
        '
        'txtEmployeeCode
        '
        Me.txtEmployeeCode.Location = New System.Drawing.Point(149, 35)
        Me.txtEmployeeCode.MaxLength = 15
        Me.txtEmployeeCode.Name = "txtEmployeeCode"
        Me.txtEmployeeCode.ReadOnly = True
        Me.txtEmployeeCode.Size = New System.Drawing.Size(100, 20)
        Me.txtEmployeeCode.TabIndex = 79
        '
        'BtnNext
        '
        Me.BtnNext.Image = CType(resources.GetObject("BtnNext.Image"), System.Drawing.Image)
        Me.BtnNext.Location = New System.Drawing.Point(392, 32)
        Me.BtnNext.Name = "BtnNext"
        Me.BtnNext.Size = New System.Drawing.Size(75, 23)
        Me.BtnNext.TabIndex = 77
        Me.BtnNext.UseVisualStyleBackColor = True
        '
        'BtnPrevius
        '
        Me.BtnPrevius.Image = CType(resources.GetObject("BtnPrevius.Image"), System.Drawing.Image)
        Me.BtnPrevius.Location = New System.Drawing.Point(311, 32)
        Me.BtnPrevius.Name = "BtnPrevius"
        Me.BtnPrevius.Size = New System.Drawing.Size(75, 23)
        Me.BtnPrevius.TabIndex = 78
        Me.BtnPrevius.UseVisualStyleBackColor = True
        '
        'Label2
        '
        Me.Label2.AutoSize = True
        Me.Label2.Location = New System.Drawing.Point(29, 300)
        Me.Label2.Name = "Label2"
        Me.Label2.Size = New System.Drawing.Size(141, 13)
        Me.Label2.TabIndex = 84
        Me.Label2.Text = "Salary 2 for Rate Calculation"
        '
        'txtSalary2ForRate
        '
        Me.txtSalary2ForRate.Location = New System.Drawing.Point(180, 297)
        Me.txtSalary2ForRate.MaxLength = 15
        Me.txtSalary2ForRate.Name = "txtSalary2ForRate"
        Me.txtSalary2ForRate.Size = New System.Drawing.Size(100, 20)
        Me.txtSalary2ForRate.TabIndex = 83
        '
        'frmPrTxEmployeeSalary
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.SystemColors.GradientActiveCaption
        Me.ClientSize = New System.Drawing.Size(746, 619)
        Me.Controls.Add(Me.Label2)
        Me.Controls.Add(Me.txtSalary2ForRate)
        Me.Controls.Add(Me.Label6)
        Me.Controls.Add(Me.txtEmployeeName)
        Me.Controls.Add(Me.Label5)
        Me.Controls.Add(Me.txtEmployeeCode)
        Me.Controls.Add(Me.BtnNext)
        Me.Controls.Add(Me.BtnPrevius)
        Me.Controls.Add(Me.Button4)
        Me.Controls.Add(Me.txtCopyFrom)
        Me.Controls.Add(Me.Button3)
        Me.Controls.Add(Me.Button2)
        Me.Controls.Add(Me.Label1)
        Me.Controls.Add(Me.txtUnitRate)
        Me.Controls.Add(Me.Button1)
        Me.Controls.Add(Me.btnCalculateBasic)
        Me.Controls.Add(Me.CBIsCOLA)
        Me.Controls.Add(Me.DatePay)
        Me.Controls.Add(Me.DateCreation)
        Me.Controls.Add(Me.DateArrears)
        Me.Controls.Add(Me.lblId)
        Me.Controls.Add(Me.txtId)
        Me.Controls.Add(Me.lblDate1)
        Me.Controls.Add(Me.lblSalaryValue)
        Me.Controls.Add(Me.txtSalaryValue)
        Me.Controls.Add(Me.lblBasic)
        Me.Controls.Add(Me.txtBasic)
        Me.Controls.Add(Me.lblEffPayDate)
        Me.Controls.Add(Me.lblCola)
        Me.Controls.Add(Me.txtCola)
        Me.Controls.Add(Me.lblEffArrearsDate)
        Me.Controls.Add(Me.Usr)
        Me.Controls.Add(Me.cmbUsr)
        Me.Controls.Add(Me.lblIsCola)
        Me.Controls.Add(Me.TSC1)
        Me.Controls.Add(Me.sspStatus)
        Me.Controls.Add(Me.DG1)
        Me.Name = "frmPrTxEmployeeSalary"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "Employee Salary"
        Me.sspStatus.ResumeLayout(False)
        Me.sspStatus.PerformLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.TSC1.TopToolStripPanel.ResumeLayout(False)
        Me.TSC1.TopToolStripPanel.PerformLayout()
        Me.TSC1.ResumeLayout(False)
        Me.TSC1.PerformLayout()
        Me.TS1.ResumeLayout(False)
        Me.TS1.PerformLayout()
        CType(Me.ErrId, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEmp_Code, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDate1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrSalaryValue, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrBasic, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEffPayDate, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrCola, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEffArrearsDate, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrUsr_Id, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrIsCola, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
    Friend WithEvents lblId As System.Windows.Forms.Label
    Friend WithEvents txtId As System.Windows.Forms.TextBox
    Friend WithEvents ErrId As System.Windows.Forms.ErrorProvider
    Friend WithEvents ErrEmp_Code As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblDate1 As System.Windows.Forms.Label
    Friend WithEvents ErrDate1 As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblSalaryValue As System.Windows.Forms.Label
    Friend WithEvents txtSalaryValue As System.Windows.Forms.TextBox
    Friend WithEvents ErrSalaryValue As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblBasic As System.Windows.Forms.Label
    Friend WithEvents txtBasic As System.Windows.Forms.TextBox
    Friend WithEvents ErrBasic As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblEffPayDate As System.Windows.Forms.Label
    Friend WithEvents ErrEffPayDate As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblCola As System.Windows.Forms.Label
    Friend WithEvents txtCola As System.Windows.Forms.TextBox
    Friend WithEvents ErrCola As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblEffArrearsDate As System.Windows.Forms.Label
    Friend WithEvents ErrEffArrearsDate As System.Windows.Forms.ErrorProvider
    Friend WithEvents Usr As System.Windows.Forms.Label
    Friend WithEvents cmbUsr As System.Windows.Forms.ComboBox
    Friend WithEvents ErrUsr_Id As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblIsCola As System.Windows.Forms.Label
    Friend WithEvents ErrIsCola As System.Windows.Forms.ErrorProvider
    Friend WithEvents sspStatus As System.Windows.Forms.StatusStrip
    Friend WithEvents lblSSStatus As System.Windows.Forms.ToolStripStatusLabel
    Friend WithEvents DG1 As System.Windows.Forms.DataGridView
    Friend WithEvents TSC1 As System.Windows.Forms.ToolStripContainer
    Friend WithEvents TS1 As System.Windows.Forms.ToolStrip
    Friend WithEvents TSBNew As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBSave As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBDelete As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBExcel As System.Windows.Forms.ToolStripButton
    Friend WithEvents CBIsCOLA As System.Windows.Forms.CheckBox
    Friend WithEvents DatePay As System.Windows.Forms.DateTimePicker
    Friend WithEvents DateCreation As System.Windows.Forms.DateTimePicker
    Friend WithEvents DateArrears As System.Windows.Forms.DateTimePicker
    Friend WithEvents btnCalculateBasic As System.Windows.Forms.Button
    Friend WithEvents BtnCalculateSalaryForCOLA As System.Windows.Forms.ToolStripButton
    Friend WithEvents Button1 As System.Windows.Forms.Button
    Friend WithEvents Label1 As System.Windows.Forms.Label
    Friend WithEvents txtUnitRate As System.Windows.Forms.TextBox
    Friend WithEvents Button2 As System.Windows.Forms.Button
    Friend WithEvents txtCopyFrom As System.Windows.Forms.TextBox
    Friend WithEvents Button3 As System.Windows.Forms.Button
    Friend WithEvents Button4 As System.Windows.Forms.Button
    Friend WithEvents Label6 As System.Windows.Forms.Label
    Friend WithEvents txtEmployeeName As System.Windows.Forms.TextBox
    Friend WithEvents Label5 As System.Windows.Forms.Label
    Friend WithEvents txtEmployeeCode As System.Windows.Forms.TextBox
    Friend WithEvents BtnNext As System.Windows.Forms.Button
    Friend WithEvents BtnPrevius As System.Windows.Forms.Button
    Friend WithEvents Label2 As System.Windows.Forms.Label
    Friend WithEvents txtSalary2ForRate As System.Windows.Forms.TextBox
    Friend WithEvents dgcEmpSal_id As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmp_Code As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpSal_Date As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpSal_Value As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpSal_Basic As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpSal_Cola As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpSal_IsCola As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpSal_EffPayDate As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcUsr_Id As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpSal_EffArrearsDate As System.Windows.Forms.DataGridViewTextBoxColumn
End Class
