<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmPrAnEmployeeAnalysis3
Inherits System.Windows.Forms.Form
<System.Diagnostics.DebuggerNonUserCode()> _
Protected Overrides Sub Dispose(ByVal disposing As Boolean)
If Disposing AndAlso components IsNot Nothing Then
components.Dispose()
End If
MyBase.Dispose(Disposing)
End Sub
Private components As System.ComponentModel.IContainer
' AutoGenerated Form by Nodalsoft
<System.Diagnostics.DebuggerStepThrough()> _
Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container
        Dim DataGridViewCellStyle1 As System.Windows.Forms.DataGridViewCellStyle = New System.Windows.Forms.DataGridViewCellStyle
        Dim DataGridViewCellStyle2 As System.Windows.Forms.DataGridViewCellStyle = New System.Windows.Forms.DataGridViewCellStyle
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmPrAnEmployeeAnalysis3))
        Me.sspStatus = New System.Windows.Forms.StatusStrip
        Me.lblSSStatus = New System.Windows.Forms.ToolStripStatusLabel
        Me.DG1 = New System.Windows.Forms.DataGridView
        Me.dgcEmpAn3_Code = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmpAn3_DescriptionL = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmpAn3_DescriptionS = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmpAn3_IsActive = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmpAn3_GLAnal1 = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmpAn3_GLAnal2 = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmpAn3_CreationDate = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcEmpAn3_AmendDate = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.TSC1 = New System.Windows.Forms.ToolStripContainer
        Me.TS1 = New System.Windows.Forms.ToolStrip
        Me.TSBNew = New System.Windows.Forms.ToolStripButton
        Me.TSBSave = New System.Windows.Forms.ToolStripButton
        Me.TSBDelete = New System.Windows.Forms.ToolStripButton
        Me.TSBExcel = New System.Windows.Forms.ToolStripButton
        Me.lblCode = New System.Windows.Forms.Label
        Me.txtCode = New System.Windows.Forms.TextBox
        Me.ErrCode = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDescriptionL = New System.Windows.Forms.Label
        Me.txtDescriptionL = New System.Windows.Forms.TextBox
        Me.ErrDescriptionL = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDescriptionS = New System.Windows.Forms.Label
        Me.txtDescriptionS = New System.Windows.Forms.TextBox
        Me.ErrDescriptionS = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblIsActive = New System.Windows.Forms.Label
        Me.ErrIsActive = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblGLAnal1 = New System.Windows.Forms.Label
        Me.txtGLAnal1 = New System.Windows.Forms.TextBox
        Me.ErrGLAnal1 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblGLAnal2 = New System.Windows.Forms.Label
        Me.txtGLAnal2 = New System.Windows.Forms.TextBox
        Me.ErrGLAnal2 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblCreationDate = New System.Windows.Forms.Label
        Me.ErrCreationDate = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblAmendDate = New System.Windows.Forms.Label
        Me.ErrAmendDate = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.CBIsActive = New System.Windows.Forms.CheckBox
        Me.DateCreated = New System.Windows.Forms.DateTimePicker
        Me.DateAmend = New System.Windows.Forms.DateTimePicker
        Me.Button1 = New System.Windows.Forms.Button
        Me.sspStatus.SuspendLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.TSC1.TopToolStripPanel.SuspendLayout()
        Me.TSC1.SuspendLayout()
        Me.TS1.SuspendLayout()
        CType(Me.ErrCode, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDescriptionL, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDescriptionS, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrIsActive, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrGLAnal1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrGLAnal2, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrCreationDate, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrAmendDate, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'sspStatus
        '
        Me.sspStatus.BackColor = System.Drawing.SystemColors.Control
        Me.sspStatus.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.lblSSStatus})
        Me.sspStatus.Location = New System.Drawing.Point(0, 529)
        Me.sspStatus.Name = "sspStatus"
        Me.sspStatus.Size = New System.Drawing.Size(987, 22)
        Me.sspStatus.TabIndex = 3
        Me.sspStatus.Text = "StatusStrip"
        '
        'lblSSStatus
        '
        Me.lblSSStatus.Name = "lblSSStatus"
        Me.lblSSStatus.Size = New System.Drawing.Size(0, 17)
        '
        'DG1
        '
        Me.DG1.AllowUserToAddRows = False
        Me.DG1.AllowUserToDeleteRows = False
        Me.DG1.BackgroundColor = System.Drawing.SystemColors.Window
        Me.DG1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DG1.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.dgcEmpAn3_Code, Me.dgcEmpAn3_DescriptionL, Me.dgcEmpAn3_DescriptionS, Me.dgcEmpAn3_IsActive, Me.dgcEmpAn3_GLAnal1, Me.dgcEmpAn3_GLAnal2, Me.dgcEmpAn3_CreationDate, Me.dgcEmpAn3_AmendDate})
        Me.DG1.Location = New System.Drawing.Point(12, 226)
        Me.DG1.Name = "DG1"
        Me.DG1.ReadOnly = True
        Me.DG1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
        Me.DG1.Size = New System.Drawing.Size(963, 290)
        Me.DG1.TabIndex = 10
        '
        'dgcEmpAn3_Code
        '
        Me.dgcEmpAn3_Code.DataPropertyName = "EmpAn3_Code"
        Me.dgcEmpAn3_Code.FillWeight = 150.0!
        Me.dgcEmpAn3_Code.HeaderText = "Code"
        Me.dgcEmpAn3_Code.Name = "dgcEmpAn3_Code"
        Me.dgcEmpAn3_Code.ReadOnly = True
        Me.dgcEmpAn3_Code.Width = 82
        '
        'dgcEmpAn3_DescriptionL
        '
        Me.dgcEmpAn3_DescriptionL.DataPropertyName = "EmpAn3_DescriptionL"
        Me.dgcEmpAn3_DescriptionL.FillWeight = 150.0!
        Me.dgcEmpAn3_DescriptionL.HeaderText = "Long Description"
        Me.dgcEmpAn3_DescriptionL.Name = "dgcEmpAn3_DescriptionL"
        Me.dgcEmpAn3_DescriptionL.ReadOnly = True
        Me.dgcEmpAn3_DescriptionL.Width = 250
        '
        'dgcEmpAn3_DescriptionS
        '
        Me.dgcEmpAn3_DescriptionS.DataPropertyName = "EmpAn3_DescriptionS"
        Me.dgcEmpAn3_DescriptionS.FillWeight = 150.0!
        Me.dgcEmpAn3_DescriptionS.HeaderText = "Short Description"
        Me.dgcEmpAn3_DescriptionS.Name = "dgcEmpAn3_DescriptionS"
        Me.dgcEmpAn3_DescriptionS.ReadOnly = True
        '
        'dgcEmpAn3_IsActive
        '
        Me.dgcEmpAn3_IsActive.DataPropertyName = "EmpAn3_IsActive"
        Me.dgcEmpAn3_IsActive.FillWeight = 150.0!
        Me.dgcEmpAn3_IsActive.HeaderText = "Is Active"
        Me.dgcEmpAn3_IsActive.Name = "dgcEmpAn3_IsActive"
        Me.dgcEmpAn3_IsActive.ReadOnly = True
        Me.dgcEmpAn3_IsActive.Width = 60
        '
        'dgcEmpAn3_GLAnal1
        '
        Me.dgcEmpAn3_GLAnal1.DataPropertyName = "EmpAn3_GLAnal1"
        Me.dgcEmpAn3_GLAnal1.FillWeight = 150.0!
        Me.dgcEmpAn3_GLAnal1.HeaderText = "GLAnal1"
        Me.dgcEmpAn3_GLAnal1.Name = "dgcEmpAn3_GLAnal1"
        Me.dgcEmpAn3_GLAnal1.ReadOnly = True
        Me.dgcEmpAn3_GLAnal1.Width = 82
        '
        'dgcEmpAn3_GLAnal2
        '
        Me.dgcEmpAn3_GLAnal2.DataPropertyName = "EmpAn3_GLAnal2"
        Me.dgcEmpAn3_GLAnal2.FillWeight = 150.0!
        Me.dgcEmpAn3_GLAnal2.HeaderText = "GLAnal2"
        Me.dgcEmpAn3_GLAnal2.Name = "dgcEmpAn3_GLAnal2"
        Me.dgcEmpAn3_GLAnal2.ReadOnly = True
        Me.dgcEmpAn3_GLAnal2.Width = 82
        '
        'dgcEmpAn3_CreationDate
        '
        Me.dgcEmpAn3_CreationDate.DataPropertyName = "EmpAn3_CreationDate"
        DataGridViewCellStyle1.Format = "dd-MM-yyyy"
        Me.dgcEmpAn3_CreationDate.DefaultCellStyle = DataGridViewCellStyle1
        Me.dgcEmpAn3_CreationDate.FillWeight = 150.0!
        Me.dgcEmpAn3_CreationDate.HeaderText = "Creation Date"
        Me.dgcEmpAn3_CreationDate.Name = "dgcEmpAn3_CreationDate"
        Me.dgcEmpAn3_CreationDate.ReadOnly = True
        Me.dgcEmpAn3_CreationDate.Width = 70
        '
        'dgcEmpAn3_AmendDate
        '
        Me.dgcEmpAn3_AmendDate.DataPropertyName = "EmpAn3_AmendDate"
        DataGridViewCellStyle2.Format = "dd-MM-yyyy"
        Me.dgcEmpAn3_AmendDate.DefaultCellStyle = DataGridViewCellStyle2
        Me.dgcEmpAn3_AmendDate.FillWeight = 150.0!
        Me.dgcEmpAn3_AmendDate.HeaderText = "Amend Date"
        Me.dgcEmpAn3_AmendDate.Name = "dgcEmpAn3_AmendDate"
        Me.dgcEmpAn3_AmendDate.ReadOnly = True
        Me.dgcEmpAn3_AmendDate.Width = 70
        '
        'TSC1
        '
        Me.TSC1.BottomToolStripPanelVisible = False
        '
        'TSC1.ContentPanel
        '
        Me.TSC1.ContentPanel.Size = New System.Drawing.Size(987, 1)
        Me.TSC1.Dock = System.Windows.Forms.DockStyle.Top
        Me.TSC1.LeftToolStripPanelVisible = False
        Me.TSC1.Location = New System.Drawing.Point(0, 0)
        Me.TSC1.Name = "TSC1"
        Me.TSC1.RightToolStripPanelVisible = False
        Me.TSC1.Size = New System.Drawing.Size(987, 26)
        Me.TSC1.TabIndex = 12
        Me.TSC1.Text = "TSC1"
        '
        'TSC1.TopToolStripPanel
        '
        Me.TSC1.TopToolStripPanel.Controls.Add(Me.TS1)
        '
        'TS1
        '
        Me.TS1.Dock = System.Windows.Forms.DockStyle.None
        Me.TS1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.TSBNew, Me.TSBSave, Me.TSBDelete, Me.TSBExcel})
        Me.TS1.Location = New System.Drawing.Point(3, 0)
        Me.TS1.Name = "TS1"
        Me.TS1.Size = New System.Drawing.Size(252, 25)
        Me.TS1.TabIndex = 0
        '
        'TSBNew
        '
        Me.TSBNew.AutoSize = False
        Me.TSBNew.Image = CType(resources.GetObject("TSBNew.Image"), System.Drawing.Image)
        Me.TSBNew.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBNew.Name = "TSBNew"
        Me.TSBNew.Size = New System.Drawing.Size(60, 22)
        Me.TSBNew.Text = "New"
        Me.TSBNew.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBSave
        '
        Me.TSBSave.AutoSize = False
        Me.TSBSave.Image = CType(resources.GetObject("TSBSave.Image"), System.Drawing.Image)
        Me.TSBSave.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBSave.Name = "TSBSave"
        Me.TSBSave.Size = New System.Drawing.Size(60, 22)
        Me.TSBSave.Text = "Save"
        Me.TSBSave.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBDelete
        '
        Me.TSBDelete.AutoSize = False
        Me.TSBDelete.Image = CType(resources.GetObject("TSBDelete.Image"), System.Drawing.Image)
        Me.TSBDelete.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBDelete.Name = "TSBDelete"
        Me.TSBDelete.Size = New System.Drawing.Size(60, 22)
        Me.TSBDelete.Text = "Delete"
        Me.TSBDelete.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBExcel
        '
        Me.TSBExcel.AutoSize = False
        Me.TSBExcel.Image = Global.NodalPay.My.Resources.Resources.excel
        Me.TSBExcel.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBExcel.Name = "TSBExcel"
        Me.TSBExcel.Size = New System.Drawing.Size(60, 22)
        Me.TSBExcel.Text = "Excel"
        Me.TSBExcel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'lblCode
        '
        Me.lblCode.AutoSize = True
        Me.lblCode.Location = New System.Drawing.Point(37, 40)
        Me.lblCode.Name = "lblCode"
        Me.lblCode.Size = New System.Drawing.Size(32, 13)
        Me.lblCode.TabIndex = 0
        Me.lblCode.Text = "Code"
        '
        'txtCode
        '
        Me.txtCode.Location = New System.Drawing.Point(157, 40)
        Me.txtCode.MaxLength = 12
        Me.txtCode.Name = "txtCode"
        Me.txtCode.Size = New System.Drawing.Size(82, 20)
        Me.txtCode.TabIndex = 1
        '
        'ErrCode
        '
        Me.ErrCode.ContainerControl = Me
        '
        'lblDescriptionL
        '
        Me.lblDescriptionL.AutoSize = True
        Me.lblDescriptionL.Location = New System.Drawing.Point(37, 60)
        Me.lblDescriptionL.Name = "lblDescriptionL"
        Me.lblDescriptionL.Size = New System.Drawing.Size(87, 13)
        Me.lblDescriptionL.TabIndex = 2
        Me.lblDescriptionL.Text = "Long Description"
        '
        'txtDescriptionL
        '
        Me.txtDescriptionL.Location = New System.Drawing.Point(157, 60)
        Me.txtDescriptionL.MaxLength = 40
        Me.txtDescriptionL.Name = "txtDescriptionL"
        Me.txtDescriptionL.Size = New System.Drawing.Size(250, 20)
        Me.txtDescriptionL.TabIndex = 2
        '
        'ErrDescriptionL
        '
        Me.ErrDescriptionL.ContainerControl = Me
        '
        'lblDescriptionS
        '
        Me.lblDescriptionS.AutoSize = True
        Me.lblDescriptionS.Location = New System.Drawing.Point(37, 80)
        Me.lblDescriptionS.Name = "lblDescriptionS"
        Me.lblDescriptionS.Size = New System.Drawing.Size(88, 13)
        Me.lblDescriptionS.TabIndex = 3
        Me.lblDescriptionS.Text = "Short Description"
        '
        'txtDescriptionS
        '
        Me.txtDescriptionS.Location = New System.Drawing.Point(157, 80)
        Me.txtDescriptionS.MaxLength = 15
        Me.txtDescriptionS.Name = "txtDescriptionS"
        Me.txtDescriptionS.Size = New System.Drawing.Size(100, 20)
        Me.txtDescriptionS.TabIndex = 3
        '
        'ErrDescriptionS
        '
        Me.ErrDescriptionS.ContainerControl = Me
        '
        'lblIsActive
        '
        Me.lblIsActive.AutoSize = True
        Me.lblIsActive.Location = New System.Drawing.Point(37, 100)
        Me.lblIsActive.Name = "lblIsActive"
        Me.lblIsActive.Size = New System.Drawing.Size(48, 13)
        Me.lblIsActive.TabIndex = 4
        Me.lblIsActive.Text = "Is Active"
        '
        'ErrIsActive
        '
        Me.ErrIsActive.ContainerControl = Me
        '
        'lblGLAnal1
        '
        Me.lblGLAnal1.AutoSize = True
        Me.lblGLAnal1.Location = New System.Drawing.Point(37, 120)
        Me.lblGLAnal1.Name = "lblGLAnal1"
        Me.lblGLAnal1.Size = New System.Drawing.Size(48, 13)
        Me.lblGLAnal1.TabIndex = 5
        Me.lblGLAnal1.Text = "GLAnal1"
        '
        'txtGLAnal1
        '
        Me.txtGLAnal1.Location = New System.Drawing.Point(157, 120)
        Me.txtGLAnal1.MaxLength = 12
        Me.txtGLAnal1.Name = "txtGLAnal1"
        Me.txtGLAnal1.Size = New System.Drawing.Size(82, 20)
        Me.txtGLAnal1.TabIndex = 5
        '
        'ErrGLAnal1
        '
        Me.ErrGLAnal1.ContainerControl = Me
        '
        'lblGLAnal2
        '
        Me.lblGLAnal2.AutoSize = True
        Me.lblGLAnal2.Location = New System.Drawing.Point(37, 140)
        Me.lblGLAnal2.Name = "lblGLAnal2"
        Me.lblGLAnal2.Size = New System.Drawing.Size(48, 13)
        Me.lblGLAnal2.TabIndex = 6
        Me.lblGLAnal2.Text = "GLAnal2"
        '
        'txtGLAnal2
        '
        Me.txtGLAnal2.Location = New System.Drawing.Point(157, 140)
        Me.txtGLAnal2.MaxLength = 12
        Me.txtGLAnal2.Name = "txtGLAnal2"
        Me.txtGLAnal2.Size = New System.Drawing.Size(82, 20)
        Me.txtGLAnal2.TabIndex = 6
        '
        'ErrGLAnal2
        '
        Me.ErrGLAnal2.ContainerControl = Me
        '
        'lblCreationDate
        '
        Me.lblCreationDate.AutoSize = True
        Me.lblCreationDate.Location = New System.Drawing.Point(37, 160)
        Me.lblCreationDate.Name = "lblCreationDate"
        Me.lblCreationDate.Size = New System.Drawing.Size(72, 13)
        Me.lblCreationDate.TabIndex = 7
        Me.lblCreationDate.Text = "Creation Date"
        '
        'ErrCreationDate
        '
        Me.ErrCreationDate.ContainerControl = Me
        '
        'lblAmendDate
        '
        Me.lblAmendDate.AutoSize = True
        Me.lblAmendDate.Location = New System.Drawing.Point(37, 180)
        Me.lblAmendDate.Name = "lblAmendDate"
        Me.lblAmendDate.Size = New System.Drawing.Size(66, 13)
        Me.lblAmendDate.TabIndex = 8
        Me.lblAmendDate.Text = "Amend Date"
        '
        'ErrAmendDate
        '
        Me.ErrAmendDate.ContainerControl = Me
        '
        'CBIsActive
        '
        Me.CBIsActive.AutoSize = True
        Me.CBIsActive.Location = New System.Drawing.Point(157, 102)
        Me.CBIsActive.Name = "CBIsActive"
        Me.CBIsActive.Size = New System.Drawing.Size(15, 14)
        Me.CBIsActive.TabIndex = 13
        Me.CBIsActive.UseVisualStyleBackColor = True
        '
        'DateCreated
        '
        Me.DateCreated.Enabled = False
        Me.DateCreated.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.DateCreated.Location = New System.Drawing.Point(157, 160)
        Me.DateCreated.Name = "DateCreated"
        Me.DateCreated.Size = New System.Drawing.Size(100, 20)
        Me.DateCreated.TabIndex = 14
        '
        'DateAmend
        '
        Me.DateAmend.Enabled = False
        Me.DateAmend.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.DateAmend.Location = New System.Drawing.Point(157, 180)
        Me.DateAmend.Name = "DateAmend"
        Me.DateAmend.Size = New System.Drawing.Size(100, 20)
        Me.DateAmend.TabIndex = 15
        '
        'Button1
        '
        Me.Button1.Location = New System.Drawing.Point(638, 65)
        Me.Button1.Name = "Button1"
        Me.Button1.Size = New System.Drawing.Size(75, 23)
        Me.Button1.TabIndex = 16
        Me.Button1.Text = "Button1"
        Me.Button1.UseVisualStyleBackColor = True
        Me.Button1.Visible = False
        '
        'frmPrAnEmployeeAnalysis3
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.SystemColors.GradientActiveCaption
        Me.ClientSize = New System.Drawing.Size(987, 551)
        Me.Controls.Add(Me.Button1)
        Me.Controls.Add(Me.DateAmend)
        Me.Controls.Add(Me.DateCreated)
        Me.Controls.Add(Me.CBIsActive)
        Me.Controls.Add(Me.lblCode)
        Me.Controls.Add(Me.txtCode)
        Me.Controls.Add(Me.lblDescriptionL)
        Me.Controls.Add(Me.txtDescriptionL)
        Me.Controls.Add(Me.lblDescriptionS)
        Me.Controls.Add(Me.txtDescriptionS)
        Me.Controls.Add(Me.lblIsActive)
        Me.Controls.Add(Me.lblGLAnal1)
        Me.Controls.Add(Me.txtGLAnal1)
        Me.Controls.Add(Me.lblGLAnal2)
        Me.Controls.Add(Me.txtGLAnal2)
        Me.Controls.Add(Me.lblCreationDate)
        Me.Controls.Add(Me.lblAmendDate)
        Me.Controls.Add(Me.TSC1)
        Me.Controls.Add(Me.sspStatus)
        Me.Controls.Add(Me.DG1)
        Me.Name = "frmPrAnEmployeeAnalysis3"
        Me.Text = "Employee Analysis 3"
        Me.sspStatus.ResumeLayout(False)
        Me.sspStatus.PerformLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.TSC1.TopToolStripPanel.ResumeLayout(False)
        Me.TSC1.TopToolStripPanel.PerformLayout()
        Me.TSC1.ResumeLayout(False)
        Me.TSC1.PerformLayout()
        Me.TS1.ResumeLayout(False)
        Me.TS1.PerformLayout()
        CType(Me.ErrCode, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDescriptionL, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDescriptionS, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrIsActive, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrGLAnal1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrGLAnal2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrCreationDate, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrAmendDate, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
    Friend WithEvents lblCode As System.Windows.Forms.Label
    Friend WithEvents txtCode As System.Windows.Forms.TextBox
    Friend WithEvents ErrCode As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblDescriptionL As System.Windows.Forms.Label
    Friend WithEvents txtDescriptionL As System.Windows.Forms.TextBox
    Friend WithEvents ErrDescriptionL As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblDescriptionS As System.Windows.Forms.Label
    Friend WithEvents txtDescriptionS As System.Windows.Forms.TextBox
    Friend WithEvents ErrDescriptionS As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblIsActive As System.Windows.Forms.Label
    Friend WithEvents ErrIsActive As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblGLAnal1 As System.Windows.Forms.Label
    Friend WithEvents txtGLAnal1 As System.Windows.Forms.TextBox
    Friend WithEvents ErrGLAnal1 As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblGLAnal2 As System.Windows.Forms.Label
    Friend WithEvents txtGLAnal2 As System.Windows.Forms.TextBox
    Friend WithEvents ErrGLAnal2 As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblCreationDate As System.Windows.Forms.Label
    Friend WithEvents ErrCreationDate As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblAmendDate As System.Windows.Forms.Label
    Friend WithEvents ErrAmendDate As System.Windows.Forms.ErrorProvider
    Friend WithEvents sspStatus As System.Windows.Forms.StatusStrip
    Friend WithEvents lblSSStatus As System.Windows.Forms.ToolStripStatusLabel
    Friend WithEvents DG1 As System.Windows.Forms.DataGridView
    Friend WithEvents TSC1 As System.Windows.Forms.ToolStripContainer
    Friend WithEvents TS1 As System.Windows.Forms.ToolStrip
    Friend WithEvents TSBNew As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBSave As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBDelete As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBExcel As System.Windows.Forms.ToolStripButton
    Friend WithEvents CBIsActive As System.Windows.Forms.CheckBox
    Friend WithEvents DateAmend As System.Windows.Forms.DateTimePicker
    Friend WithEvents DateCreated As System.Windows.Forms.DateTimePicker
    Friend WithEvents dgcEmpAn3_Code As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpAn3_DescriptionL As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpAn3_DescriptionS As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpAn3_IsActive As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpAn3_GLAnal1 As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpAn3_GLAnal2 As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpAn3_CreationDate As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpAn3_AmendDate As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents Button1 As System.Windows.Forms.Button
End Class
