<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmAaSsUsers
Inherits System.Windows.Forms.Form
<System.Diagnostics.DebuggerNonUserCode()> _
Protected Overrides Sub Dispose(ByVal disposing As Boolean)
If Disposing AndAlso components IsNot Nothing Then
components.Dispose()
End If
MyBase.Dispose(Disposing)
End Sub
Private components As System.ComponentModel.IContainer
' AutoGenerated Form by Nodalsoft
<System.Diagnostics.DebuggerStepThrough()> _
Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container
        Dim DataGridViewCellStyle1 As System.Windows.Forms.DataGridViewCellStyle = New System.Windows.Forms.DataGridViewCellStyle
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmAaSsUsers))
        Me.sspStatus = New System.Windows.Forms.StatusStrip
        Me.lblSSStatus = New System.Windows.Forms.ToolStripStatusLabel
        Me.DG1 = New System.Windows.Forms.DataGridView
        Me.dgcUsr_Id = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcUsr_UserName = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcUsr_FullName = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcUsr_CreatedOn = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcUsr_IsEnabled = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcUsr_IsSA = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcUsr_MyRole = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.TSC1 = New System.Windows.Forms.ToolStripContainer
        Me.TS1 = New System.Windows.Forms.ToolStrip
        Me.TSBNew = New System.Windows.Forms.ToolStripButton
        Me.TSBSave = New System.Windows.Forms.ToolStripButton
        Me.TSBDelete = New System.Windows.Forms.ToolStripButton
        Me.TSBExcel = New System.Windows.Forms.ToolStripButton
        Me.lblId = New System.Windows.Forms.Label
        Me.txtId = New System.Windows.Forms.TextBox
        Me.ErrId = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblUserName = New System.Windows.Forms.Label
        Me.txtUserName = New System.Windows.Forms.TextBox
        Me.ErrUserName = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblFullName = New System.Windows.Forms.Label
        Me.txtFullName = New System.Windows.Forms.TextBox
        Me.ErrFullName = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblCreatedOn = New System.Windows.Forms.Label
        Me.ErrCreatedOn = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblIsEnabled = New System.Windows.Forms.Label
        Me.ErrIsEnabled = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblIsSA = New System.Windows.Forms.Label
        Me.ErrIsSA = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblMyRole = New System.Windows.Forms.Label
        Me.txtMyRole = New System.Windows.Forms.TextBox
        Me.ErrMyRole = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.CBIsEnabled = New System.Windows.Forms.CheckBox
        Me.CBIsSA = New System.Windows.Forms.CheckBox
        Me.DateCreated = New System.Windows.Forms.DateTimePicker
        Me.Button1 = New System.Windows.Forms.Button
        Me.txtDBPass = New System.Windows.Forms.TextBox
        Me.Label1 = New System.Windows.Forms.Label
        Me.txtDBUser = New System.Windows.Forms.TextBox
        Me.Label3 = New System.Windows.Forms.Label
        Me.Button2 = New System.Windows.Forms.Button
        Me.Label2 = New System.Windows.Forms.Label
        Me.txtDBPass2 = New System.Windows.Forms.TextBox
        Me.sspStatus.SuspendLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.TSC1.TopToolStripPanel.SuspendLayout()
        Me.TSC1.SuspendLayout()
        Me.TS1.SuspendLayout()
        CType(Me.ErrId, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrUserName, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrFullName, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrCreatedOn, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrIsEnabled, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrIsSA, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrMyRole, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'sspStatus
        '
        Me.sspStatus.BackColor = System.Drawing.SystemColors.Control
        Me.sspStatus.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.lblSSStatus})
        Me.sspStatus.Location = New System.Drawing.Point(0, 529)
        Me.sspStatus.Name = "sspStatus"
        Me.sspStatus.Size = New System.Drawing.Size(987, 22)
        Me.sspStatus.TabIndex = 3
        Me.sspStatus.Text = "StatusStrip"
        '
        'lblSSStatus
        '
        Me.lblSSStatus.Name = "lblSSStatus"
        Me.lblSSStatus.Size = New System.Drawing.Size(0, 17)
        '
        'DG1
        '
        Me.DG1.AllowUserToAddRows = False
        Me.DG1.AllowUserToDeleteRows = False
        Me.DG1.BackgroundColor = System.Drawing.SystemColors.Window
        Me.DG1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DG1.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.dgcUsr_Id, Me.dgcUsr_UserName, Me.dgcUsr_FullName, Me.dgcUsr_CreatedOn, Me.dgcUsr_IsEnabled, Me.dgcUsr_IsSA, Me.dgcUsr_MyRole})
        Me.DG1.Location = New System.Drawing.Point(12, 196)
        Me.DG1.Name = "DG1"
        Me.DG1.ReadOnly = True
        Me.DG1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
        Me.DG1.Size = New System.Drawing.Size(963, 320)
        Me.DG1.TabIndex = 10
        '
        'dgcUsr_Id
        '
        Me.dgcUsr_Id.DataPropertyName = "Usr_Id"
        Me.dgcUsr_Id.FillWeight = 150.0!
        Me.dgcUsr_Id.HeaderText = "Id"
        Me.dgcUsr_Id.Name = "dgcUsr_Id"
        Me.dgcUsr_Id.ReadOnly = True
        Me.dgcUsr_Id.Width = 64
        '
        'dgcUsr_UserName
        '
        Me.dgcUsr_UserName.DataPropertyName = "Usr_UserName"
        Me.dgcUsr_UserName.FillWeight = 150.0!
        Me.dgcUsr_UserName.HeaderText = "User Name"
        Me.dgcUsr_UserName.Name = "dgcUsr_UserName"
        Me.dgcUsr_UserName.ReadOnly = True
        Me.dgcUsr_UserName.Width = 70
        '
        'dgcUsr_FullName
        '
        Me.dgcUsr_FullName.DataPropertyName = "Usr_FullName"
        Me.dgcUsr_FullName.FillWeight = 150.0!
        Me.dgcUsr_FullName.HeaderText = "Full Name"
        Me.dgcUsr_FullName.Name = "dgcUsr_FullName"
        Me.dgcUsr_FullName.ReadOnly = True
        Me.dgcUsr_FullName.Width = 310
        '
        'dgcUsr_CreatedOn
        '
        Me.dgcUsr_CreatedOn.DataPropertyName = "Usr_CreatedOn"
        DataGridViewCellStyle1.Format = "dd-MM-yyyy"
        DataGridViewCellStyle1.NullValue = Nothing
        Me.dgcUsr_CreatedOn.DefaultCellStyle = DataGridViewCellStyle1
        Me.dgcUsr_CreatedOn.FillWeight = 150.0!
        Me.dgcUsr_CreatedOn.HeaderText = "Created On"
        Me.dgcUsr_CreatedOn.Name = "dgcUsr_CreatedOn"
        Me.dgcUsr_CreatedOn.ReadOnly = True
        Me.dgcUsr_CreatedOn.Width = 70
        '
        'dgcUsr_IsEnabled
        '
        Me.dgcUsr_IsEnabled.DataPropertyName = "Usr_IsEnabled"
        Me.dgcUsr_IsEnabled.FillWeight = 150.0!
        Me.dgcUsr_IsEnabled.HeaderText = "Is Enabled"
        Me.dgcUsr_IsEnabled.Name = "dgcUsr_IsEnabled"
        Me.dgcUsr_IsEnabled.ReadOnly = True
        Me.dgcUsr_IsEnabled.Width = 60
        '
        'dgcUsr_IsSA
        '
        Me.dgcUsr_IsSA.DataPropertyName = "Usr_IsSA"
        Me.dgcUsr_IsSA.FillWeight = 150.0!
        Me.dgcUsr_IsSA.HeaderText = "Is SA"
        Me.dgcUsr_IsSA.Name = "dgcUsr_IsSA"
        Me.dgcUsr_IsSA.ReadOnly = True
        Me.dgcUsr_IsSA.Width = 60
        '
        'dgcUsr_MyRole
        '
        Me.dgcUsr_MyRole.DataPropertyName = "Usr_MyRole"
        Me.dgcUsr_MyRole.FillWeight = 150.0!
        Me.dgcUsr_MyRole.HeaderText = "MyRole"
        Me.dgcUsr_MyRole.Name = "dgcUsr_MyRole"
        Me.dgcUsr_MyRole.ReadOnly = True
        Me.dgcUsr_MyRole.Width = 64
        '
        'TSC1
        '
        Me.TSC1.BottomToolStripPanelVisible = False
        '
        'TSC1.ContentPanel
        '
        Me.TSC1.ContentPanel.Size = New System.Drawing.Size(987, 1)
        Me.TSC1.Dock = System.Windows.Forms.DockStyle.Top
        Me.TSC1.LeftToolStripPanelVisible = False
        Me.TSC1.Location = New System.Drawing.Point(0, 0)
        Me.TSC1.Name = "TSC1"
        Me.TSC1.RightToolStripPanelVisible = False
        Me.TSC1.Size = New System.Drawing.Size(987, 26)
        Me.TSC1.TabIndex = 12
        Me.TSC1.Text = "TSC1"
        '
        'TSC1.TopToolStripPanel
        '
        Me.TSC1.TopToolStripPanel.Controls.Add(Me.TS1)
        '
        'TS1
        '
        Me.TS1.Dock = System.Windows.Forms.DockStyle.None
        Me.TS1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.TSBNew, Me.TSBSave, Me.TSBDelete, Me.TSBExcel})
        Me.TS1.Location = New System.Drawing.Point(3, 0)
        Me.TS1.Name = "TS1"
        Me.TS1.Size = New System.Drawing.Size(252, 25)
        Me.TS1.TabIndex = 0
        '
        'TSBNew
        '
        Me.TSBNew.AutoSize = False
        Me.TSBNew.Image = CType(resources.GetObject("TSBNew.Image"), System.Drawing.Image)
        Me.TSBNew.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBNew.Name = "TSBNew"
        Me.TSBNew.Size = New System.Drawing.Size(60, 22)
        Me.TSBNew.Text = "New"
        Me.TSBNew.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBSave
        '
        Me.TSBSave.AutoSize = False
        Me.TSBSave.Image = CType(resources.GetObject("TSBSave.Image"), System.Drawing.Image)
        Me.TSBSave.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBSave.Name = "TSBSave"
        Me.TSBSave.Size = New System.Drawing.Size(60, 22)
        Me.TSBSave.Text = "Save"
        Me.TSBSave.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBDelete
        '
        Me.TSBDelete.AutoSize = False
        Me.TSBDelete.Image = CType(resources.GetObject("TSBDelete.Image"), System.Drawing.Image)
        Me.TSBDelete.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBDelete.Name = "TSBDelete"
        Me.TSBDelete.Size = New System.Drawing.Size(60, 22)
        Me.TSBDelete.Text = "Delete"
        Me.TSBDelete.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBExcel
        '
        Me.TSBExcel.AutoSize = False
        Me.TSBExcel.Image = Global.NodalPay.My.Resources.Resources.excel
        Me.TSBExcel.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBExcel.Name = "TSBExcel"
        Me.TSBExcel.Size = New System.Drawing.Size(60, 22)
        Me.TSBExcel.Text = "Excel"
        Me.TSBExcel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'lblId
        '
        Me.lblId.AutoSize = True
        Me.lblId.Location = New System.Drawing.Point(37, 40)
        Me.lblId.Name = "lblId"
        Me.lblId.Size = New System.Drawing.Size(16, 13)
        Me.lblId.TabIndex = 0
        Me.lblId.Text = "Id"
        '
        'txtId
        '
        Me.txtId.Enabled = False
        Me.txtId.Location = New System.Drawing.Point(157, 40)
        Me.txtId.MaxLength = 9
        Me.txtId.Name = "txtId"
        Me.txtId.Size = New System.Drawing.Size(70, 20)
        Me.txtId.TabIndex = 1
        '
        'ErrId
        '
        Me.ErrId.ContainerControl = Me
        '
        'lblUserName
        '
        Me.lblUserName.AutoSize = True
        Me.lblUserName.Location = New System.Drawing.Point(37, 60)
        Me.lblUserName.Name = "lblUserName"
        Me.lblUserName.Size = New System.Drawing.Size(60, 13)
        Me.lblUserName.TabIndex = 2
        Me.lblUserName.Text = "User Name"
        '
        'txtUserName
        '
        Me.txtUserName.Location = New System.Drawing.Point(157, 60)
        Me.txtUserName.MaxLength = 10
        Me.txtUserName.Name = "txtUserName"
        Me.txtUserName.Size = New System.Drawing.Size(70, 20)
        Me.txtUserName.TabIndex = 2
        '
        'ErrUserName
        '
        Me.ErrUserName.ContainerControl = Me
        '
        'lblFullName
        '
        Me.lblFullName.AutoSize = True
        Me.lblFullName.Location = New System.Drawing.Point(37, 80)
        Me.lblFullName.Name = "lblFullName"
        Me.lblFullName.Size = New System.Drawing.Size(54, 13)
        Me.lblFullName.TabIndex = 3
        Me.lblFullName.Text = "Full Name"
        '
        'txtFullName
        '
        Me.txtFullName.Location = New System.Drawing.Point(157, 80)
        Me.txtFullName.MaxLength = 50
        Me.txtFullName.Name = "txtFullName"
        Me.txtFullName.Size = New System.Drawing.Size(310, 20)
        Me.txtFullName.TabIndex = 3
        '
        'ErrFullName
        '
        Me.ErrFullName.ContainerControl = Me
        '
        'lblCreatedOn
        '
        Me.lblCreatedOn.AutoSize = True
        Me.lblCreatedOn.Location = New System.Drawing.Point(37, 100)
        Me.lblCreatedOn.Name = "lblCreatedOn"
        Me.lblCreatedOn.Size = New System.Drawing.Size(61, 13)
        Me.lblCreatedOn.TabIndex = 4
        Me.lblCreatedOn.Text = "Created On"
        '
        'ErrCreatedOn
        '
        Me.ErrCreatedOn.ContainerControl = Me
        '
        'lblIsEnabled
        '
        Me.lblIsEnabled.AutoSize = True
        Me.lblIsEnabled.Location = New System.Drawing.Point(37, 120)
        Me.lblIsEnabled.Name = "lblIsEnabled"
        Me.lblIsEnabled.Size = New System.Drawing.Size(57, 13)
        Me.lblIsEnabled.TabIndex = 5
        Me.lblIsEnabled.Text = "Is Enabled"
        '
        'ErrIsEnabled
        '
        Me.ErrIsEnabled.ContainerControl = Me
        '
        'lblIsSA
        '
        Me.lblIsSA.AutoSize = True
        Me.lblIsSA.Location = New System.Drawing.Point(37, 140)
        Me.lblIsSA.Name = "lblIsSA"
        Me.lblIsSA.Size = New System.Drawing.Size(32, 13)
        Me.lblIsSA.TabIndex = 6
        Me.lblIsSA.Text = "Is SA"
        '
        'ErrIsSA
        '
        Me.ErrIsSA.ContainerControl = Me
        '
        'lblMyRole
        '
        Me.lblMyRole.AutoSize = True
        Me.lblMyRole.Location = New System.Drawing.Point(37, 160)
        Me.lblMyRole.Name = "lblMyRole"
        Me.lblMyRole.Size = New System.Drawing.Size(43, 13)
        Me.lblMyRole.TabIndex = 7
        Me.lblMyRole.Text = "MyRole"
        '
        'txtMyRole
        '
        Me.txtMyRole.Location = New System.Drawing.Point(157, 160)
        Me.txtMyRole.MaxLength = 9
        Me.txtMyRole.Name = "txtMyRole"
        Me.txtMyRole.Size = New System.Drawing.Size(64, 20)
        Me.txtMyRole.TabIndex = 7
        '
        'ErrMyRole
        '
        Me.ErrMyRole.ContainerControl = Me
        '
        'CBIsEnabled
        '
        Me.CBIsEnabled.AutoSize = True
        Me.CBIsEnabled.Location = New System.Drawing.Point(157, 123)
        Me.CBIsEnabled.Name = "CBIsEnabled"
        Me.CBIsEnabled.Size = New System.Drawing.Size(15, 14)
        Me.CBIsEnabled.TabIndex = 13
        Me.CBIsEnabled.UseVisualStyleBackColor = True
        '
        'CBIsSA
        '
        Me.CBIsSA.AutoSize = True
        Me.CBIsSA.Location = New System.Drawing.Point(157, 140)
        Me.CBIsSA.Name = "CBIsSA"
        Me.CBIsSA.Size = New System.Drawing.Size(15, 14)
        Me.CBIsSA.TabIndex = 14
        Me.CBIsSA.UseVisualStyleBackColor = True
        '
        'DateCreated
        '
        Me.DateCreated.Enabled = False
        Me.DateCreated.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.DateCreated.Location = New System.Drawing.Point(157, 100)
        Me.DateCreated.Name = "DateCreated"
        Me.DateCreated.Size = New System.Drawing.Size(90, 20)
        Me.DateCreated.TabIndex = 15
        '
        'Button1
        '
        Me.Button1.Location = New System.Drawing.Point(718, 135)
        Me.Button1.Name = "Button1"
        Me.Button1.Size = New System.Drawing.Size(197, 23)
        Me.Button1.TabIndex = 16
        Me.Button1.Text = "Create Database User"
        Me.Button1.UseVisualStyleBackColor = True
        '
        'txtDBPass
        '
        Me.txtDBPass.Location = New System.Drawing.Point(718, 80)
        Me.txtDBPass.MaxLength = 10
        Me.txtDBPass.Name = "txtDBPass"
        Me.txtDBPass.PasswordChar = Global.Microsoft.VisualBasic.ChrW(42)
        Me.txtDBPass.Size = New System.Drawing.Size(197, 20)
        Me.txtDBPass.TabIndex = 17
        '
        'Label1
        '
        Me.Label1.AutoSize = True
        Me.Label1.Location = New System.Drawing.Point(598, 57)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(109, 13)
        Me.Label1.TabIndex = 19
        Me.Label1.Text = "Database User Name"
        '
        'txtDBUser
        '
        Me.txtDBUser.Location = New System.Drawing.Point(718, 57)
        Me.txtDBUser.MaxLength = 10
        Me.txtDBUser.Name = "txtDBUser"
        Me.txtDBUser.Size = New System.Drawing.Size(197, 20)
        Me.txtDBUser.TabIndex = 18
        '
        'Label3
        '
        Me.Label3.AutoSize = True
        Me.Label3.Location = New System.Drawing.Point(598, 83)
        Me.Label3.Name = "Label3"
        Me.Label3.Size = New System.Drawing.Size(102, 13)
        Me.Label3.TabIndex = 21
        Me.Label3.Text = "Database Password"
        '
        'Button2
        '
        Me.Button2.Location = New System.Drawing.Point(718, 157)
        Me.Button2.Name = "Button2"
        Me.Button2.Size = New System.Drawing.Size(197, 23)
        Me.Button2.TabIndex = 22
        Me.Button2.Text = "Add User on Database"
        Me.Button2.UseVisualStyleBackColor = True
        '
        'Label2
        '
        Me.Label2.AutoSize = True
        Me.Label2.Location = New System.Drawing.Point(598, 106)
        Me.Label2.Name = "Label2"
        Me.Label2.Size = New System.Drawing.Size(97, 13)
        Me.Label2.TabIndex = 24
        Me.Label2.Text = "Re Type Password"
        '
        'txtDBPass2
        '
        Me.txtDBPass2.Location = New System.Drawing.Point(718, 103)
        Me.txtDBPass2.MaxLength = 10
        Me.txtDBPass2.Name = "txtDBPass2"
        Me.txtDBPass2.PasswordChar = Global.Microsoft.VisualBasic.ChrW(42)
        Me.txtDBPass2.Size = New System.Drawing.Size(197, 20)
        Me.txtDBPass2.TabIndex = 23
        '
        'frmAaSsUsers
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.SystemColors.GradientActiveCaption
        Me.ClientSize = New System.Drawing.Size(987, 551)
        Me.Controls.Add(Me.Label2)
        Me.Controls.Add(Me.txtDBPass2)
        Me.Controls.Add(Me.Button2)
        Me.Controls.Add(Me.Label3)
        Me.Controls.Add(Me.Label1)
        Me.Controls.Add(Me.txtDBUser)
        Me.Controls.Add(Me.txtDBPass)
        Me.Controls.Add(Me.Button1)
        Me.Controls.Add(Me.DateCreated)
        Me.Controls.Add(Me.CBIsSA)
        Me.Controls.Add(Me.CBIsEnabled)
        Me.Controls.Add(Me.lblId)
        Me.Controls.Add(Me.txtId)
        Me.Controls.Add(Me.lblUserName)
        Me.Controls.Add(Me.txtUserName)
        Me.Controls.Add(Me.lblFullName)
        Me.Controls.Add(Me.txtFullName)
        Me.Controls.Add(Me.lblCreatedOn)
        Me.Controls.Add(Me.lblIsEnabled)
        Me.Controls.Add(Me.lblIsSA)
        Me.Controls.Add(Me.lblMyRole)
        Me.Controls.Add(Me.txtMyRole)
        Me.Controls.Add(Me.TSC1)
        Me.Controls.Add(Me.sspStatus)
        Me.Controls.Add(Me.DG1)
        Me.Name = "frmAaSsUsers"
        Me.Text = "Users"
        Me.sspStatus.ResumeLayout(False)
        Me.sspStatus.PerformLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.TSC1.TopToolStripPanel.ResumeLayout(False)
        Me.TSC1.TopToolStripPanel.PerformLayout()
        Me.TSC1.ResumeLayout(False)
        Me.TSC1.PerformLayout()
        Me.TS1.ResumeLayout(False)
        Me.TS1.PerformLayout()
        CType(Me.ErrId, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrUserName, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrFullName, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrCreatedOn, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrIsEnabled, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrIsSA, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrMyRole, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
    Friend WithEvents lblId As System.Windows.Forms.Label
    Friend WithEvents txtId As System.Windows.Forms.TextBox
    Friend WithEvents ErrId As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblUserName As System.Windows.Forms.Label
    Friend WithEvents txtUserName As System.Windows.Forms.TextBox
    Friend WithEvents ErrUserName As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblFullName As System.Windows.Forms.Label
    Friend WithEvents txtFullName As System.Windows.Forms.TextBox
    Friend WithEvents ErrFullName As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblCreatedOn As System.Windows.Forms.Label
    Friend WithEvents ErrCreatedOn As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblIsEnabled As System.Windows.Forms.Label
    Friend WithEvents ErrIsEnabled As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblIsSA As System.Windows.Forms.Label
    Friend WithEvents ErrIsSA As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblMyRole As System.Windows.Forms.Label
    Friend WithEvents txtMyRole As System.Windows.Forms.TextBox
    Friend WithEvents ErrMyRole As System.Windows.Forms.ErrorProvider
    Friend WithEvents sspStatus As System.Windows.Forms.StatusStrip
    Friend WithEvents lblSSStatus As System.Windows.Forms.ToolStripStatusLabel
    Friend WithEvents DG1 As System.Windows.Forms.DataGridView
    Friend WithEvents TSC1 As System.Windows.Forms.ToolStripContainer
    Friend WithEvents TS1 As System.Windows.Forms.ToolStrip
    Friend WithEvents TSBNew As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBSave As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBDelete As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBExcel As System.Windows.Forms.ToolStripButton
    Friend WithEvents CBIsSA As System.Windows.Forms.CheckBox
    Friend WithEvents CBIsEnabled As System.Windows.Forms.CheckBox
    Friend WithEvents DateCreated As System.Windows.Forms.DateTimePicker
    Friend WithEvents dgcUsr_Id As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcUsr_UserName As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcUsr_FullName As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcUsr_CreatedOn As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcUsr_IsEnabled As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcUsr_IsSA As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcUsr_MyRole As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents Button1 As System.Windows.Forms.Button
    Friend WithEvents Button2 As System.Windows.Forms.Button
    Friend WithEvents Label3 As System.Windows.Forms.Label
    Friend WithEvents Label1 As System.Windows.Forms.Label
    Friend WithEvents txtDBUser As System.Windows.Forms.TextBox
    Friend WithEvents txtDBPass As System.Windows.Forms.TextBox
    Friend WithEvents Label2 As System.Windows.Forms.Label
    Friend WithEvents txtDBPass2 As System.Windows.Forms.TextBox
End Class
