' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 13/02/2008 09:42:47
'
'
Public Class cPrAnEmployeeAnalysis1DbTier
    '
    Inherits cDataTier
    '
    Protected Function GetByPK(ByVal tCode As String) As DataSet
        Dim Str As String
        Str = " SELECT" & _
                " EmpAn1_Code," & _
                " EmpAn1_DescriptionL," & _
                " EmpAn1_DescriptionS," & _
                " EmpAn1_IsActive," & _
                " EmpAn1_GLAnal1," & _
                " EmpAn1_GLAnal2," & _
                " EmpAn1_CreationDate," & _
                " EmpAn1_AmendDate" & _
            "  FROM PrAnEmployeeAnalysis1" & _
            "  WHERE EmpAn1_Code = '" & tCode & "'"
        Return MyBase.GetData(Str)
    End Function
    Protected Function Save(ByVal _cPrAnEmployeeAnalysis1 As cPrAnEmployeeAnalysis1) As Boolean
        Dim SpParams As New ArrayList
        Dim SpNames As New ArrayList
        Dim Flag As Boolean = False
        With _cPrAnEmployeeAnalysis1
            SpParams.Add(.Code)                                              '(0)
            SpNames.Add("EmpAn1_Code")                                       '(0)
            SpParams.Add(.DescriptionL)                                      '(1)
            SpNames.Add("EmpAn1_DescriptionL")                               '(1)
            SpParams.Add(.DescriptionS)                                      '(2)
            SpNames.Add("EmpAn1_DescriptionS")                               '(2)
            SpParams.Add(.IsActive)                                          '(3)
            SpNames.Add("EmpAn1_IsActive")                                   '(3)
            SpParams.Add(.GLAnal1)                                           '(4)
            SpNames.Add("EmpAn1_GLAnal1")                                    '(4)
            SpParams.Add(.GLAnal2)                                           '(5)
            SpNames.Add("EmpAn1_GLAnal2")                                    '(5)
            SpParams.Add(.CreationDate)                                      '(6)
            SpNames.Add("EmpAn1_CreationDate")                               '(6)
            SpParams.Add(.AmendDate)                                         '(7)
            SpNames.Add("EmpAn1_AmendDate")                                  '(7)
        End With
        If Me.StoredProcedure("AG_PrAnEmployeeAnalysis1_Save_Update", SpParams, SpNames) Then
            Return True
        Else
            Return False
        End If
    End Function
    Protected Function Delete(ByVal tCode As String) As Boolean
        Dim Str As String
        Dim Flag As Boolean = True
        Dim Exx As New System.Exception
        Try
            BeginTransaction()
            Str = " DELETE FROM PrAnEmployeeAnalysis1" & _
               " WHERE EmpAn1_Code = '" & tCode & "'"
            If MyBase.ExecuteNonQuery(Str) = -1 Then
                Throw Exx
            End If
            CommitTransaction()
        Catch ex As Exception
            Rollback()
            Utils.ShowException(ex)
            Flag = False
        End Try
        Return Flag
    End Function
    Protected Function CheckDeleteRecords(ByVal tCode As String) As DataSet
        Dim Str As String
        Str = " " & _
        "SELECT COUNT(EmpAn1_Code) " & _
        " FROM PrMsEmployees" & _
        " WHERE EmpAn1_Code = '" & tCode & "'" & _
        " " & _
        " "
        Return GetData(Str)
    End Function
End Class
