<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmPrTxEmployeeDiscounts
Inherits System.Windows.Forms.Form
<System.Diagnostics.DebuggerNonUserCode()> _
Protected Overrides Sub Dispose(ByVal disposing As Boolean)
If Disposing AndAlso components IsNot Nothing Then
components.Dispose()
End If
MyBase.Dispose(Disposing)
End Sub
Private components As System.ComponentModel.IContainer
' AutoGenerated Form by Nodalsoft
<System.Diagnostics.DebuggerStepThrough()> _
Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmPrTxEmployeeDiscounts))
        Me.sspStatus = New System.Windows.Forms.StatusStrip()
        Me.lblSSStatus = New System.Windows.Forms.ToolStripStatusLabel()
        Me.DG1 = New System.Windows.Forms.DataGridView()
        Me.dgcEmpDis_id = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.dgcEmp_Code = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.dgcPrdGrp_Code = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.dgcEmpDis_Discount1 = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.dgcEmpDis_Discount2 = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.dgcEmpDis_Discount3 = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.dgcEmpDis_Discount4 = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.dgcEmpDis_Discount5 = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.dgcEmpDis_Discount6 = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.dgcEmpDis_Discount7 = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.dgcEmpDis_Discount8 = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.dgcEmpDis_Discount9 = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.dgcEmpDis_Discount10 = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.dgcEmpDis_LifeInsurance = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.dgcUsr_Id = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.dgcEmpDis_CreationDate = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.dgcEmpDis_AmendDate = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.MedicalFund = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.PensionFund = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.TSC1 = New System.Windows.Forms.ToolStripContainer()
        Me.TS1 = New System.Windows.Forms.ToolStrip()
        Me.TSBNew = New System.Windows.Forms.ToolStripButton()
        Me.TSBSave = New System.Windows.Forms.ToolStripButton()
        Me.TSBDelete = New System.Windows.Forms.ToolStripButton()
        Me.TSBExcel = New System.Windows.Forms.ToolStripButton()
        Me.ToolStripDropDownButton1 = New System.Windows.Forms.ToolStripDropDownButton()
        Me.RemoToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.ToolStripButton3 = New System.Windows.Forms.ToolStripButton()
        Me.ToolStripButton4 = New System.Windows.Forms.ToolStripButton()
        Me.lblId = New System.Windows.Forms.Label()
        Me.txtId = New System.Windows.Forms.TextBox()
        Me.ErrId = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.ErrEmp_Code = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblPrdGrp_Code = New System.Windows.Forms.Label()
        Me.cmbPrdGrp_Code = New System.Windows.Forms.ComboBox()
        Me.ErrPrdGrp_Code = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDiscount1 = New System.Windows.Forms.Label()
        Me.txtDiscount1 = New System.Windows.Forms.TextBox()
        Me.ErrDiscount1 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDiscount2 = New System.Windows.Forms.Label()
        Me.txtDiscount2 = New System.Windows.Forms.TextBox()
        Me.ErrDiscount2 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDiscount3 = New System.Windows.Forms.Label()
        Me.txtDiscount3 = New System.Windows.Forms.TextBox()
        Me.ErrDiscount3 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDiscount4 = New System.Windows.Forms.Label()
        Me.txtDiscount4 = New System.Windows.Forms.TextBox()
        Me.ErrDiscount4 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDiscount5 = New System.Windows.Forms.Label()
        Me.txtDiscount5 = New System.Windows.Forms.TextBox()
        Me.ErrDiscount5 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDiscount6 = New System.Windows.Forms.Label()
        Me.txtDiscount6 = New System.Windows.Forms.TextBox()
        Me.ErrDiscount6 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDiscount7 = New System.Windows.Forms.Label()
        Me.txtDiscount7 = New System.Windows.Forms.TextBox()
        Me.ErrDiscount7 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDiscount8 = New System.Windows.Forms.Label()
        Me.txtDiscount8 = New System.Windows.Forms.TextBox()
        Me.ErrDiscount8 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDiscount9 = New System.Windows.Forms.Label()
        Me.txtDiscount9 = New System.Windows.Forms.TextBox()
        Me.ErrDiscount9 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDiscount10 = New System.Windows.Forms.Label()
        Me.txtDiscount10 = New System.Windows.Forms.TextBox()
        Me.ErrDiscount10 = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblLifeInsurance = New System.Windows.Forms.Label()
        Me.txtLifeInsurance = New System.Windows.Forms.TextBox()
        Me.ErrLifeInsurance = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblUsr_Id = New System.Windows.Forms.Label()
        Me.cmbUsr_Id = New System.Windows.Forms.ComboBox()
        Me.ErrUsr_Id = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblCreationDate = New System.Windows.Forms.Label()
        Me.txtCreationDate = New System.Windows.Forms.TextBox()
        Me.ErrCreationDate = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblAmendDate = New System.Windows.Forms.Label()
        Me.txtAmendDate = New System.Windows.Forms.TextBox()
        Me.ErrAmendDate = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.Button1 = New System.Windows.Forms.Button()
        Me.Label1 = New System.Windows.Forms.Label()
        Me.txtCopyFrom = New System.Windows.Forms.TextBox()
        Me.Button3 = New System.Windows.Forms.Button()
        Me.txtCopyPeriodGroup = New System.Windows.Forms.TextBox()
        Me.GroupBox1 = New System.Windows.Forms.GroupBox()
        Me.Label3 = New System.Windows.Forms.Label()
        Me.Label2 = New System.Windows.Forms.Label()
        Me.Label4 = New System.Windows.Forms.Label()
        Me.txtMedical = New System.Windows.Forms.TextBox()
        Me.BtnNext = New System.Windows.Forms.Button()
        Me.BtnPrevius = New System.Windows.Forms.Button()
        Me.Label5 = New System.Windows.Forms.Label()
        Me.txtEmployeeCode = New System.Windows.Forms.TextBox()
        Me.Label6 = New System.Windows.Forms.Label()
        Me.txtEmployeeName = New System.Windows.Forms.TextBox()
        Me.Label7 = New System.Windows.Forms.Label()
        Me.txtPensionfund = New System.Windows.Forms.TextBox()
        Me.RemoveFirstEmployementFromALLActiveEmployeesToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.sspStatus.SuspendLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.TSC1.TopToolStripPanel.SuspendLayout()
        Me.TSC1.SuspendLayout()
        Me.TS1.SuspendLayout()
        CType(Me.ErrId, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEmp_Code, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrPrdGrp_Code, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDiscount1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDiscount2, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDiscount3, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDiscount4, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDiscount5, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDiscount6, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDiscount7, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDiscount8, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDiscount9, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDiscount10, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrLifeInsurance, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrUsr_Id, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrCreationDate, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrAmendDate, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.GroupBox1.SuspendLayout()
        Me.SuspendLayout()
        '
        'sspStatus
        '
        Me.sspStatus.BackColor = System.Drawing.SystemColors.Control
        Me.sspStatus.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.lblSSStatus})
        Me.sspStatus.Location = New System.Drawing.Point(0, 481)
        Me.sspStatus.Name = "sspStatus"
        Me.sspStatus.Size = New System.Drawing.Size(872, 22)
        Me.sspStatus.TabIndex = 3
        Me.sspStatus.Text = "StatusStrip"
        '
        'lblSSStatus
        '
        Me.lblSSStatus.Name = "lblSSStatus"
        Me.lblSSStatus.Size = New System.Drawing.Size(0, 17)
        '
        'DG1
        '
        Me.DG1.AllowUserToAddRows = False
        Me.DG1.AllowUserToDeleteRows = False
        Me.DG1.BackgroundColor = System.Drawing.SystemColors.Window
        Me.DG1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DG1.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.dgcEmpDis_id, Me.dgcEmp_Code, Me.dgcPrdGrp_Code, Me.dgcEmpDis_Discount1, Me.dgcEmpDis_Discount2, Me.dgcEmpDis_Discount3, Me.dgcEmpDis_Discount4, Me.dgcEmpDis_Discount5, Me.dgcEmpDis_Discount6, Me.dgcEmpDis_Discount7, Me.dgcEmpDis_Discount8, Me.dgcEmpDis_Discount9, Me.dgcEmpDis_Discount10, Me.dgcEmpDis_LifeInsurance, Me.dgcUsr_Id, Me.dgcEmpDis_CreationDate, Me.dgcEmpDis_AmendDate, Me.MedicalFund, Me.PensionFund})
        Me.DG1.Location = New System.Drawing.Point(12, 340)
        Me.DG1.Name = "DG1"
        Me.DG1.ReadOnly = True
        Me.DG1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
        Me.DG1.Size = New System.Drawing.Size(848, 138)
        Me.DG1.TabIndex = 10
        '
        'dgcEmpDis_id
        '
        Me.dgcEmpDis_id.DataPropertyName = "EmpDis_id"
        Me.dgcEmpDis_id.FillWeight = 150.0!
        Me.dgcEmpDis_id.HeaderText = "id"
        Me.dgcEmpDis_id.Name = "dgcEmpDis_id"
        Me.dgcEmpDis_id.ReadOnly = True
        Me.dgcEmpDis_id.Visible = False
        Me.dgcEmpDis_id.Width = 64
        '
        'dgcEmp_Code
        '
        Me.dgcEmp_Code.DataPropertyName = "Emp_Code"
        Me.dgcEmp_Code.FillWeight = 150.0!
        Me.dgcEmp_Code.HeaderText = "Employee Code"
        Me.dgcEmp_Code.Name = "dgcEmp_Code"
        Me.dgcEmp_Code.ReadOnly = True
        Me.dgcEmp_Code.Visible = False
        Me.dgcEmp_Code.Width = 106
        '
        'dgcPrdGrp_Code
        '
        Me.dgcPrdGrp_Code.DataPropertyName = "PrdGrp_Code"
        Me.dgcPrdGrp_Code.FillWeight = 150.0!
        Me.dgcPrdGrp_Code.HeaderText = "Period Group Code"
        Me.dgcPrdGrp_Code.Name = "dgcPrdGrp_Code"
        Me.dgcPrdGrp_Code.ReadOnly = True
        '
        'dgcEmpDis_Discount1
        '
        Me.dgcEmpDis_Discount1.DataPropertyName = "EmpDis_Discount1"
        Me.dgcEmpDis_Discount1.FillWeight = 150.0!
        Me.dgcEmpDis_Discount1.HeaderText = "Discount 1"
        Me.dgcEmpDis_Discount1.Name = "dgcEmpDis_Discount1"
        Me.dgcEmpDis_Discount1.ReadOnly = True
        '
        'dgcEmpDis_Discount2
        '
        Me.dgcEmpDis_Discount2.DataPropertyName = "EmpDis_Discount2"
        Me.dgcEmpDis_Discount2.FillWeight = 150.0!
        Me.dgcEmpDis_Discount2.HeaderText = "Discount 2"
        Me.dgcEmpDis_Discount2.Name = "dgcEmpDis_Discount2"
        Me.dgcEmpDis_Discount2.ReadOnly = True
        '
        'dgcEmpDis_Discount3
        '
        Me.dgcEmpDis_Discount3.DataPropertyName = "EmpDis_Discount3"
        Me.dgcEmpDis_Discount3.FillWeight = 150.0!
        Me.dgcEmpDis_Discount3.HeaderText = "Discount 3"
        Me.dgcEmpDis_Discount3.Name = "dgcEmpDis_Discount3"
        Me.dgcEmpDis_Discount3.ReadOnly = True
        '
        'dgcEmpDis_Discount4
        '
        Me.dgcEmpDis_Discount4.DataPropertyName = "EmpDis_Discount4"
        Me.dgcEmpDis_Discount4.FillWeight = 150.0!
        Me.dgcEmpDis_Discount4.HeaderText = "Discount 4"
        Me.dgcEmpDis_Discount4.Name = "dgcEmpDis_Discount4"
        Me.dgcEmpDis_Discount4.ReadOnly = True
        '
        'dgcEmpDis_Discount5
        '
        Me.dgcEmpDis_Discount5.DataPropertyName = "EmpDis_Discount5"
        Me.dgcEmpDis_Discount5.FillWeight = 150.0!
        Me.dgcEmpDis_Discount5.HeaderText = "Discount 5"
        Me.dgcEmpDis_Discount5.Name = "dgcEmpDis_Discount5"
        Me.dgcEmpDis_Discount5.ReadOnly = True
        '
        'dgcEmpDis_Discount6
        '
        Me.dgcEmpDis_Discount6.DataPropertyName = "EmpDis_Discount6"
        Me.dgcEmpDis_Discount6.FillWeight = 150.0!
        Me.dgcEmpDis_Discount6.HeaderText = "Discount 6"
        Me.dgcEmpDis_Discount6.Name = "dgcEmpDis_Discount6"
        Me.dgcEmpDis_Discount6.ReadOnly = True
        '
        'dgcEmpDis_Discount7
        '
        Me.dgcEmpDis_Discount7.DataPropertyName = "EmpDis_Discount7"
        Me.dgcEmpDis_Discount7.FillWeight = 150.0!
        Me.dgcEmpDis_Discount7.HeaderText = "Discount 7"
        Me.dgcEmpDis_Discount7.Name = "dgcEmpDis_Discount7"
        Me.dgcEmpDis_Discount7.ReadOnly = True
        '
        'dgcEmpDis_Discount8
        '
        Me.dgcEmpDis_Discount8.DataPropertyName = "EmpDis_Discount8"
        Me.dgcEmpDis_Discount8.FillWeight = 150.0!
        Me.dgcEmpDis_Discount8.HeaderText = "Discount 8"
        Me.dgcEmpDis_Discount8.Name = "dgcEmpDis_Discount8"
        Me.dgcEmpDis_Discount8.ReadOnly = True
        '
        'dgcEmpDis_Discount9
        '
        Me.dgcEmpDis_Discount9.DataPropertyName = "EmpDis_Discount9"
        Me.dgcEmpDis_Discount9.FillWeight = 150.0!
        Me.dgcEmpDis_Discount9.HeaderText = "Discount 9"
        Me.dgcEmpDis_Discount9.Name = "dgcEmpDis_Discount9"
        Me.dgcEmpDis_Discount9.ReadOnly = True
        '
        'dgcEmpDis_Discount10
        '
        Me.dgcEmpDis_Discount10.DataPropertyName = "EmpDis_Discount10"
        Me.dgcEmpDis_Discount10.FillWeight = 150.0!
        Me.dgcEmpDis_Discount10.HeaderText = "Discount 10"
        Me.dgcEmpDis_Discount10.Name = "dgcEmpDis_Discount10"
        Me.dgcEmpDis_Discount10.ReadOnly = True
        '
        'dgcEmpDis_LifeInsurance
        '
        Me.dgcEmpDis_LifeInsurance.DataPropertyName = "EmpDis_LifeInsurance"
        Me.dgcEmpDis_LifeInsurance.FillWeight = 150.0!
        Me.dgcEmpDis_LifeInsurance.HeaderText = "Life Insurance"
        Me.dgcEmpDis_LifeInsurance.Name = "dgcEmpDis_LifeInsurance"
        Me.dgcEmpDis_LifeInsurance.ReadOnly = True
        '
        'dgcUsr_Id
        '
        Me.dgcUsr_Id.DataPropertyName = "Usr_Id"
        Me.dgcUsr_Id.FillWeight = 150.0!
        Me.dgcUsr_Id.HeaderText = "User Id"
        Me.dgcUsr_Id.Name = "dgcUsr_Id"
        Me.dgcUsr_Id.ReadOnly = True
        '
        'dgcEmpDis_CreationDate
        '
        Me.dgcEmpDis_CreationDate.DataPropertyName = "EmpDis_CreationDate"
        Me.dgcEmpDis_CreationDate.FillWeight = 150.0!
        Me.dgcEmpDis_CreationDate.HeaderText = "Creation Date"
        Me.dgcEmpDis_CreationDate.Name = "dgcEmpDis_CreationDate"
        Me.dgcEmpDis_CreationDate.ReadOnly = True
        Me.dgcEmpDis_CreationDate.Width = 70
        '
        'dgcEmpDis_AmendDate
        '
        Me.dgcEmpDis_AmendDate.DataPropertyName = "EmpDis_AmendDate"
        Me.dgcEmpDis_AmendDate.FillWeight = 150.0!
        Me.dgcEmpDis_AmendDate.HeaderText = "Amend Date"
        Me.dgcEmpDis_AmendDate.Name = "dgcEmpDis_AmendDate"
        Me.dgcEmpDis_AmendDate.ReadOnly = True
        Me.dgcEmpDis_AmendDate.Width = 70
        '
        'MedicalFund
        '
        Me.MedicalFund.DataPropertyName = "EmpDis_Medical"
        Me.MedicalFund.HeaderText = "Private Medical Fund"
        Me.MedicalFund.Name = "MedicalFund"
        Me.MedicalFund.ReadOnly = True
        '
        'PensionFund
        '
        Me.PensionFund.DataPropertyName = "EmpDis_PensionFund"
        Me.PensionFund.HeaderText = "Private Pension Fund"
        Me.PensionFund.Name = "PensionFund"
        Me.PensionFund.ReadOnly = True
        '
        'TSC1
        '
        Me.TSC1.BottomToolStripPanelVisible = False
        '
        'TSC1.ContentPanel
        '
        Me.TSC1.ContentPanel.Size = New System.Drawing.Size(872, 0)
        Me.TSC1.Dock = System.Windows.Forms.DockStyle.Top
        Me.TSC1.LeftToolStripPanelVisible = False
        Me.TSC1.Location = New System.Drawing.Point(0, 0)
        Me.TSC1.Name = "TSC1"
        Me.TSC1.RightToolStripPanelVisible = False
        Me.TSC1.Size = New System.Drawing.Size(872, 25)
        Me.TSC1.TabIndex = 12
        Me.TSC1.Text = "TSC1"
        '
        'TSC1.TopToolStripPanel
        '
        Me.TSC1.TopToolStripPanel.Controls.Add(Me.TS1)
        '
        'TS1
        '
        Me.TS1.Dock = System.Windows.Forms.DockStyle.None
        Me.TS1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.TSBNew, Me.TSBSave, Me.TSBDelete, Me.TSBExcel, Me.ToolStripDropDownButton1, Me.ToolStripButton3, Me.ToolStripButton4})
        Me.TS1.Location = New System.Drawing.Point(3, 0)
        Me.TS1.Name = "TS1"
        Me.TS1.Size = New System.Drawing.Size(869, 25)
        Me.TS1.TabIndex = 0
        '
        'TSBNew
        '
        Me.TSBNew.AutoSize = False
        Me.TSBNew.Image = CType(resources.GetObject("TSBNew.Image"), System.Drawing.Image)
        Me.TSBNew.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBNew.Name = "TSBNew"
        Me.TSBNew.Size = New System.Drawing.Size(60, 22)
        Me.TSBNew.Text = "New"
        Me.TSBNew.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBSave
        '
        Me.TSBSave.AutoSize = False
        Me.TSBSave.Image = CType(resources.GetObject("TSBSave.Image"), System.Drawing.Image)
        Me.TSBSave.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBSave.Name = "TSBSave"
        Me.TSBSave.Size = New System.Drawing.Size(60, 22)
        Me.TSBSave.Text = "Save"
        Me.TSBSave.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBDelete
        '
        Me.TSBDelete.AutoSize = False
        Me.TSBDelete.Enabled = False
        Me.TSBDelete.Image = CType(resources.GetObject("TSBDelete.Image"), System.Drawing.Image)
        Me.TSBDelete.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBDelete.Name = "TSBDelete"
        Me.TSBDelete.Size = New System.Drawing.Size(60, 22)
        Me.TSBDelete.Text = "Delete"
        Me.TSBDelete.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBExcel
        '
        Me.TSBExcel.AutoSize = False
        Me.TSBExcel.Image = Global.NodalPay.My.Resources.Resources.excel
        Me.TSBExcel.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBExcel.Name = "TSBExcel"
        Me.TSBExcel.Size = New System.Drawing.Size(60, 22)
        Me.TSBExcel.Text = "Excel"
        Me.TSBExcel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'ToolStripDropDownButton1
        '
        Me.ToolStripDropDownButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text
        Me.ToolStripDropDownButton1.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.RemoToolStripMenuItem, Me.RemoveFirstEmployementFromALLActiveEmployeesToolStripMenuItem})
        Me.ToolStripDropDownButton1.Image = CType(resources.GetObject("ToolStripDropDownButton1.Image"), System.Drawing.Image)
        Me.ToolStripDropDownButton1.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.ToolStripDropDownButton1.Name = "ToolStripDropDownButton1"
        Me.ToolStripDropDownButton1.Size = New System.Drawing.Size(48, 22)
        Me.ToolStripDropDownButton1.Text = "Tools"
        '
        'RemoToolStripMenuItem
        '
        Me.RemoToolStripMenuItem.Name = "RemoToolStripMenuItem"
        Me.RemoToolStripMenuItem.Size = New System.Drawing.Size(655, 22)
        Me.RemoToolStripMenuItem.Text = "Delete ALL Discounts, Life insurance, Private Medical Fund , Private Pension Fund" &
    " of the Selected Period Group"
        '
        'ToolStripButton3
        '
        Me.ToolStripButton3.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text
        Me.ToolStripButton3.Image = CType(resources.GetObject("ToolStripButton3.Image"), System.Drawing.Image)
        Me.ToolStripButton3.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.ToolStripButton3.Name = "ToolStripButton3"
        Me.ToolStripButton3.Size = New System.Drawing.Size(612, 19)
        Me.ToolStripButton3.Text = "Delete Discounts/Life Insurance/PrivateMedical/Private Pension from ALL employees" &
    " of the Selected Period Group"
        '
        'ToolStripButton4
        '
        Me.ToolStripButton4.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text
        Me.ToolStripButton4.Image = CType(resources.GetObject("ToolStripButton4.Image"), System.Drawing.Image)
        Me.ToolStripButton4.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.ToolStripButton4.Name = "ToolStripButton4"
        Me.ToolStripButton4.Size = New System.Drawing.Size(304, 19)
        Me.ToolStripButton4.Text = "Remove First Employement from ALL Active Employees"
        '
        'lblId
        '
        Me.lblId.AutoSize = True
        Me.lblId.Location = New System.Drawing.Point(580, 291)
        Me.lblId.Name = "lblId"
        Me.lblId.Size = New System.Drawing.Size(15, 13)
        Me.lblId.TabIndex = 0
        Me.lblId.Text = "id"
        Me.lblId.Visible = False
        '
        'txtId
        '
        Me.txtId.Location = New System.Drawing.Point(596, 261)
        Me.txtId.MaxLength = 9
        Me.txtId.Name = "txtId"
        Me.txtId.Size = New System.Drawing.Size(64, 20)
        Me.txtId.TabIndex = 1
        Me.txtId.Visible = False
        '
        'ErrId
        '
        Me.ErrId.ContainerControl = Me
        '
        'ErrEmp_Code
        '
        Me.ErrEmp_Code.ContainerControl = Me
        '
        'lblPrdGrp_Code
        '
        Me.lblPrdGrp_Code.AutoSize = True
        Me.lblPrdGrp_Code.Location = New System.Drawing.Point(18, 118)
        Me.lblPrdGrp_Code.Name = "lblPrdGrp_Code"
        Me.lblPrdGrp_Code.Size = New System.Drawing.Size(97, 13)
        Me.lblPrdGrp_Code.TabIndex = 3
        Me.lblPrdGrp_Code.Text = "Period Group Code"
        '
        'cmbPrdGrp_Code
        '
        Me.cmbPrdGrp_Code.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.cmbPrdGrp_Code.Location = New System.Drawing.Point(138, 118)
        Me.cmbPrdGrp_Code.Name = "cmbPrdGrp_Code"
        Me.cmbPrdGrp_Code.Size = New System.Drawing.Size(195, 21)
        Me.cmbPrdGrp_Code.TabIndex = 3
        '
        'ErrPrdGrp_Code
        '
        Me.ErrPrdGrp_Code.ContainerControl = Me
        '
        'lblDiscount1
        '
        Me.lblDiscount1.AutoSize = True
        Me.lblDiscount1.Location = New System.Drawing.Point(18, 138)
        Me.lblDiscount1.Name = "lblDiscount1"
        Me.lblDiscount1.Size = New System.Drawing.Size(58, 13)
        Me.lblDiscount1.TabIndex = 4
        Me.lblDiscount1.Text = "Discount 1"
        '
        'txtDiscount1
        '
        Me.txtDiscount1.Location = New System.Drawing.Point(138, 139)
        Me.txtDiscount1.MaxLength = 15
        Me.txtDiscount1.Name = "txtDiscount1"
        Me.txtDiscount1.Size = New System.Drawing.Size(100, 20)
        Me.txtDiscount1.TabIndex = 4
        '
        'ErrDiscount1
        '
        Me.ErrDiscount1.ContainerControl = Me
        '
        'lblDiscount2
        '
        Me.lblDiscount2.AutoSize = True
        Me.lblDiscount2.Location = New System.Drawing.Point(18, 158)
        Me.lblDiscount2.Name = "lblDiscount2"
        Me.lblDiscount2.Size = New System.Drawing.Size(58, 13)
        Me.lblDiscount2.TabIndex = 5
        Me.lblDiscount2.Text = "Discount 2"
        '
        'txtDiscount2
        '
        Me.txtDiscount2.Location = New System.Drawing.Point(138, 159)
        Me.txtDiscount2.MaxLength = 15
        Me.txtDiscount2.Name = "txtDiscount2"
        Me.txtDiscount2.Size = New System.Drawing.Size(100, 20)
        Me.txtDiscount2.TabIndex = 5
        '
        'ErrDiscount2
        '
        Me.ErrDiscount2.ContainerControl = Me
        '
        'lblDiscount3
        '
        Me.lblDiscount3.AutoSize = True
        Me.lblDiscount3.Location = New System.Drawing.Point(18, 178)
        Me.lblDiscount3.Name = "lblDiscount3"
        Me.lblDiscount3.Size = New System.Drawing.Size(58, 13)
        Me.lblDiscount3.TabIndex = 6
        Me.lblDiscount3.Text = "Discount 3"
        '
        'txtDiscount3
        '
        Me.txtDiscount3.Location = New System.Drawing.Point(138, 179)
        Me.txtDiscount3.MaxLength = 15
        Me.txtDiscount3.Name = "txtDiscount3"
        Me.txtDiscount3.Size = New System.Drawing.Size(100, 20)
        Me.txtDiscount3.TabIndex = 6
        '
        'ErrDiscount3
        '
        Me.ErrDiscount3.ContainerControl = Me
        '
        'lblDiscount4
        '
        Me.lblDiscount4.AutoSize = True
        Me.lblDiscount4.Location = New System.Drawing.Point(18, 198)
        Me.lblDiscount4.Name = "lblDiscount4"
        Me.lblDiscount4.Size = New System.Drawing.Size(58, 13)
        Me.lblDiscount4.TabIndex = 7
        Me.lblDiscount4.Text = "Discount 4"
        '
        'txtDiscount4
        '
        Me.txtDiscount4.Location = New System.Drawing.Point(138, 199)
        Me.txtDiscount4.MaxLength = 15
        Me.txtDiscount4.Name = "txtDiscount4"
        Me.txtDiscount4.Size = New System.Drawing.Size(100, 20)
        Me.txtDiscount4.TabIndex = 7
        '
        'ErrDiscount4
        '
        Me.ErrDiscount4.ContainerControl = Me
        '
        'lblDiscount5
        '
        Me.lblDiscount5.AutoSize = True
        Me.lblDiscount5.Location = New System.Drawing.Point(18, 218)
        Me.lblDiscount5.Name = "lblDiscount5"
        Me.lblDiscount5.Size = New System.Drawing.Size(58, 13)
        Me.lblDiscount5.TabIndex = 8
        Me.lblDiscount5.Text = "Discount 5"
        '
        'txtDiscount5
        '
        Me.txtDiscount5.Location = New System.Drawing.Point(138, 219)
        Me.txtDiscount5.MaxLength = 15
        Me.txtDiscount5.Name = "txtDiscount5"
        Me.txtDiscount5.Size = New System.Drawing.Size(100, 20)
        Me.txtDiscount5.TabIndex = 8
        '
        'ErrDiscount5
        '
        Me.ErrDiscount5.ContainerControl = Me
        '
        'lblDiscount6
        '
        Me.lblDiscount6.AutoSize = True
        Me.lblDiscount6.Location = New System.Drawing.Point(18, 238)
        Me.lblDiscount6.Name = "lblDiscount6"
        Me.lblDiscount6.Size = New System.Drawing.Size(58, 13)
        Me.lblDiscount6.TabIndex = 9
        Me.lblDiscount6.Text = "Discount 6"
        '
        'txtDiscount6
        '
        Me.txtDiscount6.Location = New System.Drawing.Point(138, 239)
        Me.txtDiscount6.MaxLength = 15
        Me.txtDiscount6.Name = "txtDiscount6"
        Me.txtDiscount6.Size = New System.Drawing.Size(100, 20)
        Me.txtDiscount6.TabIndex = 9
        '
        'ErrDiscount6
        '
        Me.ErrDiscount6.ContainerControl = Me
        '
        'lblDiscount7
        '
        Me.lblDiscount7.AutoSize = True
        Me.lblDiscount7.Location = New System.Drawing.Point(18, 264)
        Me.lblDiscount7.Name = "lblDiscount7"
        Me.lblDiscount7.Size = New System.Drawing.Size(58, 13)
        Me.lblDiscount7.TabIndex = 10
        Me.lblDiscount7.Text = "Discount 7"
        '
        'txtDiscount7
        '
        Me.txtDiscount7.Location = New System.Drawing.Point(138, 259)
        Me.txtDiscount7.MaxLength = 15
        Me.txtDiscount7.Name = "txtDiscount7"
        Me.txtDiscount7.Size = New System.Drawing.Size(100, 20)
        Me.txtDiscount7.TabIndex = 10
        '
        'ErrDiscount7
        '
        Me.ErrDiscount7.ContainerControl = Me
        '
        'lblDiscount8
        '
        Me.lblDiscount8.AutoSize = True
        Me.lblDiscount8.Location = New System.Drawing.Point(355, 139)
        Me.lblDiscount8.Name = "lblDiscount8"
        Me.lblDiscount8.Size = New System.Drawing.Size(58, 13)
        Me.lblDiscount8.TabIndex = 11
        Me.lblDiscount8.Text = "Discount 8"
        '
        'txtDiscount8
        '
        Me.txtDiscount8.Location = New System.Drawing.Point(487, 136)
        Me.txtDiscount8.MaxLength = 15
        Me.txtDiscount8.Name = "txtDiscount8"
        Me.txtDiscount8.Size = New System.Drawing.Size(100, 20)
        Me.txtDiscount8.TabIndex = 11
        '
        'ErrDiscount8
        '
        Me.ErrDiscount8.ContainerControl = Me
        '
        'lblDiscount9
        '
        Me.lblDiscount9.AutoSize = True
        Me.lblDiscount9.Location = New System.Drawing.Point(355, 159)
        Me.lblDiscount9.Name = "lblDiscount9"
        Me.lblDiscount9.Size = New System.Drawing.Size(58, 13)
        Me.lblDiscount9.TabIndex = 12
        Me.lblDiscount9.Text = "Discount 9"
        '
        'txtDiscount9
        '
        Me.txtDiscount9.Location = New System.Drawing.Point(487, 156)
        Me.txtDiscount9.MaxLength = 15
        Me.txtDiscount9.Name = "txtDiscount9"
        Me.txtDiscount9.Size = New System.Drawing.Size(100, 20)
        Me.txtDiscount9.TabIndex = 12
        '
        'ErrDiscount9
        '
        Me.ErrDiscount9.ContainerControl = Me
        '
        'lblDiscount10
        '
        Me.lblDiscount10.AutoSize = True
        Me.lblDiscount10.Location = New System.Drawing.Point(355, 179)
        Me.lblDiscount10.Name = "lblDiscount10"
        Me.lblDiscount10.Size = New System.Drawing.Size(64, 13)
        Me.lblDiscount10.TabIndex = 13
        Me.lblDiscount10.Text = "Discount 10"
        '
        'txtDiscount10
        '
        Me.txtDiscount10.Location = New System.Drawing.Point(487, 176)
        Me.txtDiscount10.MaxLength = 15
        Me.txtDiscount10.Name = "txtDiscount10"
        Me.txtDiscount10.Size = New System.Drawing.Size(100, 20)
        Me.txtDiscount10.TabIndex = 13
        '
        'ErrDiscount10
        '
        Me.ErrDiscount10.ContainerControl = Me
        '
        'lblLifeInsurance
        '
        Me.lblLifeInsurance.AutoSize = True
        Me.lblLifeInsurance.Location = New System.Drawing.Point(355, 199)
        Me.lblLifeInsurance.Name = "lblLifeInsurance"
        Me.lblLifeInsurance.Size = New System.Drawing.Size(74, 13)
        Me.lblLifeInsurance.TabIndex = 14
        Me.lblLifeInsurance.Text = "Life Insurance"
        '
        'txtLifeInsurance
        '
        Me.txtLifeInsurance.Location = New System.Drawing.Point(487, 196)
        Me.txtLifeInsurance.MaxLength = 15
        Me.txtLifeInsurance.Name = "txtLifeInsurance"
        Me.txtLifeInsurance.Size = New System.Drawing.Size(100, 20)
        Me.txtLifeInsurance.TabIndex = 14
        '
        'ErrLifeInsurance
        '
        Me.ErrLifeInsurance.ContainerControl = Me
        '
        'lblUsr_Id
        '
        Me.lblUsr_Id.AutoSize = True
        Me.lblUsr_Id.Location = New System.Drawing.Point(355, 267)
        Me.lblUsr_Id.Name = "lblUsr_Id"
        Me.lblUsr_Id.Size = New System.Drawing.Size(29, 13)
        Me.lblUsr_Id.TabIndex = 15
        Me.lblUsr_Id.Text = "User"
        '
        'cmbUsr_Id
        '
        Me.cmbUsr_Id.Location = New System.Drawing.Point(487, 261)
        Me.cmbUsr_Id.Name = "cmbUsr_Id"
        Me.cmbUsr_Id.Size = New System.Drawing.Size(100, 21)
        Me.cmbUsr_Id.TabIndex = 15
        '
        'ErrUsr_Id
        '
        Me.ErrUsr_Id.ContainerControl = Me
        '
        'lblCreationDate
        '
        Me.lblCreationDate.AutoSize = True
        Me.lblCreationDate.Location = New System.Drawing.Point(355, 291)
        Me.lblCreationDate.Name = "lblCreationDate"
        Me.lblCreationDate.Size = New System.Drawing.Size(72, 13)
        Me.lblCreationDate.TabIndex = 16
        Me.lblCreationDate.Text = "Creation Date"
        '
        'txtCreationDate
        '
        Me.txtCreationDate.Location = New System.Drawing.Point(487, 285)
        Me.txtCreationDate.MaxLength = 10
        Me.txtCreationDate.Name = "txtCreationDate"
        Me.txtCreationDate.ReadOnly = True
        Me.txtCreationDate.Size = New System.Drawing.Size(70, 20)
        Me.txtCreationDate.TabIndex = 16
        '
        'ErrCreationDate
        '
        Me.ErrCreationDate.ContainerControl = Me
        '
        'lblAmendDate
        '
        Me.lblAmendDate.AutoSize = True
        Me.lblAmendDate.Location = New System.Drawing.Point(355, 314)
        Me.lblAmendDate.Name = "lblAmendDate"
        Me.lblAmendDate.Size = New System.Drawing.Size(66, 13)
        Me.lblAmendDate.TabIndex = 17
        Me.lblAmendDate.Text = "Amend Date"
        '
        'txtAmendDate
        '
        Me.txtAmendDate.Location = New System.Drawing.Point(487, 308)
        Me.txtAmendDate.MaxLength = 10
        Me.txtAmendDate.Name = "txtAmendDate"
        Me.txtAmendDate.ReadOnly = True
        Me.txtAmendDate.Size = New System.Drawing.Size(70, 20)
        Me.txtAmendDate.TabIndex = 17
        '
        'ErrAmendDate
        '
        Me.ErrAmendDate.ContainerControl = Me
        '
        'Button1
        '
        Me.Button1.Location = New System.Drawing.Point(12, 287)
        Me.Button1.Name = "Button1"
        Me.Button1.Size = New System.Drawing.Size(215, 23)
        Me.Button1.TabIndex = 18
        Me.Button1.Text = "First Employment Discount"
        Me.Button1.UseVisualStyleBackColor = True
        Me.Button1.Visible = False
        '
        'Label1
        '
        Me.Label1.AutoSize = True
        Me.Label1.Location = New System.Drawing.Point(593, 199)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(176, 13)
        Me.Label1.TabIndex = 19
        Me.Label1.Text = "Maximum 7% of the insured amount."
        '
        'txtCopyFrom
        '
        Me.txtCopyFrom.Location = New System.Drawing.Point(94, 39)
        Me.txtCopyFrom.Name = "txtCopyFrom"
        Me.txtCopyFrom.Size = New System.Drawing.Size(100, 20)
        Me.txtCopyFrom.TabIndex = 25
        '
        'Button3
        '
        Me.Button3.Location = New System.Drawing.Point(94, 10)
        Me.Button3.Name = "Button3"
        Me.Button3.Size = New System.Drawing.Size(100, 23)
        Me.Button3.TabIndex = 24
        Me.Button3.Text = "Copy From"
        Me.Button3.UseVisualStyleBackColor = True
        '
        'txtCopyPeriodGroup
        '
        Me.txtCopyPeriodGroup.Location = New System.Drawing.Point(94, 65)
        Me.txtCopyPeriodGroup.Name = "txtCopyPeriodGroup"
        Me.txtCopyPeriodGroup.Size = New System.Drawing.Size(100, 20)
        Me.txtCopyPeriodGroup.TabIndex = 26
        '
        'GroupBox1
        '
        Me.GroupBox1.Controls.Add(Me.Label3)
        Me.GroupBox1.Controls.Add(Me.Label2)
        Me.GroupBox1.Controls.Add(Me.txtCopyPeriodGroup)
        Me.GroupBox1.Controls.Add(Me.txtCopyFrom)
        Me.GroupBox1.Controls.Add(Me.Button3)
        Me.GroupBox1.Location = New System.Drawing.Point(660, 106)
        Me.GroupBox1.Name = "GroupBox1"
        Me.GroupBox1.Size = New System.Drawing.Size(200, 91)
        Me.GroupBox1.TabIndex = 27
        Me.GroupBox1.TabStop = False
        '
        'Label3
        '
        Me.Label3.AutoSize = True
        Me.Label3.Location = New System.Drawing.Point(7, 68)
        Me.Label3.Name = "Label3"
        Me.Label3.Size = New System.Drawing.Size(69, 13)
        Me.Label3.TabIndex = 28
        Me.Label3.Text = "Period Group"
        '
        'Label2
        '
        Me.Label2.AutoSize = True
        Me.Label2.Location = New System.Drawing.Point(6, 42)
        Me.Label2.Name = "Label2"
        Me.Label2.Size = New System.Drawing.Size(81, 13)
        Me.Label2.TabIndex = 27
        Me.Label2.Text = "Employee Code"
        '
        'Label4
        '
        Me.Label4.AutoSize = True
        Me.Label4.Location = New System.Drawing.Point(355, 219)
        Me.Label4.Name = "Label4"
        Me.Label4.Size = New System.Drawing.Size(130, 13)
        Me.Label4.TabIndex = 29
        Me.Label4.Text = "Private Medical Insurance"
        '
        'txtMedical
        '
        Me.txtMedical.Location = New System.Drawing.Point(487, 216)
        Me.txtMedical.MaxLength = 15
        Me.txtMedical.Name = "txtMedical"
        Me.txtMedical.Size = New System.Drawing.Size(100, 20)
        Me.txtMedical.TabIndex = 28
        '
        'BtnNext
        '
        Me.BtnNext.Image = CType(resources.GetObject("BtnNext.Image"), System.Drawing.Image)
        Me.BtnNext.Location = New System.Drawing.Point(381, 31)
        Me.BtnNext.Name = "BtnNext"
        Me.BtnNext.Size = New System.Drawing.Size(75, 23)
        Me.BtnNext.TabIndex = 65
        Me.BtnNext.UseVisualStyleBackColor = True
        '
        'BtnPrevius
        '
        Me.BtnPrevius.Image = CType(resources.GetObject("BtnPrevius.Image"), System.Drawing.Image)
        Me.BtnPrevius.Location = New System.Drawing.Point(300, 31)
        Me.BtnPrevius.Name = "BtnPrevius"
        Me.BtnPrevius.Size = New System.Drawing.Size(75, 23)
        Me.BtnPrevius.TabIndex = 66
        Me.BtnPrevius.UseVisualStyleBackColor = True
        '
        'Label5
        '
        Me.Label5.AutoSize = True
        Me.Label5.Location = New System.Drawing.Point(18, 33)
        Me.Label5.Name = "Label5"
        Me.Label5.Size = New System.Drawing.Size(81, 13)
        Me.Label5.TabIndex = 68
        Me.Label5.Text = "Employee Code"
        '
        'txtEmployeeCode
        '
        Me.txtEmployeeCode.Location = New System.Drawing.Point(138, 34)
        Me.txtEmployeeCode.MaxLength = 15
        Me.txtEmployeeCode.Name = "txtEmployeeCode"
        Me.txtEmployeeCode.ReadOnly = True
        Me.txtEmployeeCode.Size = New System.Drawing.Size(100, 20)
        Me.txtEmployeeCode.TabIndex = 67
        '
        'Label6
        '
        Me.Label6.AutoSize = True
        Me.Label6.Location = New System.Drawing.Point(18, 59)
        Me.Label6.Name = "Label6"
        Me.Label6.Size = New System.Drawing.Size(84, 13)
        Me.Label6.TabIndex = 70
        Me.Label6.Text = "Employee Name"
        '
        'txtEmployeeName
        '
        Me.txtEmployeeName.Location = New System.Drawing.Point(138, 60)
        Me.txtEmployeeName.MaxLength = 15
        Me.txtEmployeeName.Name = "txtEmployeeName"
        Me.txtEmployeeName.ReadOnly = True
        Me.txtEmployeeName.Size = New System.Drawing.Size(316, 20)
        Me.txtEmployeeName.TabIndex = 69
        '
        'Label7
        '
        Me.Label7.AutoSize = True
        Me.Label7.Location = New System.Drawing.Point(355, 239)
        Me.Label7.Name = "Label7"
        Me.Label7.Size = New System.Drawing.Size(105, 13)
        Me.Label7.TabIndex = 72
        Me.Label7.Text = "Private Pension fund"
        '
        'txtPensionfund
        '
        Me.txtPensionfund.Location = New System.Drawing.Point(487, 236)
        Me.txtPensionfund.MaxLength = 15
        Me.txtPensionfund.Name = "txtPensionfund"
        Me.txtPensionfund.Size = New System.Drawing.Size(100, 20)
        Me.txtPensionfund.TabIndex = 71
        '
        'RemoveFirstEmployementFromALLActiveEmployeesToolStripMenuItem
        '
        Me.RemoveFirstEmployementFromALLActiveEmployeesToolStripMenuItem.Name = "RemoveFirstEmployementFromALLActiveEmployeesToolStripMenuItem"
        Me.RemoveFirstEmployementFromALLActiveEmployeesToolStripMenuItem.Size = New System.Drawing.Size(655, 22)
        Me.RemoveFirstEmployementFromALLActiveEmployeesToolStripMenuItem.Text = "Remove First Employement from ALL Active Employees"
        '
        'frmPrTxEmployeeDiscounts
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.SystemColors.GradientActiveCaption
        Me.ClientSize = New System.Drawing.Size(872, 503)
        Me.Controls.Add(Me.Label7)
        Me.Controls.Add(Me.txtPensionfund)
        Me.Controls.Add(Me.Label6)
        Me.Controls.Add(Me.txtEmployeeName)
        Me.Controls.Add(Me.Label5)
        Me.Controls.Add(Me.txtEmployeeCode)
        Me.Controls.Add(Me.BtnNext)
        Me.Controls.Add(Me.BtnPrevius)
        Me.Controls.Add(Me.Label4)
        Me.Controls.Add(Me.txtMedical)
        Me.Controls.Add(Me.GroupBox1)
        Me.Controls.Add(Me.Label1)
        Me.Controls.Add(Me.Button1)
        Me.Controls.Add(Me.lblId)
        Me.Controls.Add(Me.txtId)
        Me.Controls.Add(Me.lblPrdGrp_Code)
        Me.Controls.Add(Me.cmbPrdGrp_Code)
        Me.Controls.Add(Me.lblDiscount1)
        Me.Controls.Add(Me.txtDiscount1)
        Me.Controls.Add(Me.lblDiscount2)
        Me.Controls.Add(Me.txtDiscount2)
        Me.Controls.Add(Me.lblDiscount3)
        Me.Controls.Add(Me.txtDiscount3)
        Me.Controls.Add(Me.lblDiscount4)
        Me.Controls.Add(Me.txtDiscount4)
        Me.Controls.Add(Me.lblDiscount5)
        Me.Controls.Add(Me.txtDiscount5)
        Me.Controls.Add(Me.lblDiscount6)
        Me.Controls.Add(Me.txtDiscount6)
        Me.Controls.Add(Me.lblDiscount7)
        Me.Controls.Add(Me.txtDiscount7)
        Me.Controls.Add(Me.lblDiscount8)
        Me.Controls.Add(Me.txtDiscount8)
        Me.Controls.Add(Me.lblDiscount9)
        Me.Controls.Add(Me.txtDiscount9)
        Me.Controls.Add(Me.lblDiscount10)
        Me.Controls.Add(Me.txtDiscount10)
        Me.Controls.Add(Me.lblLifeInsurance)
        Me.Controls.Add(Me.txtLifeInsurance)
        Me.Controls.Add(Me.lblUsr_Id)
        Me.Controls.Add(Me.cmbUsr_Id)
        Me.Controls.Add(Me.lblCreationDate)
        Me.Controls.Add(Me.txtCreationDate)
        Me.Controls.Add(Me.lblAmendDate)
        Me.Controls.Add(Me.txtAmendDate)
        Me.Controls.Add(Me.TSC1)
        Me.Controls.Add(Me.sspStatus)
        Me.Controls.Add(Me.DG1)
        Me.Name = "frmPrTxEmployeeDiscounts"
        Me.Text = "Employee Discounts"
        Me.sspStatus.ResumeLayout(False)
        Me.sspStatus.PerformLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.TSC1.TopToolStripPanel.ResumeLayout(False)
        Me.TSC1.TopToolStripPanel.PerformLayout()
        Me.TSC1.ResumeLayout(False)
        Me.TSC1.PerformLayout()
        Me.TS1.ResumeLayout(False)
        Me.TS1.PerformLayout()
        CType(Me.ErrId, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEmp_Code, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrPrdGrp_Code, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDiscount1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDiscount2, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDiscount3, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDiscount4, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDiscount5, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDiscount6, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDiscount7, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDiscount8, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDiscount9, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDiscount10, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrLifeInsurance, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrUsr_Id, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrCreationDate, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrAmendDate, System.ComponentModel.ISupportInitialize).EndInit()
        Me.GroupBox1.ResumeLayout(False)
        Me.GroupBox1.PerformLayout()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
    Friend WithEvents lblId As System.Windows.Forms.Label
    Friend WithEvents txtId As System.Windows.Forms.TextBox
    Friend WithEvents ErrId As System.Windows.Forms.ErrorProvider
    Friend WithEvents ErrEmp_Code As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblPrdGrp_Code As System.Windows.Forms.Label
    Friend WithEvents cmbPrdGrp_Code As System.Windows.Forms.ComboBox
    Friend WithEvents ErrPrdGrp_Code As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblDiscount1 As System.Windows.Forms.Label
    Friend WithEvents txtDiscount1 As System.Windows.Forms.TextBox
    Friend WithEvents ErrDiscount1 As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblDiscount2 As System.Windows.Forms.Label
    Friend WithEvents txtDiscount2 As System.Windows.Forms.TextBox
    Friend WithEvents ErrDiscount2 As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblDiscount3 As System.Windows.Forms.Label
    Friend WithEvents txtDiscount3 As System.Windows.Forms.TextBox
    Friend WithEvents ErrDiscount3 As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblDiscount4 As System.Windows.Forms.Label
    Friend WithEvents txtDiscount4 As System.Windows.Forms.TextBox
    Friend WithEvents ErrDiscount4 As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblDiscount5 As System.Windows.Forms.Label
    Friend WithEvents txtDiscount5 As System.Windows.Forms.TextBox
    Friend WithEvents ErrDiscount5 As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblDiscount6 As System.Windows.Forms.Label
    Friend WithEvents txtDiscount6 As System.Windows.Forms.TextBox
    Friend WithEvents ErrDiscount6 As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblDiscount7 As System.Windows.Forms.Label
    Friend WithEvents txtDiscount7 As System.Windows.Forms.TextBox
    Friend WithEvents ErrDiscount7 As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblDiscount8 As System.Windows.Forms.Label
    Friend WithEvents txtDiscount8 As System.Windows.Forms.TextBox
    Friend WithEvents ErrDiscount8 As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblDiscount9 As System.Windows.Forms.Label
    Friend WithEvents txtDiscount9 As System.Windows.Forms.TextBox
    Friend WithEvents ErrDiscount9 As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblDiscount10 As System.Windows.Forms.Label
    Friend WithEvents txtDiscount10 As System.Windows.Forms.TextBox
    Friend WithEvents ErrDiscount10 As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblLifeInsurance As System.Windows.Forms.Label
    Friend WithEvents txtLifeInsurance As System.Windows.Forms.TextBox
    Friend WithEvents ErrLifeInsurance As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblUsr_Id As System.Windows.Forms.Label
    Friend WithEvents cmbUsr_Id As System.Windows.Forms.ComboBox
    Friend WithEvents ErrUsr_Id As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblCreationDate As System.Windows.Forms.Label
    Friend WithEvents txtCreationDate As System.Windows.Forms.TextBox
    Friend WithEvents ErrCreationDate As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblAmendDate As System.Windows.Forms.Label
    Friend WithEvents txtAmendDate As System.Windows.Forms.TextBox
    Friend WithEvents ErrAmendDate As System.Windows.Forms.ErrorProvider
    Friend WithEvents sspStatus As System.Windows.Forms.StatusStrip
    Friend WithEvents lblSSStatus As System.Windows.Forms.ToolStripStatusLabel
    Friend WithEvents DG1 As System.Windows.Forms.DataGridView
    Friend WithEvents TSC1 As System.Windows.Forms.ToolStripContainer
    Friend WithEvents TS1 As System.Windows.Forms.ToolStrip
    Friend WithEvents TSBNew As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBSave As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBDelete As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBExcel As System.Windows.Forms.ToolStripButton
    Friend WithEvents Button1 As System.Windows.Forms.Button
    Friend WithEvents Label1 As System.Windows.Forms.Label
    Friend WithEvents txtCopyFrom As System.Windows.Forms.TextBox
    Friend WithEvents Button3 As System.Windows.Forms.Button
    Friend WithEvents GroupBox1 As System.Windows.Forms.GroupBox
    Friend WithEvents Label3 As System.Windows.Forms.Label
    Friend WithEvents Label2 As System.Windows.Forms.Label
    Friend WithEvents txtCopyPeriodGroup As System.Windows.Forms.TextBox
    Friend WithEvents Label4 As System.Windows.Forms.Label
    Friend WithEvents txtMedical As System.Windows.Forms.TextBox
    Friend WithEvents Label6 As System.Windows.Forms.Label
    Friend WithEvents txtEmployeeName As System.Windows.Forms.TextBox
    Friend WithEvents Label5 As System.Windows.Forms.Label
    Friend WithEvents txtEmployeeCode As System.Windows.Forms.TextBox
    Friend WithEvents BtnNext As System.Windows.Forms.Button
    Friend WithEvents BtnPrevius As System.Windows.Forms.Button
    Friend WithEvents Label7 As System.Windows.Forms.Label
    Friend WithEvents txtPensionfund As System.Windows.Forms.TextBox
    Friend WithEvents dgcEmpDis_id As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmp_Code As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcPrdGrp_Code As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpDis_Discount1 As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpDis_Discount2 As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpDis_Discount3 As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpDis_Discount4 As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpDis_Discount5 As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpDis_Discount6 As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpDis_Discount7 As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpDis_Discount8 As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpDis_Discount9 As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpDis_Discount10 As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpDis_LifeInsurance As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcUsr_Id As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpDis_CreationDate As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcEmpDis_AmendDate As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents MedicalFund As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents PensionFund As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents ToolStripDropDownButton1 As ToolStripDropDownButton
    Friend WithEvents ToolStripButton3 As ToolStripButton
    Friend WithEvents ToolStripButton4 As ToolStripButton
    Friend WithEvents RemoToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents RemoveFirstEmployementFromALLActiveEmployeesToolStripMenuItem As ToolStripMenuItem
End Class
