Public Class cPrSsExtraTaxTable
    ' This Class has been autogenerated by Nodalsoft
    ' Do NOT adjust as it will be overwritten
    ' Generation Date : 13/02/2008 09:42:51
    '
    '
    '
    Inherits cPrSsExtraTaxTableDBTier
    '
    Private mTaxTbl_id As Integer
    Private mTaxTbl_Sequence As Integer
    Private mTaxTbl_BracketAmount As Double
    Private mTaxTbl_DedRate As Double
    Private mTaxTbl_ConRate As Double
    Private mTaxTbl_CreationDate As Date
    Private mTaxTbl_CreatedBy As Integer
    Private mTaxTbl_AmendDate As Date
    Private mTaxTbl_AmendBy As Integer
    Public Property TaxTbl_id() As Integer
        Get
            Return mTaxTbl_id
        End Get
        Set(ByVal Value As Integer)
            mTaxTbl_id = Value
        End Set
    End Property
    Public Property TaxTbl_Sequence() As Integer
        Get
            Return mTaxTbl_Sequence
        End Get
        Set(ByVal Value As Integer)
            mTaxTbl_Sequence = Value
        End Set
    End Property
    Public Property TaxTbl_BracketAmount() As Double
        Get
            Return mTaxTbl_BracketAmount
        End Get
        Set(ByVal Value As Double)
            mTaxTbl_BracketAmount = Value
        End Set
    End Property
    Public Property TaxTbl_DedRate() As Double
        Get
            Return mTaxTbl_DedRate
        End Get
        Set(ByVal Value As Double)
            mTaxTbl_DedRate = Value
        End Set
    End Property
    Public Property TaxTbl_ConRate() As Double
        Get
            Return mTaxTbl_ConRate
        End Get
        Set(ByVal Value As Double)
            mTaxTbl_ConRate = Value
        End Set
    End Property
    Public Property TaxTbl_CreationDate() As Date
        Get
            Return mTaxTbl_CreationDate
        End Get
        Set(ByVal Value As Date)
            mTaxTbl_CreationDate = Value
        End Set
    End Property
    Public Property TaxTbl_CreatedBy() As Integer
        Get
            Return mTaxTbl_CreatedBy
        End Get
        Set(ByVal Value As Integer)
            mTaxTbl_CreatedBy = Value
        End Set
    End Property
    Public Property TaxTbl_AmendDate() As Date
        Get
            Return mTaxTbl_AmendDate
        End Get
        Set(ByVal Value As Date)
            mTaxTbl_AmendDate = Value
        End Set
    End Property
    Public Property TaxTbl_AmendBy() As Integer
        Get
            Return mTaxTbl_AmendBy
        End Get
        Set(ByVal Value As Integer)
            mTaxTbl_AmendBy = Value
        End Set
    End Property
    Public Sub New()
    End Sub
    Public Sub New(ByVal Dr As DataRow)
        If Not Dr Is Nothing Then
            LoadDataRow(Dr)
        End If
    End Sub
    Public Sub New(ByVal tTaxTbl_id As Integer)
        If tTaxTbl_id <> 0 Then
            Init(tTaxTbl_id)
        End If
    End Sub
    Private Sub Init(ByVal tTaxTbl_id As Integer)
        Try
            Dim ds As DataSet
            ds = MyBase.GetByPK(tTaxTbl_id)
            If CheckDataSet(ds) Then
                LoadDataRow(ds.Tables(0).Rows(0))
            End If
        Catch ex As System.Exception
        End Try
    End Sub
    Private Sub LoadDataRow(ByVal dr As DataRow)
        mTaxTbl_id = DbNullToInt(dr.Item(0))
        mTaxTbl_Sequence = DbNullToInt(dr.Item(1))
        mTaxTbl_BracketAmount = DbNullToDouble(dr.Item(2))
        mTaxTbl_DedRate = DbNullToDouble(dr.Item(3))
        mTaxTbl_ConRate = DbNullToDouble(dr.Item(4))
        mTaxTbl_CreationDate = DbNullToDate(dr.Item(5))
        mTaxTbl_CreatedBy = DbNullToInt(dr.Item(6))
        mTaxTbl_AmendDate = DbNullToDate(dr.Item(7))
        mTaxTbl_AmendBy = DbNullToInt(dr.Item(8))
    End Sub
    Public Shadows Function Delete(ByVal tTaxTbl_id As Integer) As Boolean
        Try
            Dim Counter As Integer
            Dim TableCount As Integer
            Dim RecordCount As Integer
            Dim TransStr As String = ""
            Dim ds As DataSet
            ds = MyBase.CheckDeleteRecords(tTaxTbl_id)
            If CheckDataSet(ds) Then
                For Counter = 0 To ds.Tables.Count - 1
                    TableCount = TableCount + 1
                    RecordCount = RecordCount + DbNullToInt(ds.Tables(Counter).Rows(0).Item(0))
                    TransStr = TransStr & vbCrLf & "Table " & TableCount & "  Records " & RecordCount
                Next Counter
                If RecordCount = 0 Then
                    Return MyBase.Delete(tTaxTbl_id)
                Else
                    MsgBox("Transactions Exist For This item - Can not Delete" & TransStr, MsgBoxStyle.Critical)
                End If
            Else
                MsgBox("Failed to confirm that no records exist for this item - Can not Delete")
                Return False
            End If
        Catch ex As System.Exception
        End Try
    End Function
    '
    Public Shadows Function Save() As Boolean
        Try
            Return MyBase.Save(Me)
        Catch ex As System.Exception
            Return False
        End Try
    End Function
End Class


