' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 13/02/2008 09:42:51
'
'
Public Class cPrSsTaxTableDbTier
    '
    Inherits cDataTier
    '
    Protected Function GetByPK(ByVal tTaxTbl_id As Integer) As DataSet
        Dim Str As String
        Str = " SELECT" &
    " TaxTbl_id," &
    " TaxTbl_Sequence," &
    " TaxTbl_BracketAmount," &
    " TaxTbl_BracketRate," &
    " TaxTbl_CreationDate," &
    " TaxTbl_CreatedBy," &
    " TaxTbl_AmendDate," &
    " TaxTbl_AmendBy" &
    "  FROM PrSsTaxTable" &
    "  WHERE TaxTbl_id = " & tTaxTbl_id
        Return MyBase.GetData(Str)
    End Function
    Protected Function GetBySequence(ByVal Sequence As Integer) As DataSet
        Dim Str As String
        Str = " SELECT" &
    " TaxTbl_id," &
    " TaxTbl_Sequence," &
    " TaxTbl_BracketAmount," &
    " TaxTbl_BracketRate," &
    " TaxTbl_CreationDate," &
    " TaxTbl_CreatedBy," &
    " TaxTbl_AmendDate," &
    " TaxTbl_AmendBy" &
    "  FROM PrSsTaxTable" &
    "  WHERE TaxTbl_Sequence = " & Sequence
        Return MyBase.GetData(Str)
    End Function
    Protected Function Save(ByRef _cPrSsTaxTable As cPrSsTaxTable) As Boolean
        Dim SpParams As New ArrayList
        Dim SpNames As New ArrayList
        Dim Flag As Boolean = False
        With _cPrSsTaxTable
            SpParams.Add(.TaxTbl_id)                                         '(0)
            SpNames.Add("TaxTbl_id")                                         '(0)
            SpParams.Add(.TaxTbl_Sequence)                                   '(1)
            SpNames.Add("TaxTbl_Sequence")                                   '(1)
            SpParams.Add(.TaxTbl_BracketAmount)                              '(2)
            SpNames.Add("TaxTbl_BracketAmount")                              '(2)
            SpParams.Add(.TaxTbl_BracketRate)                                '(3)
            SpNames.Add("TaxTbl_BracketRate")                                '(3)
            SpParams.Add(.TaxTbl_CreationDate)                               '(4)
            SpNames.Add("TaxTbl_CreationDate")                               '(4)
            SpParams.Add(.TaxTbl_CreatedBy)                                  '(5)
            SpNames.Add("TaxTbl_CreatedBy")                                  '(5)
            SpParams.Add(.TaxTbl_AmendDate)                                  '(6)
            SpNames.Add("TaxTbl_AmendDate")                                  '(6)
            SpParams.Add(.TaxTbl_AmendBy)                                    '(7)
            SpNames.Add("TaxTbl_AmendBy")                                    '(7)
        End With
        SpNames.Add("NewId")                                             '(8)
        SpParams.Add(CInt(0))                                            '(8)
        If Me.StoredProcedure("AG_PrSsTaxTable_Save_Update", SpParams, SpNames, 8) Then
            If _cPrSsTaxTable.TaxTbl_id = 0 Then
                _cPrSsTaxTable.TaxTbl_id = DbNullToInt(SpParams(8))
            End If
            Return True
        Else
            Return False
        End If
    End Function
    Protected Function Delete(ByVal tTaxTbl_id As Integer) As Boolean
        Dim Str As String
        Dim Flag As Boolean = True
        Dim Exx As New System.Exception
        Try
            BeginTransaction()
            Str = " DELETE FROM PrSsTaxTable" &
    " WHERE TaxTbl_id = " & tTaxTbl_id
            If MyBase.ExecuteNonQuery(Str) = -1 Then
                Throw Exx
            End If
            CommitTransaction()
        Catch ex As Exception
            Rollback()
            Utils.ShowException(ex)
            Flag = False
        End Try
        Return Flag
    End Function
    Protected Function CheckDeleteRecords(ByVal tCode As Integer) As DataSet
        Dim ds As DataSet
        '    Generation Note : 13/02/2008 09:42:51 :- No Foriegn Key Constraints where found
        ds = Nothing
        Return ds
    End Function
End Class
