' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 13/02/2008 09:42:51
'
'
Public Class cPrSsSocialInsPeriodsDbTier
'
Inherits cDataTier
'
Protected Function GetByPK(ByVal tCode As Integer) as DataSet
Dim Str as String
Str = " SELECT" & _
        " SinPrd_Code," & _
        " SinPrd_DescriptionL," & _
        " SinPrd_DescriptionS" & _
    "  FROM PrSsSocialInsPeriods" & _
    "  WHERE SinPrd_Code = " & tCode
Return MyBase.GetData(Str)
End Function
Protected Function Save(ByVal _cPrSsSocialInsPeriods AS cPrSsSocialInsPeriods) As Boolean
Dim SpParams As New ArrayList
Dim SpNames As New ArrayList
Dim Flag As Boolean = False
With _cPrSsSocialInsPeriods
   SpParams.Add(.Code)                                              '(0)
   SpNames.Add("SinPrd_Code")                                       '(0)
   SpParams.Add(.DescriptionL)                                      '(1)
   SpNames.Add("SinPrd_DescriptionL")                               '(1)
   SpParams.Add(.DescriptionS)                                      '(2)
   SpNames.Add("SinPrd_DescriptionS")                               '(2)
End With
If Me.StoredProcedure("AG_PrSsSocialInsPeriods_Save_Update",SpParams,SpNames) Then
  Return True
Else
  Return False
End if
End Function
Protected Function Delete(ByVal tCode As Integer) as Boolean
Dim Str as String
Dim Flag As Boolean = True
Dim Exx As New System.Exception
   Try
         BeginTransaction()
         Str = " DELETE FROM PrSsSocialInsPeriods" & _
            " WHERE SinPrd_Code = " & tCode
         If MyBase.ExecuteNonQuery(Str) = -1 Then
                 Throw Exx
         End If
         CommitTransaction()
   Catch ex as Exception
            Rollback()
            Utils.ShowException(ex)
            Flag = False
   End Try
Return Flag
End Function
Protected Function CheckDeleteRecords(ByVal tCode As Integer) as DataSet
Dim Str as String
Str = " " & _
"SELECT COUNT(SinPrd_Code) " & _
" FROM PrMsPeriodCodes" & _
" WHERE SinPrd_Code = " & tCode &  _ 
" " & _
" "
Return GetData(Str)
End Function
End Class
