' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 17/03/2008 13:57:38
'
'
Public Class cPrMsPeriodGroupsDbTier
    '
    Inherits cDataTier
    '
    Protected Function GetByPK(ByVal tCode As String) As DataSet
        Dim Str As String
        Str = " SELECT" & _
                " PrdGrp_Code," & _
                " PrdGrp_Status," & _
                " PrdGpr_Year," & _
                " TemGrp_Code," & _
                " PrdGrp_DescriptionL" & _
            "  FROM PrMsPeriodGroups" & _
            "  WHERE PrdGrp_Code = '" & tCode & "'"
        Return MyBase.GetData(Str)
    End Function
    Protected Function Save(ByVal _cPrMsPeriodGroups As cPrMsPeriodGroups) As Boolean
        Dim SpParams As New ArrayList
        Dim SpNames As New ArrayList
        Dim Flag As Boolean = False
        With _cPrMsPeriodGroups
            SpParams.Add(.Code)                                              '(0)
            SpNames.Add("PrdGrp_Code")                                       '(0)
            SpParams.Add(.Status)                                            '(1)
            SpNames.Add("PrdGrp_Status")                                     '(1)
            SpParams.Add(.Year)                                              '(2)
            SpNames.Add("PrdGpr_Year")                                       '(2)
            SpParams.Add(.TemGrpCode)                                        '(3)
            SpNames.Add("TemGrp_Code")                                       '(3)
            SpParams.Add(.DescriptionL)                                      '(4)
            SpNames.Add("PrdGrp_DescriptionL")                               '(4)
        End With
        If Me.StoredProcedure("AG_PrMsPeriodGroups_Save_Update", SpParams, SpNames) Then
            Return True
        Else
            Return False
        End If
    End Function
    Protected Function Delete(ByVal tCode As String) As Boolean
        Dim Str As String
        Dim Flag As Boolean = True
        Dim Exx As New System.Exception
        Try
            BeginTransaction()
            Str = " DELETE FROM PrMsPeriodGroups" & _
               " WHERE PrdGrp_Code = '" & tCode & "'"
            If MyBase.ExecuteNonQuery(Str) = -1 Then
                Throw Exx
            End If
            CommitTransaction()
        Catch ex As Exception
            Rollback()
            Utils.ShowException(ex)
            Flag = False
        End Try
        Return Flag
    End Function
    Protected Function CheckDeleteRecords(ByVal tCode As String) As DataSet
        Dim Str As String
        Str = " " & _
        "SELECT COUNT(PrdGrp_Code) " & _
        " FROM PrMsPeriodCodes" & _
        " WHERE PrdGrp_Code = '" & tCode & "'" & _
        " " & _
        "SELECT COUNT(PrdGrp_Code) " & _
        " FROM PrTxEmployeeDiscounts" & _
        " WHERE PrdGrp_Code = '" & tCode & "'" & _
        " " & _
        " "
        Return GetData(Str)
    End Function
End Class
