<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmAdMsCurrencyRates
Inherits System.Windows.Forms.Form
<System.Diagnostics.DebuggerNonUserCode()> _
Protected Overrides Sub Dispose(ByVal disposing As Boolean)
If Disposing AndAlso components IsNot Nothing Then
components.Dispose()
End If
MyBase.Dispose(Disposing)
End Sub
Private components As System.ComponentModel.IContainer
' AutoGenerated Form by Nodalsoft
<System.Diagnostics.DebuggerStepThrough()> _
Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container
        Dim DataGridViewCellStyle1 As System.Windows.Forms.DataGridViewCellStyle = New System.Windows.Forms.DataGridViewCellStyle
        Dim DataGridViewCellStyle2 As System.Windows.Forms.DataGridViewCellStyle = New System.Windows.Forms.DataGridViewCellStyle
        Dim DataGridViewCellStyle3 As System.Windows.Forms.DataGridViewCellStyle = New System.Windows.Forms.DataGridViewCellStyle
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmAdMsCurrencyRates))
        Me.sspStatus = New System.Windows.Forms.StatusStrip
        Me.lblSSStatus = New System.Windows.Forms.ToolStripStatusLabel
        Me.DG1 = New System.Windows.Forms.DataGridView
        Me.dgcCurRte_id = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcCur_AlphaCode = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcCurRte_Rate = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcCurRte_EffectiveDate = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcCurRte_CreatedBy = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcCurRte_CreationDate = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcCurRte_AmendBy = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcCurRte_AmendDate = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dcolCurRte_CreatedByName = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dcolCurRte_AmendByName = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.TSC1 = New System.Windows.Forms.ToolStripContainer
        Me.TS1 = New System.Windows.Forms.ToolStrip
        Me.TSBNew = New System.Windows.Forms.ToolStripButton
        Me.TSBSave = New System.Windows.Forms.ToolStripButton
        Me.TSBDelete = New System.Windows.Forms.ToolStripButton
        Me.TSBExcel = New System.Windows.Forms.ToolStripButton
        Me.lblCurRte_id = New System.Windows.Forms.Label
        Me.txtCurRte_id = New System.Windows.Forms.TextBox
        Me.ErrCurRte_id = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblAlphaCode = New System.Windows.Forms.Label
        Me.cmbAlphaCode = New System.Windows.Forms.ComboBox
        Me.ErrAlphaCode = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblRate = New System.Windows.Forms.Label
        Me.txtRate = New System.Windows.Forms.TextBox
        Me.ErrRate = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblEffectiveDate = New System.Windows.Forms.Label
        Me.ErrEffectiveDate = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblCreatedBy = New System.Windows.Forms.Label
        Me.txtCreatedBy = New System.Windows.Forms.TextBox
        Me.ErrCreatedBy = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblCreationDate = New System.Windows.Forms.Label
        Me.ErrCreationDate = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblAmendBy = New System.Windows.Forms.Label
        Me.txtAmendBy = New System.Windows.Forms.TextBox
        Me.ErrAmendBy = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblAmendDate = New System.Windows.Forms.Label
        Me.ErrAmendDate = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.DateCreated = New System.Windows.Forms.DateTimePicker
        Me.DateAmend = New System.Windows.Forms.DateTimePicker
        Me.DateEffective = New System.Windows.Forms.DateTimePicker
        Me.sspStatus.SuspendLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.TSC1.TopToolStripPanel.SuspendLayout()
        Me.TSC1.SuspendLayout()
        Me.TS1.SuspendLayout()
        CType(Me.ErrCurRte_id, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrAlphaCode, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrRate, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrEffectiveDate, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrCreatedBy, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrCreationDate, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrAmendBy, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrAmendDate, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'sspStatus
        '
        Me.sspStatus.BackColor = System.Drawing.SystemColors.Control
        Me.sspStatus.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.lblSSStatus})
        Me.sspStatus.Location = New System.Drawing.Point(0, 529)
        Me.sspStatus.Name = "sspStatus"
        Me.sspStatus.Size = New System.Drawing.Size(987, 22)
        Me.sspStatus.TabIndex = 3
        Me.sspStatus.Text = "StatusStrip"
        '
        'lblSSStatus
        '
        Me.lblSSStatus.Name = "lblSSStatus"
        Me.lblSSStatus.Size = New System.Drawing.Size(0, 17)
        '
        'DG1
        '
        Me.DG1.AllowUserToAddRows = False
        Me.DG1.AllowUserToDeleteRows = False
        Me.DG1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DG1.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.dgcCurRte_id, Me.dgcCur_AlphaCode, Me.dgcCurRte_Rate, Me.dgcCurRte_EffectiveDate, Me.dgcCurRte_CreatedBy, Me.dgcCurRte_CreationDate, Me.dgcCurRte_AmendBy, Me.dgcCurRte_AmendDate, Me.dcolCurRte_CreatedByName, Me.dcolCurRte_AmendByName})
        Me.DG1.Location = New System.Drawing.Point(12, 222)
        Me.DG1.Name = "DG1"
        Me.DG1.ReadOnly = True
        Me.DG1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
        Me.DG1.Size = New System.Drawing.Size(963, 295)
        Me.DG1.TabIndex = 10
        '
        'dgcCurRte_id
        '
        Me.dgcCurRte_id.DataPropertyName = "CurRte_id"
        Me.dgcCurRte_id.FillWeight = 150.0!
        Me.dgcCurRte_id.HeaderText = "Id"
        Me.dgcCurRte_id.Name = "dgcCurRte_id"
        Me.dgcCurRte_id.ReadOnly = True
        Me.dgcCurRte_id.Width = 64
        '
        'dgcCur_AlphaCode
        '
        Me.dgcCur_AlphaCode.DataPropertyName = "Cur_AlphaCode"
        Me.dgcCur_AlphaCode.FillWeight = 150.0!
        Me.dgcCur_AlphaCode.HeaderText = "Alpha Code"
        Me.dgcCur_AlphaCode.Name = "dgcCur_AlphaCode"
        Me.dgcCur_AlphaCode.ReadOnly = True
        '
        'dgcCurRte_Rate
        '
        Me.dgcCurRte_Rate.DataPropertyName = "CurRte_Rate"
        Me.dgcCurRte_Rate.FillWeight = 150.0!
        Me.dgcCurRte_Rate.HeaderText = "Rate"
        Me.dgcCurRte_Rate.Name = "dgcCurRte_Rate"
        Me.dgcCurRte_Rate.ReadOnly = True
        '
        'dgcCurRte_EffectiveDate
        '
        Me.dgcCurRte_EffectiveDate.DataPropertyName = "CurRte_EffectiveDate"
        DataGridViewCellStyle1.Format = "dd-MM-yyyy"
        Me.dgcCurRte_EffectiveDate.DefaultCellStyle = DataGridViewCellStyle1
        Me.dgcCurRte_EffectiveDate.FillWeight = 150.0!
        Me.dgcCurRte_EffectiveDate.HeaderText = "Effective Date"
        Me.dgcCurRte_EffectiveDate.Name = "dgcCurRte_EffectiveDate"
        Me.dgcCurRte_EffectiveDate.ReadOnly = True
        Me.dgcCurRte_EffectiveDate.Width = 80
        '
        'dgcCurRte_CreatedBy
        '
        Me.dgcCurRte_CreatedBy.DataPropertyName = "CurRte_CreatedBy"
        Me.dgcCurRte_CreatedBy.FillWeight = 150.0!
        Me.dgcCurRte_CreatedBy.HeaderText = "Created By"
        Me.dgcCurRte_CreatedBy.Name = "dgcCurRte_CreatedBy"
        Me.dgcCurRte_CreatedBy.ReadOnly = True
        Me.dgcCurRte_CreatedBy.Visible = False
        Me.dgcCurRte_CreatedBy.Width = 60
        '
        'dgcCurRte_CreationDate
        '
        Me.dgcCurRte_CreationDate.DataPropertyName = "CurRte_CreationDate"
        DataGridViewCellStyle2.Format = "dd-MM-yyyy"
        Me.dgcCurRte_CreationDate.DefaultCellStyle = DataGridViewCellStyle2
        Me.dgcCurRte_CreationDate.FillWeight = 150.0!
        Me.dgcCurRte_CreationDate.HeaderText = "Creation Date"
        Me.dgcCurRte_CreationDate.Name = "dgcCurRte_CreationDate"
        Me.dgcCurRte_CreationDate.ReadOnly = True
        Me.dgcCurRte_CreationDate.Width = 80
        '
        'dgcCurRte_AmendBy
        '
        Me.dgcCurRte_AmendBy.DataPropertyName = "CurRte_AmendBy"
        Me.dgcCurRte_AmendBy.FillWeight = 150.0!
        Me.dgcCurRte_AmendBy.HeaderText = "Amend By"
        Me.dgcCurRte_AmendBy.Name = "dgcCurRte_AmendBy"
        Me.dgcCurRte_AmendBy.ReadOnly = True
        Me.dgcCurRte_AmendBy.Visible = False
        Me.dgcCurRte_AmendBy.Width = 60
        '
        'dgcCurRte_AmendDate
        '
        Me.dgcCurRte_AmendDate.DataPropertyName = "CurRte_AmendDate"
        DataGridViewCellStyle3.Format = "dd-MM-yyyy"
        Me.dgcCurRte_AmendDate.DefaultCellStyle = DataGridViewCellStyle3
        Me.dgcCurRte_AmendDate.FillWeight = 150.0!
        Me.dgcCurRte_AmendDate.HeaderText = "Amend Date"
        Me.dgcCurRte_AmendDate.Name = "dgcCurRte_AmendDate"
        Me.dgcCurRte_AmendDate.ReadOnly = True
        Me.dgcCurRte_AmendDate.Width = 80
        '
        'dcolCurRte_CreatedByName
        '
        Me.dcolCurRte_CreatedByName.DataPropertyName = "CurRte_CreatedByName"
        Me.dcolCurRte_CreatedByName.HeaderText = "Created By Name"
        Me.dcolCurRte_CreatedByName.Name = "dcolCurRte_CreatedByName"
        Me.dcolCurRte_CreatedByName.ReadOnly = True
        '
        'dcolCurRte_AmendByName
        '
        Me.dcolCurRte_AmendByName.DataPropertyName = "CurRte_AmendByName"
        Me.dcolCurRte_AmendByName.HeaderText = "Amend By Name"
        Me.dcolCurRte_AmendByName.Name = "dcolCurRte_AmendByName"
        Me.dcolCurRte_AmendByName.ReadOnly = True
        '
        'TSC1
        '
        Me.TSC1.BottomToolStripPanelVisible = False
        '
        'TSC1.ContentPanel
        '
        Me.TSC1.ContentPanel.Size = New System.Drawing.Size(987, 1)
        Me.TSC1.Dock = System.Windows.Forms.DockStyle.Top
        Me.TSC1.LeftToolStripPanelVisible = False
        Me.TSC1.Location = New System.Drawing.Point(0, 0)
        Me.TSC1.Name = "TSC1"
        Me.TSC1.RightToolStripPanelVisible = False
        Me.TSC1.Size = New System.Drawing.Size(987, 26)
        Me.TSC1.TabIndex = 12
        Me.TSC1.Text = "TSC1"
        '
        'TSC1.TopToolStripPanel
        '
        Me.TSC1.TopToolStripPanel.Controls.Add(Me.TS1)
        '
        'TS1
        '
        Me.TS1.Dock = System.Windows.Forms.DockStyle.None
        Me.TS1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.TSBNew, Me.TSBSave, Me.TSBDelete, Me.TSBExcel})
        Me.TS1.Location = New System.Drawing.Point(3, 0)
        Me.TS1.Name = "TS1"
        Me.TS1.Size = New System.Drawing.Size(252, 25)
        Me.TS1.TabIndex = 0
        '
        'TSBNew
        '
        Me.TSBNew.AutoSize = False
        Me.TSBNew.Image = CType(resources.GetObject("TSBNew.Image"), System.Drawing.Image)
        Me.TSBNew.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBNew.Name = "TSBNew"
        Me.TSBNew.Size = New System.Drawing.Size(60, 22)
        Me.TSBNew.Text = "New"
        Me.TSBNew.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBSave
        '
        Me.TSBSave.AutoSize = False
        Me.TSBSave.Image = CType(resources.GetObject("TSBSave.Image"), System.Drawing.Image)
        Me.TSBSave.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBSave.Name = "TSBSave"
        Me.TSBSave.Size = New System.Drawing.Size(60, 22)
        Me.TSBSave.Text = "Save"
        Me.TSBSave.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBDelete
        '
        Me.TSBDelete.AutoSize = False
        Me.TSBDelete.Image = CType(resources.GetObject("TSBDelete.Image"), System.Drawing.Image)
        Me.TSBDelete.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBDelete.Name = "TSBDelete"
        Me.TSBDelete.Size = New System.Drawing.Size(60, 22)
        Me.TSBDelete.Text = "Delete"
        Me.TSBDelete.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBExcel
        '
        Me.TSBExcel.AutoSize = False
        Me.TSBExcel.Image = Global.NodalPay.My.Resources.Resources.excel
        Me.TSBExcel.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBExcel.Name = "TSBExcel"
        Me.TSBExcel.Size = New System.Drawing.Size(60, 22)
        Me.TSBExcel.Text = "Excel"
        Me.TSBExcel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'lblCurRte_id
        '
        Me.lblCurRte_id.AutoSize = True
        Me.lblCurRte_id.Location = New System.Drawing.Point(37, 40)
        Me.lblCurRte_id.Name = "lblCurRte_id"
        Me.lblCurRte_id.Size = New System.Drawing.Size(16, 13)
        Me.lblCurRte_id.TabIndex = 0
        Me.lblCurRte_id.Text = "Id"
        '
        'txtCurRte_id
        '
        Me.txtCurRte_id.Enabled = False
        Me.txtCurRte_id.Location = New System.Drawing.Point(157, 40)
        Me.txtCurRte_id.MaxLength = 9
        Me.txtCurRte_id.Name = "txtCurRte_id"
        Me.txtCurRte_id.Size = New System.Drawing.Size(100, 20)
        Me.txtCurRte_id.TabIndex = 1
        '
        'ErrCurRte_id
        '
        Me.ErrCurRte_id.ContainerControl = Me
        '
        'lblAlphaCode
        '
        Me.lblAlphaCode.AutoSize = True
        Me.lblAlphaCode.Location = New System.Drawing.Point(37, 60)
        Me.lblAlphaCode.Name = "lblAlphaCode"
        Me.lblAlphaCode.Size = New System.Drawing.Size(62, 13)
        Me.lblAlphaCode.TabIndex = 2
        Me.lblAlphaCode.Text = "Alpha Code"
        '
        'cmbAlphaCode
        '
        Me.cmbAlphaCode.Location = New System.Drawing.Point(157, 60)
        Me.cmbAlphaCode.Name = "cmbAlphaCode"
        Me.cmbAlphaCode.Size = New System.Drawing.Size(100, 21)
        Me.cmbAlphaCode.TabIndex = 2
        '
        'ErrAlphaCode
        '
        Me.ErrAlphaCode.ContainerControl = Me
        '
        'lblRate
        '
        Me.lblRate.AutoSize = True
        Me.lblRate.Location = New System.Drawing.Point(37, 80)
        Me.lblRate.Name = "lblRate"
        Me.lblRate.Size = New System.Drawing.Size(30, 13)
        Me.lblRate.TabIndex = 3
        Me.lblRate.Text = "Rate"
        '
        'txtRate
        '
        Me.txtRate.Location = New System.Drawing.Point(157, 80)
        Me.txtRate.MaxLength = 15
        Me.txtRate.Name = "txtRate"
        Me.txtRate.Size = New System.Drawing.Size(100, 20)
        Me.txtRate.TabIndex = 3
        '
        'ErrRate
        '
        Me.ErrRate.ContainerControl = Me
        '
        'lblEffectiveDate
        '
        Me.lblEffectiveDate.AutoSize = True
        Me.lblEffectiveDate.Location = New System.Drawing.Point(37, 100)
        Me.lblEffectiveDate.Name = "lblEffectiveDate"
        Me.lblEffectiveDate.Size = New System.Drawing.Size(75, 13)
        Me.lblEffectiveDate.TabIndex = 4
        Me.lblEffectiveDate.Text = "Effective Date"
        '
        'ErrEffectiveDate
        '
        Me.ErrEffectiveDate.ContainerControl = Me
        '
        'lblCreatedBy
        '
        Me.lblCreatedBy.AutoSize = True
        Me.lblCreatedBy.Location = New System.Drawing.Point(37, 120)
        Me.lblCreatedBy.Name = "lblCreatedBy"
        Me.lblCreatedBy.Size = New System.Drawing.Size(59, 13)
        Me.lblCreatedBy.TabIndex = 5
        Me.lblCreatedBy.Text = "Created By"
        '
        'txtCreatedBy
        '
        Me.txtCreatedBy.BackColor = System.Drawing.SystemColors.Window
        Me.txtCreatedBy.Location = New System.Drawing.Point(157, 120)
        Me.txtCreatedBy.MaxLength = 4
        Me.txtCreatedBy.Name = "txtCreatedBy"
        Me.txtCreatedBy.ReadOnly = True
        Me.txtCreatedBy.Size = New System.Drawing.Size(100, 20)
        Me.txtCreatedBy.TabIndex = 5
        '
        'ErrCreatedBy
        '
        Me.ErrCreatedBy.ContainerControl = Me
        '
        'lblCreationDate
        '
        Me.lblCreationDate.AutoSize = True
        Me.lblCreationDate.Location = New System.Drawing.Point(37, 140)
        Me.lblCreationDate.Name = "lblCreationDate"
        Me.lblCreationDate.Size = New System.Drawing.Size(72, 13)
        Me.lblCreationDate.TabIndex = 6
        Me.lblCreationDate.Text = "Creation Date"
        '
        'ErrCreationDate
        '
        Me.ErrCreationDate.ContainerControl = Me
        '
        'lblAmendBy
        '
        Me.lblAmendBy.AutoSize = True
        Me.lblAmendBy.Location = New System.Drawing.Point(37, 160)
        Me.lblAmendBy.Name = "lblAmendBy"
        Me.lblAmendBy.Size = New System.Drawing.Size(55, 13)
        Me.lblAmendBy.TabIndex = 7
        Me.lblAmendBy.Text = "Amend By"
        '
        'txtAmendBy
        '
        Me.txtAmendBy.BackColor = System.Drawing.SystemColors.Window
        Me.txtAmendBy.Location = New System.Drawing.Point(157, 160)
        Me.txtAmendBy.MaxLength = 4
        Me.txtAmendBy.Name = "txtAmendBy"
        Me.txtAmendBy.ReadOnly = True
        Me.txtAmendBy.Size = New System.Drawing.Size(100, 20)
        Me.txtAmendBy.TabIndex = 7
        '
        'ErrAmendBy
        '
        Me.ErrAmendBy.ContainerControl = Me
        '
        'lblAmendDate
        '
        Me.lblAmendDate.AutoSize = True
        Me.lblAmendDate.Location = New System.Drawing.Point(37, 180)
        Me.lblAmendDate.Name = "lblAmendDate"
        Me.lblAmendDate.Size = New System.Drawing.Size(66, 13)
        Me.lblAmendDate.TabIndex = 8
        Me.lblAmendDate.Text = "Amend Date"
        '
        'ErrAmendDate
        '
        Me.ErrAmendDate.ContainerControl = Me
        '
        'DateCreated
        '
        Me.DateCreated.Enabled = False
        Me.DateCreated.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.DateCreated.Location = New System.Drawing.Point(157, 140)
        Me.DateCreated.Name = "DateCreated"
        Me.DateCreated.Size = New System.Drawing.Size(100, 20)
        Me.DateCreated.TabIndex = 13
        '
        'DateAmend
        '
        Me.DateAmend.Enabled = False
        Me.DateAmend.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.DateAmend.Location = New System.Drawing.Point(157, 180)
        Me.DateAmend.Name = "DateAmend"
        Me.DateAmend.Size = New System.Drawing.Size(100, 20)
        Me.DateAmend.TabIndex = 14
        '
        'DateEffective
        '
        Me.DateEffective.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.DateEffective.Location = New System.Drawing.Point(157, 100)
        Me.DateEffective.Name = "DateEffective"
        Me.DateEffective.Size = New System.Drawing.Size(100, 20)
        Me.DateEffective.TabIndex = 15
        '
        'frmAdMsCurrencyRates
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.SystemColors.GradientActiveCaption
        Me.ClientSize = New System.Drawing.Size(987, 551)
        Me.Controls.Add(Me.DateEffective)
        Me.Controls.Add(Me.DateAmend)
        Me.Controls.Add(Me.DateCreated)
        Me.Controls.Add(Me.lblCurRte_id)
        Me.Controls.Add(Me.txtCurRte_id)
        Me.Controls.Add(Me.lblAlphaCode)
        Me.Controls.Add(Me.cmbAlphaCode)
        Me.Controls.Add(Me.lblRate)
        Me.Controls.Add(Me.txtRate)
        Me.Controls.Add(Me.lblEffectiveDate)
        Me.Controls.Add(Me.lblCreatedBy)
        Me.Controls.Add(Me.txtCreatedBy)
        Me.Controls.Add(Me.lblCreationDate)
        Me.Controls.Add(Me.lblAmendBy)
        Me.Controls.Add(Me.txtAmendBy)
        Me.Controls.Add(Me.lblAmendDate)
        Me.Controls.Add(Me.TSC1)
        Me.Controls.Add(Me.sspStatus)
        Me.Controls.Add(Me.DG1)
        Me.Name = "frmAdMsCurrencyRates"
        Me.Text = "Currency Rates"
        Me.sspStatus.ResumeLayout(False)
        Me.sspStatus.PerformLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.TSC1.TopToolStripPanel.ResumeLayout(False)
        Me.TSC1.TopToolStripPanel.PerformLayout()
        Me.TSC1.ResumeLayout(False)
        Me.TSC1.PerformLayout()
        Me.TS1.ResumeLayout(False)
        Me.TS1.PerformLayout()
        CType(Me.ErrCurRte_id, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrAlphaCode, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrRate, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrEffectiveDate, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrCreatedBy, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrCreationDate, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrAmendBy, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrAmendDate, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
Friend WithEvents  lblCurRte_id As System.Windows.Forms.Label
Friend WithEvents  txtCurRte_id As System.Windows.Forms.TextBox
Friend WithEvents ErrCurRte_id As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblAlphaCode As System.Windows.Forms.Label
Friend WithEvents  cmbAlphaCode As System.Windows.Forms.ComboBox
Friend WithEvents ErrAlphaCode As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblRate As System.Windows.Forms.Label
Friend WithEvents  txtRate As System.Windows.Forms.TextBox
Friend WithEvents ErrRate As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblEffectiveDate As System.Windows.Forms.Label
    Friend WithEvents ErrEffectiveDate As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblCreatedBy As System.Windows.Forms.Label
Friend WithEvents  txtCreatedBy As System.Windows.Forms.TextBox
Friend WithEvents ErrCreatedBy As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblCreationDate As System.Windows.Forms.Label
    Friend WithEvents ErrCreationDate As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblAmendBy As System.Windows.Forms.Label
Friend WithEvents  txtAmendBy As System.Windows.Forms.TextBox
Friend WithEvents ErrAmendBy As System.Windows.Forms.ErrorProvider
    Friend WithEvents lblAmendDate As System.Windows.Forms.Label
    Friend WithEvents ErrAmendDate As System.Windows.Forms.ErrorProvider
    Friend WithEvents sspStatus As System.Windows.Forms.StatusStrip
Friend WithEvents lblSSStatus As System.Windows.Forms.ToolStripStatusLabel
Friend WithEvents DG1 As System.Windows.Forms.DataGridView
Friend WithEvents TSC1 As System.Windows.Forms.ToolStripContainer
Friend WithEvents TS1 As System.Windows.Forms.ToolStrip
Friend WithEvents TSBNew As System.Windows.Forms.ToolStripButton
Friend WithEvents TSBSave As System.Windows.Forms.ToolStripButton
Friend WithEvents TSBDelete As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBExcel As System.Windows.Forms.ToolStripButton
    Friend WithEvents DateEffective As System.Windows.Forms.DateTimePicker
    Friend WithEvents DateAmend As System.Windows.Forms.DateTimePicker
    Friend WithEvents DateCreated As System.Windows.Forms.DateTimePicker
    Friend WithEvents dgcCurRte_id As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcCur_AlphaCode As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcCurRte_Rate As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcCurRte_EffectiveDate As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcCurRte_CreatedBy As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcCurRte_CreationDate As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcCurRte_AmendBy As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dgcCurRte_AmendDate As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dcolCurRte_CreatedByName As System.Windows.Forms.DataGridViewTextBoxColumn
    Friend WithEvents dcolCurRte_AmendByName As System.Windows.Forms.DataGridViewTextBoxColumn
End Class
