' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 13/02/2008 09:42:51
'
'
Public Class cPrSsEmployeeStatusDbTier
'
Inherits cDataTier
'
Protected Function GetByPK(ByVal tEmpSta_Code As String) as DataSet
Dim Str as String
Str = " SELECT" & _
        " EmpSta_Code," & _
        " EmpSta_DescriptionL," & _
        " EmpSta_DescriptionS" & _
    "  FROM PrSsEmployeeStatus" & _
    "  WHERE EmpSta_Code = '" & tEmpSta_Code & "'"
Return MyBase.GetData(Str)
End Function
Protected Function Save(ByVal _cPrSsEmployeeStatus AS cPrSsEmployeeStatus) As Boolean
Dim SpParams As New ArrayList
Dim SpNames As New ArrayList
Dim Flag As Boolean = False
With _cPrSsEmployeeStatus
   SpParams.Add(.EmpSta_Code)                                       '(0)
   SpNames.Add("EmpSta_Code")                                       '(0)
   SpParams.Add(.EmpSta_DescriptionL)                               '(1)
   SpNames.Add("EmpSta_DescriptionL")                               '(1)
   SpParams.Add(.EmpSta_DescriptionS)                               '(2)
   SpNames.Add("EmpSta_DescriptionS")                               '(2)
End With
If Me.StoredProcedure("AG_PrSsEmployeeStatus_Save_Update",SpParams,SpNames) Then
  Return True
Else
  Return False
End if
End Function
Protected Function Delete(ByVal tEmpSta_Code As String) as Boolean
Dim Str as String
Dim Flag As Boolean = True
Dim Exx As New System.Exception
   Try
         BeginTransaction()
         Str = " DELETE FROM PrSsEmployeeStatus" & _
            " WHERE EmpSta_Code = '" & tEmpSta_Code & "'"
         If MyBase.ExecuteNonQuery(Str) = -1 Then
                 Throw Exx
         End If
         CommitTransaction()
   Catch ex as Exception
            Rollback()
            Utils.ShowException(ex)
            Flag = False
   End Try
Return Flag
End Function
Protected Function CheckDeleteRecords(ByVal tCode As String) as DataSet
 Dim ds As DataSet
'    Generation Note : 13/02/2008 09:42:51 :- No Foriegn Key Constraints where found
     ds = nothing
     Return ds
End Function
End Class
