<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmAdMsCurrency
Inherits System.Windows.Forms.Form
<System.Diagnostics.DebuggerNonUserCode()> _
Protected Overrides Sub Dispose(ByVal disposing As Boolean)
If Disposing AndAlso components IsNot Nothing Then
components.Dispose()
End If
MyBase.Dispose(Disposing)
End Sub
Private components As System.ComponentModel.IContainer
' AutoGenerated Form by Nodalsoft
<System.Diagnostics.DebuggerStepThrough()> _
Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmAdMsCurrency))
        Me.sspStatus = New System.Windows.Forms.StatusStrip
        Me.lblSSStatus = New System.Windows.Forms.ToolStripStatusLabel
        Me.DG1 = New System.Windows.Forms.DataGridView
        Me.dgcCur_AlphaCode = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcCur_NumericCode = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcCur_Description = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcCur_Symbol = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.dgcCur_IsActive = New System.Windows.Forms.DataGridViewTextBoxColumn
        Me.TSC1 = New System.Windows.Forms.ToolStripContainer
        Me.TS1 = New System.Windows.Forms.ToolStrip
        Me.TSBNew = New System.Windows.Forms.ToolStripButton
        Me.TSBSave = New System.Windows.Forms.ToolStripButton
        Me.TSBDelete = New System.Windows.Forms.ToolStripButton
        Me.TSBExcel = New System.Windows.Forms.ToolStripButton
        Me.lblAlphaCode = New System.Windows.Forms.Label
        Me.txtAlphaCode = New System.Windows.Forms.TextBox
        Me.ErrAlphaCode = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblNumericCode = New System.Windows.Forms.Label
        Me.txtNumericCode = New System.Windows.Forms.TextBox
        Me.ErrNumericCode = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblDescription = New System.Windows.Forms.Label
        Me.txtDescription = New System.Windows.Forms.TextBox
        Me.ErrDescription = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblSymbol = New System.Windows.Forms.Label
        Me.txtSymbol = New System.Windows.Forms.TextBox
        Me.ErrSymbol = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.lblIsActive = New System.Windows.Forms.Label
        Me.ErrIsActive = New System.Windows.Forms.ErrorProvider(Me.components)
        Me.CBIsActive = New System.Windows.Forms.CheckBox
        Me.sspStatus.SuspendLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.TSC1.TopToolStripPanel.SuspendLayout()
        Me.TSC1.SuspendLayout()
        Me.TS1.SuspendLayout()
        CType(Me.ErrAlphaCode, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrNumericCode, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrDescription, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrSymbol, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ErrIsActive, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'sspStatus
        '
        Me.sspStatus.BackColor = System.Drawing.SystemColors.Control
        Me.sspStatus.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.lblSSStatus})
        Me.sspStatus.Location = New System.Drawing.Point(0, 529)
        Me.sspStatus.Name = "sspStatus"
        Me.sspStatus.Size = New System.Drawing.Size(987, 22)
        Me.sspStatus.TabIndex = 3
        Me.sspStatus.Text = "StatusStrip"
        '
        'lblSSStatus
        '
        Me.lblSSStatus.Name = "lblSSStatus"
        Me.lblSSStatus.Size = New System.Drawing.Size(0, 17)
        '
        'DG1
        '
        Me.DG1.AllowUserToAddRows = False
        Me.DG1.AllowUserToDeleteRows = False
        Me.DG1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DG1.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.dgcCur_AlphaCode, Me.dgcCur_NumericCode, Me.dgcCur_Description, Me.dgcCur_Symbol, Me.dgcCur_IsActive})
        Me.DG1.Location = New System.Drawing.Point(12, 161)
        Me.DG1.Name = "DG1"
        Me.DG1.ReadOnly = True
        Me.DG1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
        Me.DG1.Size = New System.Drawing.Size(963, 355)
        Me.DG1.TabIndex = 10
        '
        'dgcCur_AlphaCode
        '
        Me.dgcCur_AlphaCode.DataPropertyName = "Cur_AlphaCode"
        Me.dgcCur_AlphaCode.FillWeight = 150.0!
        Me.dgcCur_AlphaCode.HeaderText = "Alpha Code"
        Me.dgcCur_AlphaCode.Name = "dgcCur_AlphaCode"
        Me.dgcCur_AlphaCode.ReadOnly = True
        Me.dgcCur_AlphaCode.Width = 60
        '
        'dgcCur_NumericCode
        '
        Me.dgcCur_NumericCode.DataPropertyName = "Cur_NumericCode"
        Me.dgcCur_NumericCode.FillWeight = 150.0!
        Me.dgcCur_NumericCode.HeaderText = "Numeric Code"
        Me.dgcCur_NumericCode.Name = "dgcCur_NumericCode"
        Me.dgcCur_NumericCode.ReadOnly = True
        Me.dgcCur_NumericCode.Width = 60
        '
        'dgcCur_Description
        '
        Me.dgcCur_Description.DataPropertyName = "Cur_Description"
        Me.dgcCur_Description.FillWeight = 150.0!
        Me.dgcCur_Description.HeaderText = "Description"
        Me.dgcCur_Description.Name = "dgcCur_Description"
        Me.dgcCur_Description.ReadOnly = True
        Me.dgcCur_Description.Width = 190
        '
        'dgcCur_Symbol
        '
        Me.dgcCur_Symbol.DataPropertyName = "Cur_Symbol"
        Me.dgcCur_Symbol.FillWeight = 150.0!
        Me.dgcCur_Symbol.HeaderText = "Symbol"
        Me.dgcCur_Symbol.Name = "dgcCur_Symbol"
        Me.dgcCur_Symbol.ReadOnly = True
        Me.dgcCur_Symbol.Width = 60
        '
        'dgcCur_IsActive
        '
        Me.dgcCur_IsActive.DataPropertyName = "Cur_IsActive"
        Me.dgcCur_IsActive.FillWeight = 150.0!
        Me.dgcCur_IsActive.HeaderText = "Is Active"
        Me.dgcCur_IsActive.Name = "dgcCur_IsActive"
        Me.dgcCur_IsActive.ReadOnly = True
        Me.dgcCur_IsActive.Width = 60
        '
        'TSC1
        '
        Me.TSC1.BottomToolStripPanelVisible = False
        '
        'TSC1.ContentPanel
        '
        Me.TSC1.ContentPanel.Size = New System.Drawing.Size(987, 1)
        Me.TSC1.Dock = System.Windows.Forms.DockStyle.Top
        Me.TSC1.LeftToolStripPanelVisible = False
        Me.TSC1.Location = New System.Drawing.Point(0, 0)
        Me.TSC1.Name = "TSC1"
        Me.TSC1.RightToolStripPanelVisible = False
        Me.TSC1.Size = New System.Drawing.Size(987, 26)
        Me.TSC1.TabIndex = 12
        Me.TSC1.Text = "TSC1"
        '
        'TSC1.TopToolStripPanel
        '
        Me.TSC1.TopToolStripPanel.Controls.Add(Me.TS1)
        '
        'TS1
        '
        Me.TS1.Dock = System.Windows.Forms.DockStyle.None
        Me.TS1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.TSBNew, Me.TSBSave, Me.TSBDelete, Me.TSBExcel})
        Me.TS1.Location = New System.Drawing.Point(3, 0)
        Me.TS1.Name = "TS1"
        Me.TS1.Size = New System.Drawing.Size(252, 25)
        Me.TS1.TabIndex = 0
        '
        'TSBNew
        '
        Me.TSBNew.AutoSize = False
        Me.TSBNew.Image = CType(resources.GetObject("TSBNew.Image"), System.Drawing.Image)
        Me.TSBNew.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBNew.Name = "TSBNew"
        Me.TSBNew.Size = New System.Drawing.Size(60, 22)
        Me.TSBNew.Text = "New"
        Me.TSBNew.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBSave
        '
        Me.TSBSave.AutoSize = False
        Me.TSBSave.Image = CType(resources.GetObject("TSBSave.Image"), System.Drawing.Image)
        Me.TSBSave.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBSave.Name = "TSBSave"
        Me.TSBSave.Size = New System.Drawing.Size(60, 22)
        Me.TSBSave.Text = "Save"
        Me.TSBSave.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBDelete
        '
        Me.TSBDelete.AutoSize = False
        Me.TSBDelete.Image = CType(resources.GetObject("TSBDelete.Image"), System.Drawing.Image)
        Me.TSBDelete.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBDelete.Name = "TSBDelete"
        Me.TSBDelete.Size = New System.Drawing.Size(60, 22)
        Me.TSBDelete.Text = "Delete"
        Me.TSBDelete.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'TSBExcel
        '
        Me.TSBExcel.AutoSize = False
        Me.TSBExcel.Image = Global.NodalPay.My.Resources.Resources.excel
        Me.TSBExcel.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSBExcel.Name = "TSBExcel"
        Me.TSBExcel.Size = New System.Drawing.Size(60, 22)
        Me.TSBExcel.Text = "Excel"
        Me.TSBExcel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'lblAlphaCode
        '
        Me.lblAlphaCode.AutoSize = True
        Me.lblAlphaCode.Location = New System.Drawing.Point(37, 40)
        Me.lblAlphaCode.Name = "lblAlphaCode"
        Me.lblAlphaCode.Size = New System.Drawing.Size(62, 13)
        Me.lblAlphaCode.TabIndex = 0
        Me.lblAlphaCode.Text = "Alpha Code"
        '
        'txtAlphaCode
        '
        Me.txtAlphaCode.Location = New System.Drawing.Point(157, 40)
        Me.txtAlphaCode.MaxLength = 3
        Me.txtAlphaCode.Name = "txtAlphaCode"
        Me.txtAlphaCode.Size = New System.Drawing.Size(69, 20)
        Me.txtAlphaCode.TabIndex = 1
        '
        'ErrAlphaCode
        '
        Me.ErrAlphaCode.ContainerControl = Me
        '
        'lblNumericCode
        '
        Me.lblNumericCode.AutoSize = True
        Me.lblNumericCode.Location = New System.Drawing.Point(37, 60)
        Me.lblNumericCode.Name = "lblNumericCode"
        Me.lblNumericCode.Size = New System.Drawing.Size(74, 13)
        Me.lblNumericCode.TabIndex = 2
        Me.lblNumericCode.Text = "Numeric Code"
        '
        'txtNumericCode
        '
        Me.txtNumericCode.Location = New System.Drawing.Point(157, 60)
        Me.txtNumericCode.MaxLength = 3
        Me.txtNumericCode.Name = "txtNumericCode"
        Me.txtNumericCode.Size = New System.Drawing.Size(69, 20)
        Me.txtNumericCode.TabIndex = 2
        '
        'ErrNumericCode
        '
        Me.ErrNumericCode.ContainerControl = Me
        '
        'lblDescription
        '
        Me.lblDescription.AutoSize = True
        Me.lblDescription.Location = New System.Drawing.Point(37, 80)
        Me.lblDescription.Name = "lblDescription"
        Me.lblDescription.Size = New System.Drawing.Size(60, 13)
        Me.lblDescription.TabIndex = 3
        Me.lblDescription.Text = "Description"
        '
        'txtDescription
        '
        Me.txtDescription.Location = New System.Drawing.Point(157, 80)
        Me.txtDescription.MaxLength = 30
        Me.txtDescription.Name = "txtDescription"
        Me.txtDescription.Size = New System.Drawing.Size(190, 20)
        Me.txtDescription.TabIndex = 3
        '
        'ErrDescription
        '
        Me.ErrDescription.ContainerControl = Me
        '
        'lblSymbol
        '
        Me.lblSymbol.AutoSize = True
        Me.lblSymbol.Location = New System.Drawing.Point(37, 100)
        Me.lblSymbol.Name = "lblSymbol"
        Me.lblSymbol.Size = New System.Drawing.Size(41, 13)
        Me.lblSymbol.TabIndex = 4
        Me.lblSymbol.Text = "Symbol"
        '
        'txtSymbol
        '
        Me.txtSymbol.Location = New System.Drawing.Point(157, 100)
        Me.txtSymbol.MaxLength = 1
        Me.txtSymbol.Name = "txtSymbol"
        Me.txtSymbol.Size = New System.Drawing.Size(69, 20)
        Me.txtSymbol.TabIndex = 4
        '
        'ErrSymbol
        '
        Me.ErrSymbol.ContainerControl = Me
        '
        'lblIsActive
        '
        Me.lblIsActive.AutoSize = True
        Me.lblIsActive.Location = New System.Drawing.Point(37, 120)
        Me.lblIsActive.Name = "lblIsActive"
        Me.lblIsActive.Size = New System.Drawing.Size(48, 13)
        Me.lblIsActive.TabIndex = 5
        Me.lblIsActive.Text = "Is Active"
        '
        'ErrIsActive
        '
        Me.ErrIsActive.ContainerControl = Me
        '
        'CBIsActive
        '
        Me.CBIsActive.AutoSize = True
        Me.CBIsActive.Location = New System.Drawing.Point(157, 120)
        Me.CBIsActive.Name = "CBIsActive"
        Me.CBIsActive.Size = New System.Drawing.Size(15, 14)
        Me.CBIsActive.TabIndex = 13
        Me.CBIsActive.UseVisualStyleBackColor = True
        '
        'frmAdMsCurrency
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.SystemColors.GradientActiveCaption
        Me.ClientSize = New System.Drawing.Size(987, 551)
        Me.Controls.Add(Me.CBIsActive)
        Me.Controls.Add(Me.lblAlphaCode)
        Me.Controls.Add(Me.txtAlphaCode)
        Me.Controls.Add(Me.lblNumericCode)
        Me.Controls.Add(Me.txtNumericCode)
        Me.Controls.Add(Me.lblDescription)
        Me.Controls.Add(Me.txtDescription)
        Me.Controls.Add(Me.lblSymbol)
        Me.Controls.Add(Me.txtSymbol)
        Me.Controls.Add(Me.lblIsActive)
        Me.Controls.Add(Me.TSC1)
        Me.Controls.Add(Me.sspStatus)
        Me.Controls.Add(Me.DG1)
        Me.Name = "frmAdMsCurrency"
        Me.Text = "Currency"
        Me.sspStatus.ResumeLayout(False)
        Me.sspStatus.PerformLayout()
        CType(Me.DG1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.TSC1.TopToolStripPanel.ResumeLayout(False)
        Me.TSC1.TopToolStripPanel.PerformLayout()
        Me.TSC1.ResumeLayout(False)
        Me.TSC1.PerformLayout()
        Me.TS1.ResumeLayout(False)
        Me.TS1.PerformLayout()
        CType(Me.ErrAlphaCode, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrNumericCode, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrDescription, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrSymbol, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ErrIsActive, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
Friend WithEvents  lblAlphaCode As System.Windows.Forms.Label
Friend WithEvents  txtAlphaCode As System.Windows.Forms.TextBox
Friend WithEvents ErrAlphaCode As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcCur_AlphaCode As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblNumericCode As System.Windows.Forms.Label
Friend WithEvents  txtNumericCode As System.Windows.Forms.TextBox
Friend WithEvents ErrNumericCode As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcCur_NumericCode As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblDescription As System.Windows.Forms.Label
Friend WithEvents  txtDescription As System.Windows.Forms.TextBox
Friend WithEvents ErrDescription As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcCur_Description As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblSymbol As System.Windows.Forms.Label
Friend WithEvents  txtSymbol As System.Windows.Forms.TextBox
Friend WithEvents ErrSymbol As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcCur_Symbol As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents  lblIsActive As System.Windows.Forms.Label
    Friend WithEvents ErrIsActive As System.Windows.Forms.ErrorProvider
Friend WithEvents dgcCur_IsActive As System.Windows.Forms.DataGridViewTextBoxColumn
Friend WithEvents sspStatus As System.Windows.Forms.StatusStrip
Friend WithEvents lblSSStatus As System.Windows.Forms.ToolStripStatusLabel
Friend WithEvents DG1 As System.Windows.Forms.DataGridView
Friend WithEvents TSC1 As System.Windows.Forms.ToolStripContainer
Friend WithEvents TS1 As System.Windows.Forms.ToolStrip
Friend WithEvents TSBNew As System.Windows.Forms.ToolStripButton
Friend WithEvents TSBSave As System.Windows.Forms.ToolStripButton
Friend WithEvents TSBDelete As System.Windows.Forms.ToolStripButton
    Friend WithEvents TSBExcel As System.Windows.Forms.ToolStripButton
    Friend WithEvents CBIsActive As System.Windows.Forms.CheckBox
End Class
