' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 13/02/2008 09:42:50
'
'
Public Class cPrMsPeriodDeductions
    '
    Inherits cPrMsPeriodDeductionsDbTier
    '
    Private mId As Integer
    Private mPrdCodCode As String
    Private mPrdGrpCode As String
    Private mDedCodCode As String
    Private mIsActive As String
    Public Property Id() As Integer
        Get
            Return mId
        End Get
        Set(ByVal Value As Integer)
            mId = Value
        End Set
    End Property
    Public Property PrdCodCode() As String
        Get
            Return mPrdCodCode
        End Get
        Set(ByVal Value As String)
            mPrdCodCode = Value
        End Set
    End Property
    Public Property PrdGrpCode() As String
        Get
            Return mPrdGrpCode
        End Get
        Set(ByVal Value As String)
            mPrdGrpCode = Value
        End Set
    End Property
    Public Property DedCodCode() As String
        Get
            Return mDedCodCode
        End Get
        Set(ByVal Value As String)
            mDedCodCode = Value
        End Set
    End Property
    Public Property IsActive() As String
        Get
            Return mIsActive
        End Get
        Set(ByVal Value As String)
            mIsActive = Value
        End Set
    End Property

    Public Sub New()
    End Sub
    Public Sub New(ByVal PerCode As String, ByVal PerGroup As String, ByVal EDCCode As String)
        Try
            Dim ds As DataSet
            ds = MyBase.GetByPK(PerCode, PerGroup, EDCCode)
            If CheckDataSet(ds) Then
                LoadDataRow(ds.Tables(0).Rows(0))
            End If
        Catch ex As System.Exception
        End Try
    End Sub

    Public Sub New(ByVal Dr As DataRow)
        If Not Dr Is Nothing Then
            LoadDataRow(Dr)
        End If
    End Sub
    Public Sub New(ByVal tId As Integer)
        If tId <> 0 Then
            Init(tId)
        End If
    End Sub
    Private Sub Init(ByVal tId As Integer)
        Try
            Dim ds As DataSet
            ds = MyBase.GetByPK(tId)
            If CheckDataSet(ds) Then
                LoadDataRow(ds.Tables(0).Rows(0))
            End If
        Catch ex As System.Exception
        End Try
    End Sub
    Private Sub LoadDataRow(ByVal dr As DataRow)
        mId = DbNullToInt(dr.Item(0))
        mPrdCodCode = DbNullToString(dr.Item(1))
        mPrdGrpCode = DbNullToString(dr.Item(2))
        mDedCodCode = DbNullToString(dr.Item(3))
        mIsActive = DbNullToString(dr.Item(4))
    End Sub
    Public Shadows Function Delete(ByVal tId As Integer) As Boolean
        Try
            Dim Counter As Integer
            Dim TableCount As Integer
            Dim RecordCount As Integer
            Dim TransStr As String = ""
            Dim ds As DataSet
            ds = MyBase.CheckDeleteRecords(tId)
            If CheckDataSet(ds) Then
                For Counter = 0 To ds.Tables.Count - 1
                    TableCount = TableCount + 1
                    RecordCount = RecordCount + DbNullToInt(ds.Tables(Counter).Rows(0).Item(0))
                    TransStr = TransStr & vbCrLf & "Table " & TableCount & "  Records " & RecordCount
                Next Counter
                If RecordCount = 0 Then
                    Return MyBase.Delete(tId)
                Else
                    MsgBox("Transactions Exist For This item - Can not Delete" & TransStr, MsgBoxStyle.Critical)
                End If
            Else
                MsgBox("Failed to confirm that no records exist for this item - Can not Delete")
                Return False
            End If
        Catch ex As System.Exception
        End Try
    End Function
    '
    Public Shadows Function Save() As Boolean
        Try
            Return MyBase.Save(Me)
        Catch ex As System.Exception
            Return False
        End Try
    End Function
End Class
