' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 13/02/2008 09:42:49
'
'
Public Class cPrMsDeductionCodesDbTier
'
Inherits cDataTier
'
Protected Function GetByPK(ByVal tCode As String) as DataSet
Dim Str as String
Str = " SELECT" & _
        " DedCod_Code," & _
        " DedTyp_Code," & _
        " DedCod_DescriptionL," & _
        " DedCod_DescriptionS," & _
        " DedCod_IsActive" & _
    "  FROM PrMsDeductionCodes" & _
    "  WHERE DedCod_Code = '" & tCode & "'"
Return MyBase.GetData(Str)
End Function
Protected Function Save(ByVal _cPrMsDeductionCodes AS cPrMsDeductionCodes) As Boolean
Dim SpParams As New ArrayList
Dim SpNames As New ArrayList
Dim Flag As Boolean = False
With _cPrMsDeductionCodes
   SpParams.Add(.Code)                                              '(0)
   SpNames.Add("DedCod_Code")                                       '(0)
   SpParams.Add(.DedTypCode)                                        '(1)
   SpNames.Add("DedTyp_Code")                                       '(1)
   SpParams.Add(.DescriptionL)                                      '(2)
   SpNames.Add("DedCod_DescriptionL")                               '(2)
   SpParams.Add(.DescriptionS)                                      '(3)
   SpNames.Add("DedCod_DescriptionS")                               '(3)
   SpParams.Add(.IsActive)                                          '(4)
   SpNames.Add("DedCod_IsActive")                                   '(4)
End With
If Me.StoredProcedure("AG_PrMsDeductionCodes_Save_Update",SpParams,SpNames) Then
  Return True
Else
  Return False
End if
End Function
Protected Function Delete(ByVal tCode As String) as Boolean
Dim Str as String
Dim Flag As Boolean = True
Dim Exx As New System.Exception
   Try
         BeginTransaction()
         Str = " DELETE FROM PrMsDeductionCodes" & _
            " WHERE DedCod_Code = '" & tCode & "'"
         If MyBase.ExecuteNonQuery(Str) = -1 Then
                 Throw Exx
         End If
         CommitTransaction()
   Catch ex as Exception
            Rollback()
            Utils.ShowException(ex)
            Flag = False
   End Try
Return Flag
End Function
Protected Function CheckDeleteRecords(ByVal tCode As String) as DataSet
Dim Str as String
Str = " " & _
"SELECT COUNT(DedCod_Code) " & _
" FROM PrMsPeriodDeductions" & _
" WHERE DedCod_Code = '" & tCode & "'" & _ 
" " & _
"SELECT COUNT(DedCod_Code) " & _
" FROM PrMsTemplateDeductions" & _
" WHERE DedCod_Code = '" & tCode & "'" & _ 
" " & _
" "
Return GetData(Str)
End Function
End Class
