' This Class has been autogenerated by Nodalsoft
' Do NOT adjust as it will be overwritten
' Generation Date : 13/02/2008 09:42:49
'
'
Public Class cPrAnTaxCardTypeDbTier
'
Inherits cDataTier
'
Protected Function GetByPK(ByVal tCode As String) as DataSet
Dim Str as String
Str = " SELECT" & _
        " TicTyp_Code," & _
        " TicTyp_DescriptionL," & _
        " TicTyp_DescriptionS," & _
        " TicTyp_IsActive" & _
    "  FROM PrAnTaxCardType" & _
    "  WHERE TicTyp_Code = '" & tCode & "'"
Return MyBase.GetData(Str)
End Function
Protected Function Save(ByVal _cPrAnTaxCardType AS cPrAnTaxCardType) As Boolean
Dim SpParams As New ArrayList
Dim SpNames As New ArrayList
Dim Flag As Boolean = False
With _cPrAnTaxCardType
   SpParams.Add(.Code)                                              '(0)
   SpNames.Add("TicTyp_Code")                                       '(0)
   SpParams.Add(.DescriptionL)                                      '(1)
   SpNames.Add("TicTyp_DescriptionL")                               '(1)
   SpParams.Add(.DescriptionS)                                      '(2)
   SpNames.Add("TicTyp_DescriptionS")                               '(2)
   SpParams.Add(.IsActive)                                          '(3)
   SpNames.Add("TicTyp_IsActive")                                   '(3)
End With
If Me.StoredProcedure("AG_PrAnTaxCardType_Save_Update",SpParams,SpNames) Then
  Return True
Else
  Return False
End if
End Function
Protected Function Delete(ByVal tCode As String) as Boolean
Dim Str as String
Dim Flag As Boolean = True
Dim Exx As New System.Exception
   Try
         BeginTransaction()
         Str = " DELETE FROM PrAnTaxCardType" & _
            " WHERE TicTyp_Code = '" & tCode & "'"
         If MyBase.ExecuteNonQuery(Str) = -1 Then
                 Throw Exx
         End If
         CommitTransaction()
   Catch ex as Exception
            Rollback()
            Utils.ShowException(ex)
            Flag = False
   End Try
Return Flag
End Function
Protected Function CheckDeleteRecords(ByVal tCode As String) as DataSet
 Dim ds As DataSet
'    Generation Note : 13/02/2008 09:42:49 :- No Foriegn Key Constraints where found
     ds = nothing
     Return ds
End Function
End Class
